<?xml version="1.0"?>
<Words xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Word word="" roman="contemporary" star="1"/>
  <Word word="" roman="concord" star="1"/>
  <Word word="" roman="contend" star="1"/>
  <Word word="" roman="chapter" star="1"/>
  <Word word="" roman="exclaim" star="1"/>
  <Word word="" roman="essay" star="1"/>
  <Word word="" roman="budget" star="1"/>
  <Word word="" roman="darling" star="1"/>
  <Word word="" roman="cheat" star="1"/>
  <Word word="" roman="bulletin" star="1"/>
  <Word word="" roman="cape" star="1"/>
  <Word word="" roman="canvas" star="1"/>
  <Word word="" roman="eighteenth" star="1"/>
  <Word word="" roman="Arab" star="1"/>
  <Word word="" roman="dew" star="1"/>
  <Word word="" roman="collision" star="1"/>
  <Word word="" roman="fasten" star="1"/>
  <Word word="" roman="Austria" star="1"/>
  <Word word="" roman="forecast" star="1"/>
  <Word word="" roman="bookstore" star="1"/>
  <Word word="" roman="amend" star="1"/>
  <Word word="" roman="document" star="1"/>
  <Word word="" roman="defeat" star="1"/>
  <Word word="" roman="comic" star="1"/>
  <Word word="" roman="astronomy" star="1"/>
  <Word word="" roman="correspondence" star="1"/>
  <Word word="" roman="empire" star="1"/>
  <Word word="" roman="comedian" star="1"/>
  <Word word="" roman="comment" star="1"/>
  <Word word="" roman="covering" star="1"/>
  <Word word="" roman="fill" star="1"/>
  <Word word="" roman="exchange" star="1"/>
  <Word word="" roman="fiber" star="1"/>
  <Word word="" roman="acorn" star="1"/>
  <Word word="" roman="auto" star="1"/>
  <Word word="" roman="elevate" star="1"/>
  <Word word="" roman="belief" star="1"/>
  <Word word="" roman="assembly" star="1"/>
  <Word word="" roman="couch" star="1"/>
  <Word word="" roman="existence" star="1"/>
  <Word word="" roman="architecture" star="1"/>
  <Word word="" roman="butterfly" star="1"/>
  <Word word="" roman="accuse" star="1"/>
  <Word word="" roman="attitude" star="1"/>
  <Word word="" roman="active" star="1"/>
  <Word word="" roman="accomplish" star="1"/>
  <Word word="" roman="finance" star="1"/>
  <Word word="" roman="ace" star="1"/>
  <Word word="" roman="brute" star="1"/>
  <Word word="" roman="accord" star="1"/>
  <Word word="" roman="cab" star="1"/>
  <Word word="" roman="foreigner" star="1"/>
  <Word word="" roman="expert" star="1"/>
  <Word word="" roman="balcony" star="1"/>
  <Word word="" roman="fifteenth" star="1"/>
  <Word word="" roman="feast" star="1"/>
  <Word word="" roman="flare" star="1"/>
  <Word word="" roman="flush" star="1"/>
  <Word word="" roman="courtesy" star="1"/>
  <Word word="" roman="beg" star="1"/>
  <Word word="" roman="ample" star="1"/>
  <Word word="" roman="circulate" star="1"/>
  <Word word="" roman="cholera" star="1"/>
  <Word word="" roman="ass" star="1"/>
  <Word word="" roman="circuit" star="1"/>
  <Word word="" roman="chapel" star="1"/>
  <Word word="" roman="female" star="1"/>
  <Word word="" roman="dwell" star="1"/>
  <Word word="" roman="communication" star="1"/>
  <Word word="" roman="backward" star="1"/>
  <Word word="" roman="discussion" star="1"/>
  <Word word="" roman="boot" star="1"/>
  <Word word="" roman="advanced" star="1"/>
  <Word word="" roman="atmosphere" star="1"/>
  <Word word="" roman="congress" star="1"/>
  <Word word="" roman="desolate" star="1"/>
  <Word word="" roman="connect" star="1"/>
  <Word word="" roman="earnest" star="1"/>
  <Word word="" roman="beefsteak" star="1"/>
  <Word word="" roman="dealer" star="1"/>
  <Word word="" roman="amaze" star="1"/>
  <Word word="" roman="coil" star="1"/>
  <Word word="" roman="alike" star="1"/>
  <Word word="" roman="destination" star="1"/>
  <Word word="" roman="accident" star="1"/>
  <Word word="" roman="catholic" star="1"/>
  <Word word="" roman="carrot" star="1"/>
  <Word word="" roman="driven" star="1"/>
  <Word word="" roman="bust" star="1"/>
  <Word word="" roman="cord" star="1"/>
  <Word word="" roman="bandage" star="1"/>
  <Word word="" roman="antenna" star="1"/>
  <Word word="" roman="acquire" star="1"/>
  <Word word="" roman="comprehensive" star="1"/>
  <Word word="" roman="deprive" star="1"/>
  <Word word="" roman="desperate" star="1"/>
  <Word word="" roman="conquer" star="1"/>
  <Word word="" roman="agency" star="1"/>
  <Word word="" roman="awful" star="1"/>
  <Word word="" roman="clutch" star="1"/>
  <Word word="" roman="dairy" star="1"/>
  <Word word="" roman="deny" star="1"/>
  <Word word="" roman="compete" star="1"/>
  <Word word="" roman="chestnut" star="1"/>
  <Word word="" roman="candidate" star="1"/>
  <Word word="" roman="earthly" star="1"/>
  <Word word="" roman="elegant" star="1"/>
  <Word word="" roman="beloved" star="1"/>
  <Word word="" roman="exception" star="1"/>
  <Word word="" roman="fantastic" star="1"/>
  <Word word="" roman="barrel" star="1"/>
  <Word word="" roman="dictate" star="1"/>
  <Word word="" roman="boom" star="1"/>
  <Word word="" roman="consist" star="1"/>
  <Word word="" roman="brook" star="1"/>
  <Word word="" roman="affirmative" star="1"/>
  <Word word="" roman="abandon" star="1"/>
  <Word word="" roman="feedback" star="1"/>
  <Word word="" roman="absorb" star="1"/>
  <Word word="" roman="allergy" star="1"/>
  <Word word="" roman="formation" star="1"/>
  <Word word="" roman="abundance" star="1"/>
  <Word word="" roman="applaud" star="1"/>
  <Word word="" roman="bodily" star="1"/>
  <Word word="" roman="dramatic" star="1"/>
  <Word word="" roman="affection" star="1"/>
  <Word word="" roman="discipline" star="1"/>
  <Word word="" roman="bald" star="1"/>
  <Word word="" roman="balance" star="1"/>
  <Word word="" roman="futile" star="1"/>
  <Word word="" roman="absolute" star="1"/>
  <Word word="" roman="encourage" star="1"/>
  <Word word="" roman="data" star="1"/>
  <Word word="" roman="dishonest" star="1"/>
  <Word word="" roman="eagle" star="1"/>
  <Word word="" roman="audience" star="1"/>
  <Word word="" roman="furthest" star="1"/>
  <Word word="" roman="calf" star="1"/>
  <Word word="" roman="crouch" star="1"/>
  <Word word="" roman="confuse" star="1"/>
  <Word word="" roman="blanket" star="1"/>
  <Word word="" roman="correspondent" star="1"/>
  <Word word="" roman="frail" star="1"/>
  <Word word="" roman="breast" star="1"/>
  <Word word="" roman="etc." star="1"/>
  <Word word="" roman="fraction" star="1"/>
  <Word word="" roman="deck" star="1"/>
  <Word word="" roman="fishing" star="1"/>
  <Word word="" roman="fashionable" star="1"/>
  <Word word="" roman="celebrated" star="1"/>
  <Word word="" roman="creative" star="1"/>
  <Word word="" roman="compact" star="1"/>
  <Word word="" roman="discourage" star="1"/>
  <Word word="" roman="capsule" star="1"/>
  <Word word="" roman="devise" star="1"/>
  <Word word="" roman="decrease" star="1"/>
  <Word word="" roman="exclusive" star="1"/>
  <Word word="" roman="cage" star="1"/>
  <Word word="" roman="development" star="1"/>
  <Word word="" roman="conception" star="1"/>
  <Word word="" roman="decree" star="1"/>
  <Word word="" roman="convey" star="1"/>
  <Word word="" roman="agriculture" star="1"/>
  <Word word="" roman="bewilder" star="1"/>
  <Word word="" roman="exact" star="1"/>
  <Word word="" roman="enforce" star="1"/>
  <Word word="" roman="biography" star="1"/>
  <Word word="" roman="bridegroom" star="1"/>
  <Word word="" roman="civilization" star="1"/>
  <Word word="" roman="Berlin" star="1"/>
  <Word word="" roman="cathedral" star="1"/>
  <Word word="" roman="dreadful" star="1"/>
  <Word word="" roman="cast" star="1"/>
  <Word word="" roman="dagger" star="1"/>
  <Word word="" roman="bargain" star="1"/>
  <Word word="" roman="barrier" star="1"/>
  <Word word="" roman="ceremony" star="1"/>
  <Word word="" roman="conceive" star="1"/>
  <Word word="" roman="enthusiasm" star="1"/>
  <Word word="" roman="estate" star="1"/>
  <Word word="" roman="bride" star="1"/>
  <Word word="" roman="dismiss" star="1"/>
  <Word word="" roman="academy" star="1"/>
  <Word word="" roman="blend" star="1"/>
  <Word word="" roman="barren" star="1"/>
  <Word word="" roman="congratulate" star="1"/>
  <Word word="" roman="drawing" star="1"/>
  <Word word="" roman="conservative" star="1"/>
  <Word word="" roman="depth" star="1"/>
  <Word word="" roman="assemble" star="1"/>
  <Word word="" roman="bankrupt" star="1"/>
  <Word word="" roman="algebra" star="1"/>
  <Word word="" roman="fillet" star="1"/>
  <Word word="" roman="deed" star="1"/>
  <Word word="" roman="calculate" star="1"/>
  <Word word="" roman="anticipate" star="1"/>
  <Word word="" roman="bounce" star="1"/>
  <Word word="" roman="cordial" star="1"/>
  <Word word="" roman="flute" star="1"/>
  <Word word="" roman="attractive" star="1"/>
  <Word word="" roman="correspond" star="1"/>
  <Word word="" roman="cave" star="1"/>
  <Word word="" roman="cinema" star="1"/>
  <Word word="" roman="afterward" star="1"/>
  <Word word="" roman="colonel" star="1"/>
  <Word word="" roman="diminish" star="1"/>
  <Word word="" roman="disorder" star="1"/>
  <Word word="" roman="examine" star="1"/>
  <Word word="" roman="division" star="1"/>
  <Word word="" roman="escort" star="1"/>
  <Word word="" roman="alternative" star="1"/>
  <Word word="" roman="career" star="1"/>
  <Word word="" roman="customer" star="1"/>
  <Word word="" roman="abrupt" star="1"/>
  <Word word="" roman="crane" star="1"/>
  <Word word="" roman="complement" star="1"/>
  <Word word="" roman="atom" star="1"/>
  <Word word="" roman="fluid" star="1"/>
  <Word word="" roman="community" star="1"/>
  <Word word="" roman="Denmark" star="1"/>
  <Word word="" roman="boss" star="1"/>
  <Word word="" roman="commodity" star="1"/>
  <Word word="" roman="error" star="1"/>
  <Word word="" roman="central" star="1"/>
  <Word word="" roman="bold" star="1"/>
  <Word word="" roman="committee" star="1"/>
  <Word word="" roman="forehand" star="1"/>
  <Word word="" roman="dye" star="1"/>
  <Word word="" roman="available" star="1"/>
  <Word word="" roman="absent-minded" star="1"/>
  <Word word="" roman="cereal" star="1"/>
  <Word word="" roman="dwelt" star="1"/>
  <Word word="" roman="fisherman" star="1"/>
  <Word word="" roman="continental" star="1"/>
  <Word word="" roman="ash" star="1"/>
  <Word word="" roman="agitate" star="1"/>
  <Word word="" roman="etiquette" star="1"/>
  <Word word="" roman="acute" star="1"/>
  <Word word="" roman="chart" star="1"/>
  <Word word="" roman="booking" star="1"/>
  <Word word="" roman="construction" star="1"/>
  <Word word="" roman="contrive" star="1"/>
  <Word word="" roman="cider" star="1"/>
  <Word word="" roman="beware" star="1"/>
  <Word word="" roman="condemn" star="1"/>
  <Word word="" roman="beneath" star="1"/>
  <Word word="" roman="fed" star="1"/>
  <Word word="" roman="evidence" star="1"/>
  <Word word="" roman="acid" star="1"/>
  <Word word="" roman="choir" star="1"/>
  <Word word="" roman="damn" star="1"/>
  <Word word="" roman="considering" star="1"/>
  <Word word="" roman="concert" star="1"/>
  <Word word="" roman="cafe" star="1"/>
  <Word word="" roman="applause" star="1"/>
  <Word word="" roman="beauty" star="1"/>
  <Word word="" roman="doorway" star="1"/>
  <Word word="" roman="ale" star="1"/>
  <Word word="" roman="aloud" star="1"/>
  <Word word="" roman="feeble" star="1"/>
  <Word word="" roman="chase" star="1"/>
  <Word word="" roman="dazzle" star="1"/>
  <Word word="" roman="analogy" star="1"/>
  <Word word="" roman="fever" star="1"/>
  <Word word="" roman="duly" star="1"/>
  <Word word="" roman="disappoint" star="1"/>
  <Word word="" roman="cafeteria" star="1"/>
  <Word word="" roman="foe" star="1"/>
  <Word word="" roman="apartment" star="1"/>
  <Word word="" roman="democracy" star="1"/>
  <Word word="" roman="cleaner" star="1"/>
  <Word word="" roman="flower" star="1"/>
  <Word word="" roman="dome" star="1"/>
  <Word word="" roman="chorus" star="1"/>
  <Word word="" roman="expansion" star="1"/>
  <Word word="" roman="brood" star="1"/>
  <Word word="" roman="cargo" star="1"/>
  <Word word="" roman="farthest" star="1"/>
  <Word word="" roman="complaint" star="1"/>
  <Word word="" roman="decent" star="1"/>
  <Word word="" roman="evolution" star="1"/>
  <Word word="" roman="bucket" star="1"/>
  <Word word="" roman="carbon" star="1"/>
  <Word word="" roman="cube" star="1"/>
  <Word word="" roman="flat" star="1"/>
  <Word word="" roman="donkey" star="1"/>
  <Word word="" roman="accent" star="1"/>
  <Word word="" roman="apt" star="1"/>
  <Word word="" roman="cocoa" star="1"/>
  <Word word="" roman="episode" star="1"/>
  <Word word="" roman="entertain" star="1"/>
  <Word word="" roman="behalf" star="1"/>
  <Word word="" roman="assert" star="1"/>
  <Word word="" roman="clash" star="1"/>
  <Word word="" roman="daze" star="1"/>
  <Word word="" roman="chamber" star="1"/>
  <Word word="" roman="dove" star="1"/>
  <Word word="" roman="abolish" star="1"/>
  <Word word="" roman="blew" star="1"/>
  <Word word="" roman="crisp" star="1"/>
  <Word word="" roman="emerge" star="1"/>
  <Word word="" roman="dice" star="1"/>
  <Word word="" roman="duty" star="1"/>
  <Word word="" roman="feature" star="1"/>
  <Word word="" roman="acting" star="1"/>
  <Word word="" roman="alcohol" star="1"/>
  <Word word="" roman="county" star="1"/>
  <Word word="" roman="conclude" star="1"/>
  <Word word="" roman="failure" star="1"/>
  <Word word="" roman="funeral" star="1"/>
  <Word word="" roman="crest" star="1"/>
  <Word word="" roman="coarse" star="1"/>
  <Word word="" roman="flying" star="1"/>
  <Word word="" roman="carpenter" star="1"/>
  <Word word="" roman="adjourn" star="1"/>
  <Word word="" roman="beam" star="1"/>
  <Word word="" roman="founder" star="1"/>
  <Word word="" roman="astonish" star="1"/>
  <Word word="" roman="factor" star="1"/>
  <Word word="" roman="adjust" star="1"/>
  <Word word="" roman="aim" star="1"/>
  <Word word="" roman="drag" star="1"/>
  <Word word="" roman="component" star="1"/>
  <Word word="" roman="compel" star="1"/>
  <Word word="" roman="baker" star="1"/>
  <Word word="" roman="clover" star="1"/>
  <Word word="" roman="fixed" star="1"/>
  <Word word="" roman="amid" star="1"/>
  <Word word="" roman="astronomer" star="1"/>
  <Word word="" roman="currency" star="1"/>
  <Word word="" roman="festival" star="1"/>
  <Word word="" roman="fortune" star="1"/>
  <Word word="" roman="climate" star="1"/>
  <Word word="" roman="district" star="1"/>
  <Word word="" roman="cling" star="1"/>
  <Word word="" roman="dormitory" star="1"/>
  <Word word="" roman="divine" star="1"/>
  <Word word="" roman="designate" star="1"/>
  <Word word="" roman="cigar" star="1"/>
  <Word word="" roman="bookshop" star="1"/>
  <Word word="" roman="berry" star="1"/>
  <Word word="" roman="economic" star="1"/>
  <Word word="" roman="disease" star="1"/>
  <Word word="" roman="crow" star="1"/>
  <Word word="" roman="diet" star="1"/>
  <Word word="" roman="butcher" star="1"/>
  <Word word="" roman="ambulance" star="1"/>
  <Word word="" roman="ad" star="1"/>
  <Word word="" roman="blade" star="1"/>
  <Word word="" roman="foster" star="1"/>
  <Word word="" roman="appendix" star="1"/>
  <Word word="" roman="creed" star="1"/>
  <Word word="" roman="china" star="1"/>
  <Word word="" roman="dot" star="1"/>
  <Word word="" roman="alarm" star="1"/>
  <Word word="" roman="fancy" star="1"/>
  <Word word="" roman="favorite" star="1"/>
  <Word word="" roman="epoch" star="1"/>
  <Word word="" roman="assume" star="1"/>
  <Word word="" roman="apposition" star="1"/>
  <Word word="" roman="cleaning" star="1"/>
  <Word word="" roman="bike" star="1"/>
  <Word word="" roman="errand" star="1"/>
  <Word word="" roman="defect" star="1"/>
  <Word word="" roman="dine" star="1"/>
  <Word word="" roman="confront" star="1"/>
  <Word word="" roman="fashion" star="1"/>
  <Word word="" roman="alas" star="1"/>
  <Word word="" roman="crude" star="1"/>
  <Word word="" roman="flung" star="1"/>
  <Word word="" roman="badge" star="1"/>
  <Word word="" roman="classify" star="1"/>
  <Word word="" roman="disaster" star="1"/>
  <Word word="" roman="cluster" star="1"/>
  <Word word="" roman="domain" star="1"/>
  <Word word="" roman="eager" star="1"/>
  <Word word="" roman="familiar" star="1"/>
  <Word word="" roman="colonist" star="1"/>
  <Word word="" roman="accumulate" star="1"/>
  <Word word="" roman="colloquial" star="1"/>
  <Word word="" roman="chess" star="1"/>
  <Word word="" roman="Asian" star="1"/>
  <Word word="" roman="birth" star="1"/>
  <Word word="" roman="dizzy" star="1"/>
  <Word word="" roman="bother" star="1"/>
  <Word word="" roman="dock" star="1"/>
  <Word word="" roman="attic" star="1"/>
  <Word word="" roman="amusing" star="1"/>
  <Word word="" roman="chat" star="1"/>
  <Word word="" roman="directly" star="1"/>
  <Word word="" roman="enchant" star="1"/>
  <Word word="" roman="apologize" star="1"/>
  <Word word="" roman="bump" star="1"/>
  <Word word="" roman="flipper" star="1"/>
  <Word word="" roman="basis" star="1"/>
  <Word word="" roman="admission" star="1"/>
  <Word word="" roman="chap" star="1"/>
  <Word word="" roman="daylight" star="1"/>
  <Word word="" roman="adhere" star="1"/>
  <Word word="" roman="fuss" star="1"/>
  <Word word="" roman="cream" star="1"/>
  <Word word="" roman="dumb" star="1"/>
  <Word word="" roman="cabinet" star="1"/>
  <Word word="" roman="frank" star="1"/>
  <Word word="" roman="core" star="1"/>
  <Word word="" roman="armchair" star="1"/>
  <Word word="" roman="dialogue" star="1"/>
  <Word word="" roman="edition" star="1"/>
  <Word word="" roman="envoy" star="1"/>
  <Word word="" roman="dare" star="1"/>
  <Word word="" roman="exit" star="1"/>
  <Word word="" roman="deal" star="1"/>
  <Word word="" roman="beetle" star="1"/>
  <Word word="" roman="flexible" star="1"/>
  <Word word="" roman="confident" star="1"/>
  <Word word="" roman="bait" star="1"/>
  <Word word="" roman="altar" star="1"/>
  <Word word="" roman="criminal" star="1"/>
  <Word word="" roman="arrest" star="1"/>
  <Word word="" roman="elsewhere" star="1"/>
  <Word word="" roman="ferry" star="1"/>
  <Word word="" roman="consult" star="1"/>
  <Word word="" roman="devote" star="1"/>
  <Word word="" roman="California" star="1"/>
  <Word word="" roman="distribution" star="1"/>
  <Word word="" roman="bulk" star="1"/>
  <Word word="" roman="annoy" star="1"/>
  <Word word="" roman="academic" star="1"/>
  <Word word="" roman="flame" star="1"/>
  <Word word="" roman="Alps" star="1"/>
  <Word word="" roman="fume" star="1"/>
  <Word word="" roman="fairy tale" star="1"/>
  <Word word="" roman="disgrace" star="1"/>
  <Word word="" roman="barn" star="1"/>
  <Word word="" roman="entry" star="1"/>
  <Word word="" roman="extent" star="1"/>
  <Word word="" roman="bet" star="1"/>
  <Word word="" roman="affectionate" star="1"/>
  <Word word="" roman="exaggerate" star="1"/>
  <Word word="" roman="canary" star="1"/>
  <Word word="" roman="exotic" star="1"/>
  <Word word="" roman="expensive" star="1"/>
  <Word word="" roman="celebrate" star="1"/>
  <Word word="" roman="curriculum" star="1"/>
  <Word word="" roman="epilog" star="1"/>
  <Word word="" roman="bind" star="1"/>
  <Word word="" roman="brass" star="1"/>
  <Word word="" roman="beard" star="1"/>
  <Word word="" roman="foundation" star="1"/>
  <Word word="" roman="deem" star="1"/>
  <Word word="" roman="context" star="1"/>
  <Word word="" roman="feeling" star="1"/>
  <Word word="" roman="drum" star="1"/>
  <Word word="" roman="auxiliary" star="1"/>
  <Word word="" roman="achieve" star="1"/>
  <Word word="" roman="evaluate" star="1"/>
  <Word word="" roman="edit" star="1"/>
  <Word word="" roman="casual" star="1"/>
  <Word word="" roman="crime" star="1"/>
  <Word word="" roman="competition" star="1"/>
  <Word word="" roman="consume" star="1"/>
  <Word word="" roman="basketball" star="1"/>
  <Word word="" roman="furniture" star="1"/>
  <Word word="" roman="fee" star="1"/>
  <Word word="" roman="Egypt" star="1"/>
  <Word word="" roman="automatic" star="1"/>
  <Word word="" roman="dozen" star="1"/>
  <Word word="" roman="dial" star="1"/>
  <Word word="" roman="cooking" star="1"/>
  <Word word="" roman="confession" star="1"/>
  <Word word="" roman="apparatus" star="1"/>
  <Word word="" roman="drown" star="1"/>
  <Word word="" roman="forgive" star="1"/>
  <Word word="" roman="footstep" star="1"/>
  <Word word="" roman="dignity" star="1"/>
  <Word word="" roman="director" star="1"/>
  <Word word="" roman="differ" star="1"/>
  <Word word="" roman="ambassador" star="1"/>
  <Word word="" roman="excite" star="1"/>
  <Word word="" roman="advertise" star="1"/>
  <Word word="" roman="bonnet" star="1"/>
  <Word word="" roman="Christ" star="1"/>
  <Word word="" roman="banana" star="1"/>
  <Word word="" roman="bacon" star="1"/>
  <Word word="" roman="camel" star="1"/>
  <Word word="" roman="conspicuous" star="1"/>
  <Word word="" roman="blank" star="1"/>
  <Word word="" roman="defense" star="1"/>
  <Word word="" roman="confess" star="1"/>
  <Word word="" roman="altitude" star="1"/>
  <Word word="" roman="assign" star="1"/>
  <Word word="" roman="fault" star="1"/>
  <Word word="" roman="Belgium" star="1"/>
  <Word word="" roman="entitle" star="1"/>
  <Word word="" roman="expenditure" star="1"/>
  <Word word="" roman="entire" star="1"/>
  <Word word="" roman="fret" star="1"/>
  <Word word="" roman="client" star="1"/>
  <Word word="" roman="flour" star="1"/>
  <Word word="" roman="accompany" star="1"/>
  <Word word="" roman="dissolve" star="1"/>
  <Word word="" roman="continuous" star="1"/>
  <Word word="" roman="absurd" star="1"/>
  <Word word="" roman="aspire" star="1"/>
  <Word word="" roman="freeze" star="1"/>
  <Word word="" roman="Arabia" star="1"/>
  <Word word="" roman="fully" star="1"/>
  <Word word="" roman="fountain pen" star="1"/>
  <Word word="" roman="confirm" star="1"/>
  <Word word="" roman="deliver" star="1"/>
  <Word word="" roman="brilliant" star="1"/>
  <Word word="" roman="frontier" star="1"/>
  <Word word="" roman="dirt" star="1"/>
  <Word word="" roman="event" star="1"/>
  <Word word="" roman="decay" star="1"/>
  <Word word="" roman="cough" star="1"/>
  <Word word="" roman="deaf" star="1"/>
  <Word word="" roman="curiosity" star="1"/>
  <Word word="" roman="accommodate" star="1"/>
  <Word word="" roman="circumstance" star="1"/>
  <Word word="" roman="bark" star="1"/>
  <Word word="" roman="cradle" star="1"/>
  <Word word="" roman="climax" star="1"/>
  <Word word="" roman="allowance" star="1"/>
  <Word word="" roman="eastern" star="1"/>
  <Word word="" roman="cloak" star="1"/>
  <Word word="" roman="circulation" star="1"/>
  <Word word="" roman="driving" star="1"/>
  <Word word="" roman="edge" star="1"/>
  <Word word="" roman="evacuate" star="1"/>
  <Word word="" roman="final" star="1"/>
  <Word word="" roman="affect" star="1"/>
  <Word word="" roman="crust" star="1"/>
  <Word word="" roman="employ" star="1"/>
  <Word word="" roman="decline" star="1"/>
  <Word word="" roman="bay" star="1"/>
  <Word word="" roman="Boston" star="1"/>
  <Word word="" roman="fabric" star="1"/>
  <Word word="" roman="broom" star="1"/>
  <Word word="" roman="appetite" star="1"/>
  <Word word="" roman="beef" star="1"/>
  <Word word="" roman="bond" star="1"/>
  <Word word="" roman="bloom" star="1"/>
  <Word word="" roman="addition" star="1"/>
  <Word word="" roman="drawer" star="1"/>
  <Word word="" roman="definition" star="1"/>
  <Word word="" roman="ease" star="1"/>
  <Word word="" roman="absence" star="1"/>
  <Word word="" roman="effect" star="1"/>
  <Word word="" roman="dip" star="1"/>
  <Word word="" roman="firework" star="1"/>
  <Word word="" roman="emergency" star="1"/>
  <Word word="" roman="compass" star="1"/>
  <Word word="" roman="collar" star="1"/>
  <Word word="" roman="expedition" star="1"/>
  <Word word="" roman="extensive" star="1"/>
  <Word word="" roman="delicious" star="1"/>
  <Word word="" roman="cunning" star="1"/>
  <Word word="" roman="ally" star="1"/>
  <Word word="" roman="caterpillar" star="1"/>
  <Word word="" roman="calm" star="1"/>
  <Word word="" roman="crack" star="1"/>
  <Word word="" roman="champion" star="1"/>
  <Word word="" roman="feed" star="1"/>
  <Word word="" roman="distinction" star="1"/>
  <Word word="" roman="clergyman" star="1"/>
  <Word word="" roman="economical" star="1"/>
  <Word word="" roman="blush" star="1"/>
  <Word word="" roman="confound" star="1"/>
  <Word word="" roman="disgust" star="1"/>
  <Word word="" roman="enlighten" star="1"/>
  <Word word="" roman="confidence" star="1"/>
  <Word word="" roman="bestow" star="1"/>
  <Word word="" roman="environment" star="1"/>
  <Word word="" roman="assure" star="1"/>
  <Word word="" roman="comprehension" star="1"/>
  <Word word="" roman="depend" star="1"/>
  <Word word="" roman="adjective" star="1"/>
  <Word word="" roman="fleet" star="1"/>
  <Word word="" roman="Dutch" star="1"/>
  <Word word="" roman="erect" star="1"/>
  <Word word="" roman="crisis" star="1"/>
  <Word word="" roman="farther" star="1"/>
  <Word word="" roman="charm" star="1"/>
  <Word word="" roman="educational" star="1"/>
  <Word word="" roman="crush" star="1"/>
  <Word word="" roman="establishment" star="1"/>
  <Word word="" roman="bunch" star="1"/>
  <Word word="" roman="forefather" star="1"/>
  <Word word="" roman="caution" star="1"/>
  <Word word="" roman="credit" star="1"/>
  <Word word="" roman="fury" star="1"/>
  <Word word="" roman="circular" star="1"/>
  <Word word="" roman="abode" star="1"/>
  <Word word="" roman="destructive" star="1"/>
  <Word word="" roman="admiration" star="1"/>
  <Word word="" roman="cultural" star="1"/>
  <Word word="" roman="cliff" star="1"/>
  <Word word="" roman="barometer" star="1"/>
  <Word word="" roman="fable" star="1"/>
  <Word word="" roman="container" star="1"/>
  <Word word="" roman="few" star="1"/>
  <Word word="" roman="authority" star="1"/>
  <Word word="" roman="debate" star="1"/>
  <Word word="" roman="approve" star="1"/>
  <Word word="" roman="financial" star="1"/>
  <Word word="" roman="explode" star="1"/>
  <Word word="" roman="drench" star="1"/>
  <Word word="" roman="airmail" star="1"/>
  <Word word="" roman="aluminum" star="1"/>
  <Word word="" roman="ditch" star="1"/>
  <Word word="" roman="assist" star="1"/>
  <Word word="" roman="dam" star="1"/>
  <Word word="" roman="beforehand" star="1"/>
  <Word word="" roman="dolphin" star="1"/>
  <Word word="" roman="flap" star="1"/>
  <Word word="" roman="downtown" star="1"/>
  <Word word="" roman="council" star="1"/>
  <Word word="" roman="behavior" star="1"/>
  <Word word="" roman="escalator" star="1"/>
  <Word word="" roman="colon" star="1"/>
  <Word word="" roman="drugstore" star="1"/>
  <Word word="" roman="exhaust" star="1"/>
  <Word word="" roman="frighten" star="1"/>
  <Word word="" roman="critical" star="1"/>
  <Word word="" roman="carnival" star="1"/>
  <Word word="" roman="champagne" star="1"/>
  <Word word="" roman="dandelion" star="1"/>
  <Word word="" roman="extend" star="1"/>
  <Word word="" roman="fork" star="1"/>
  <Word word="" roman="disappear" star="1"/>
  <Word word="" roman="especial" star="1"/>
  <Word word="" roman="curve" star="1"/>
  <Word word="" roman="cultivate" star="1"/>
  <Word word="" roman="elder" star="1"/>
  <Word word="" roman="deer" star="1"/>
  <Word word="" roman="brake" star="1"/>
  <Word word="" roman="commissioner" star="1"/>
  <Word word="" roman="faith" star="1"/>
  <Word word="" roman="challenge" star="1"/>
  <Word word="" roman="Englishman" star="1"/>
  <Word word="" roman="ambition" star="1"/>
  <Word word="" roman="bar" star="1"/>
  <Word word="" roman="electronic" star="1"/>
  <Word word="" roman="fantasy" star="1"/>
  <Word word="" roman="departure" star="1"/>
  <Word word="" roman="federal" star="1"/>
  <Word word="" roman="crayon" star="1"/>
  <Word word="" roman="dispose" star="1"/>
  <Word word="" roman="flash" star="1"/>
  <Word word="" roman="charity" star="1"/>
  <Word word="" roman="argue" star="1"/>
  <Word word="" roman="conceit" star="1"/>
  <Word word="" roman="conquest" star="1"/>
  <Word word="" roman="blast" star="1"/>
  <Word word="" roman="fuel" star="1"/>
  <Word word="" roman="ending" star="1"/>
  <Word word="" roman="cope" star="1"/>
  <Word word="" roman="dense" star="1"/>
  <Word word="" roman="examination" star="1"/>
  <Word word="" roman="dilemma" star="1"/>
  <Word word="" roman="conscience" star="1"/>
  <Word word="" roman="basin" star="1"/>
  <Word word="" roman="cylinder" star="1"/>
  <Word word="" roman="firm" star="1"/>
  <Word word="" roman="blown" star="1"/>
  <Word word="" roman="fortunate" star="1"/>
  <Word word="" roman="composition" star="1"/>
  <Word word="" roman="awkward" star="1"/>
  <Word word="" roman="brow" star="1"/>
  <Word word="" roman="choice" star="1"/>
  <Word word="" roman="armor" star="1"/>
  <Word word="" roman="deadly" star="1"/>
  <Word word="" roman="equator" star="1"/>
  <Word word="" roman="era" star="1"/>
  <Word word="" roman="execute" star="1"/>
  <Word word="" roman="fiction" star="1"/>
  <Word word="" roman="costume" star="1"/>
  <Word word="" roman="converse" star="1"/>
  <Word word="" roman="expression" star="1"/>
  <Word word="" roman="attain" star="1"/>
  <Word word="" roman="cherry" star="1"/>
  <Word word="" roman="film" star="1"/>
  <Word word="" roman="attire" star="1"/>
  <Word word="" roman="carol" star="1"/>
  <Word word="" roman="dash" star="1"/>
  <Word word="" roman="bang" star="1"/>
  <Word word="" roman="file" star="1"/>
  <Word word="" roman="adore" star="1"/>
  <Word word="" roman="clatter" star="1"/>
  <Word word="" roman="condense" star="1"/>
  <Word word="" roman="closet" star="1"/>
  <Word word="" roman="centimeter" star="1"/>
  <Word word="" roman="commercial" star="1"/>
  <Word word="" roman="excessive" star="1"/>
  <Word word="" roman="flavor" star="1"/>
  <Word word="" roman="candle" star="1"/>
  <Word word="" roman="carnation" star="1"/>
  <Word word="" roman="alien" star="1"/>
  <Word word="" roman="ensemble" star="1"/>
  <Word word="" roman="fruitful" star="1"/>
  <Word word="" roman="concrete" star="1"/>
  <Word word="" roman="aware" star="1"/>
  <Word word="" roman="Christian" star="1"/>
  <Word word="" roman="carrier" star="1"/>
  <Word word="" roman="canal" star="1"/>
  <Word word="" roman="fragment" star="1"/>
  <Word word="" roman="crew" star="1"/>
  <Word word="" roman="efficient" star="1"/>
  <Word word="" roman="exposure" star="1"/>
  <Word word="" roman="doubtful" star="1"/>
  <Word word="" roman="banner" star="1"/>
  <Word word="" roman="contempt" star="1"/>
  <Word word="" roman="biscuit" star="1"/>
  <Word word="" roman="dusty" star="1"/>
  <Word word="" roman="convention" star="1"/>
  <Word word="" roman="boast" star="1"/>
  <Word word="" roman="emigrate" star="1"/>
  <Word word="" roman="attentive" star="1"/>
  <Word word="" roman="bow" star="1"/>
  <Word word="" roman="capable" star="1"/>
  <Word word="" roman="extreme" star="1"/>
  <Word word="" roman="channel" star="1"/>
  <Word word="" roman="buzz" star="1"/>
  <Word word="" roman="chemist" star="1"/>
  <Word word="" roman="deposit" star="1"/>
  <Word word="" roman="Brazil" star="1"/>
  <Word word="" roman="coral" star="1"/>
  <Word word="" roman="bowl" star="1"/>
  <Word word="" roman="endless" star="1"/>
  <Word word="" roman="crooked" star="1"/>
  <Word word="" roman="diligent" star="1"/>
  <Word word="" roman="disgusting" star="1"/>
  <Word word="" roman="anxiety" star="1"/>
  <Word word="" roman="blossom" star="1"/>
  <Word word="" roman="adorn" star="1"/>
  <Word word="" roman="fling" star="1"/>
  <Word word="" roman="beast" star="1"/>
  <Word word="" roman="daring" star="1"/>
  <Word word="" roman="claw" star="1"/>
  <Word word="" roman="chatter" star="1"/>
  <Word word="" roman="democratic" star="1"/>
  <Word word="" roman="clinic" star="1"/>
  <Word word="" roman="clothing" star="1"/>
  <Word word="" roman="faculty" star="1"/>
  <Word word="" roman="arose" star="1"/>
  <Word word="" roman="access" star="1"/>
  <Word word="" roman="flank" star="1"/>
  <Word word="" roman="conference" star="1"/>
  <Word word="" roman="cell" star="1"/>
  <Word word="" roman="appeal" star="1"/>
  <Word word="" roman="cane" star="1"/>
  <Word word="" roman="bilingual" star="1"/>
  <Word word="" roman="divert" star="1"/>
  <Word word="" roman="bolt" star="1"/>
  <Word word="" roman="accommodation" star="1"/>
  <Word word="" roman="chuckle" star="1"/>
  <Word word="" roman="classic" star="1"/>
  <Word word="" roman="excursion" star="1"/>
  <Word word="" roman="apology" star="1"/>
  <Word word="" roman="administrator" star="1"/>
  <Word word="" roman="debt" star="1"/>
  <Word word="" roman="equip" star="1"/>
  <Word word="" roman="assurance" star="1"/>
  <Word word="" roman="eve" star="1"/>
  <Word word="" roman="compound" star="1"/>
  <Word word="" roman="crab" star="1"/>
  <Word word="" roman="accuracy" star="1"/>
  <Word word="" roman="excess" star="1"/>
  <Word word="" roman="communicate" star="1"/>
  <Word word="" roman="airfield" star="1"/>
  <Word word="" roman="ashamed" star="1"/>
  <Word word="" roman="attribute" star="1"/>
  <Word word="" roman="dried" star="1"/>
  <Word word="" roman="connection" star="1"/>
  <Word word="" roman="fate" star="1"/>
  <Word word="" roman="adventure" star="1"/>
  <Word word="" roman="comma" star="1"/>
  <Word word="" roman="folly" star="1"/>
  <Word word="" roman="cannon" star="1"/>
  <Word word="" roman="flea" star="1"/>
  <Word word="" roman="draft" star="1"/>
  <Word word="" roman="displease" star="1"/>
  <Word word="" roman="comrade" star="1"/>
  <Word word="" roman="brisk" star="1"/>
  <Word word="" roman="dragon" star="1"/>
  <Word word="" roman="fled" star="1"/>
  <Word word="" roman="constant" star="1"/>
  <Word word="" roman="daybreak" star="1"/>
  <Word word="" roman="droop" star="1"/>
  <Word word="" roman="arithmetic" star="1"/>
  <Word word="" roman="delegate" star="1"/>
  <Word word="" roman="cutting" star="1"/>
  <Word word="" roman="dig" star="1"/>
  <Word word="" roman="favorable" star="1"/>
  <Word word="" roman="communism" star="1"/>
  <Word word="" roman="engage" star="1"/>
  <Word word="" roman="dual" star="1"/>
  <Word word="" roman="furnish" star="1"/>
  <Word word="" roman="dispute" star="1"/>
  <Word word="" roman="cycle" star="1"/>
  <Word word="" roman="furnace" star="1"/>
  <Word word="" roman="define" star="1"/>
  <Word word="" roman="curse" star="1"/>
  <Word word="" roman="carpet" star="1"/>
  <Word word="" roman="advantage" star="1"/>
  <Word word="" roman="explore" star="1"/>
  <Word word="" roman="dentist" star="1"/>
  <Word word="" roman="calcium" star="1"/>
  <Word word="" roman="eyebrow" star="1"/>
  <Word word="" roman="fundamental" star="1"/>
  <Word word="" roman="dainty" star="1"/>
  <Word word="" roman="additional" star="1"/>
  <Word word="" roman="fireplace" star="1"/>
  <Word word="" roman="continual" star="1"/>
  <Word word="" roman="besides" star="1"/>
  <Word word="" roman="awhile" star="1"/>
  <Word word="" roman="beverage" star="1"/>
  <Word word="" roman="cork" star="1"/>
  <Word word="" roman="bid" star="1"/>
  <Word word="" roman="chosen" star="1"/>
  <Word word="" roman="anticipation" star="1"/>
  <Word word="" roman="cooperate" star="1"/>
  <Word word="" roman="alert" star="1"/>
  <Word word="" roman="artistic" star="1"/>
  <Word word="" roman="breadth" star="1"/>
  <Word word="" roman="commit" star="1"/>
  <Word word="" roman="clip" star="1"/>
  <Word word="" roman="chirp" star="1"/>
  <Word word="" roman="bowel" star="1"/>
  <Word word="" roman="content" star="1"/>
  <Word word="" roman="bade" star="1"/>
  <Word word="" roman="definite" star="1"/>
  <Word word="" roman="foresee" star="1"/>
  <Word word="" roman="consideration" star="1"/>
  <Word word="" roman="envy" star="1"/>
  <Word word="" roman="bathe" star="1"/>
  <Word word="" roman="appropriate" star="1"/>
  <Word word="" roman="bore" star="1"/>
  <Word word="" roman="exile" star="1"/>
  <Word word="" roman="cottage" star="1"/>
  <Word word="" roman="disguise" star="1"/>
  <Word word="" roman="economy" star="1"/>
  <Word word="" roman="cautious" star="1"/>
  <Word word="" roman="comfort" star="1"/>
  <Word word="" roman="activity" star="1"/>
  <Word word="" roman="Bible" star="1"/>
  <Word word="" roman="efficiency" star="1"/>
  <Word word="" roman="civil" star="1"/>
  <Word word="" roman="function" star="1"/>
  <Word word="" roman="drift" star="1"/>
  <Word word="" roman="effort" star="1"/>
  <Word word="" roman="conclusion" star="1"/>
  <Word word="" roman="alight" star="1"/>
  <Word word="" roman="exactly" star="1"/>
  <Word word="" roman="foam" star="1"/>
  <Word word="" roman="category" star="1"/>
  <Word word="" roman="anchor" star="1"/>
  <Word word="" roman="enclose" star="1"/>
  <Word word="" roman="advertisement" star="1"/>
  <Word word="" roman="await" star="1"/>
  <Word word="" roman="carve" star="1"/>
  <Word word="" roman="apply" star="1"/>
  <Word word="" roman="bury" star="1"/>
  <Word word="" roman="blond" star="1"/>
  <Word word="" roman="cuckoo" star="1"/>
  <Word word="" roman="cosmetic" star="1"/>
  <Word word="" roman="behold" star="1"/>
  <Word word="" roman="frost" star="1"/>
  <Word word="" roman="flourish" star="1"/>
  <Word word="" roman="education" star="1"/>
  <Word word="" roman="crimson" star="1"/>
  <Word word="" roman="bullet" star="1"/>
  <Word word="" roman="confide" star="1"/>
  <Word word="" roman="cancel" star="1"/>
  <Word word="" roman="entrance" star="1"/>
  <Word word="" roman="despise" star="1"/>
  <Word word="" roman="chilly" star="1"/>
  <Word word="" roman="dedicate" star="1"/>
  <Word word="" roman="disk" star="1"/>
  <Word word="" roman="burst" star="1"/>
  <Word word="" roman="computer" star="1"/>
  <Word word="" roman="consumption" star="1"/>
  <Word word="" roman="contrast" star="1"/>
  <Word word="" roman="ecstasy" star="1"/>
  <Word word="" roman="bedroom" star="1"/>
  <Word word="" roman="flake" star="1"/>
  <Word word="" roman="default" star="1"/>
  <Word word="" roman="bosom" star="1"/>
  <Word word="" roman="election" star="1"/>
  <Word word="" roman="cabbage" star="1"/>
  <Word word="" roman="Anglo-Saxon" star="1"/>
  <Word word="" roman="dealt" star="1"/>
  <Word word="" roman="encounter" star="1"/>
  <Word word="" roman="bug" star="1"/>
  <Word word="" roman="everlasting" star="1"/>
  <Word word="" roman="cowboy" star="1"/>
  <Word word="" roman="commission" star="1"/>
  <Word word="" roman="campus" star="1"/>
  <Word word="" roman="devour" star="1"/>
  <Word word="" roman="affirm" star="1"/>
  <Word word="" roman="contract" star="1"/>
  <Word word="" roman="blessing" star="1"/>
  <Word word="" roman="effective" star="1"/>
  <Word word="" roman="chandelier" star="1"/>
  <Word word="" roman="exclude" star="1"/>
  <Word word="" roman="adequate" star="1"/>
  <Word word="" roman="conduct" star="1"/>
  <Word word="" roman="Frenchman" star="1"/>
  <Word word="" roman="detect" star="1"/>
  <Word word="" roman="cripple" star="1"/>
  <Word word="" roman="asphalt" star="1"/>
  <Word word="" roman="allied" star="1"/>
  <Word word="" roman="copper" star="1"/>
  <Word word="" roman="damp" star="1"/>
  <Word word="" roman="awoke" star="1"/>
  <Word word="" roman="clam" star="1"/>
  <Word word="" roman="button" star="1"/>
  <Word word="" roman="emphasis" star="1"/>
  <Word word="" roman="creature" star="1"/>
  <Word word="" roman="courageous" star="1"/>
  <Word word="" roman="doom" star="1"/>
  <Word word="" roman="antecedent" star="1"/>
  <Word word="" roman="beak" star="1"/>
  <Word word="" roman="constitute" star="1"/>
  <Word word="" roman="furious" star="1"/>
  <Word word="" roman="compliment" star="1"/>
  <Word word="" roman="easily" star="1"/>
  <Word word="" roman="aboard" star="1"/>
  <Word word="" roman="appreciation" star="1"/>
  <Word word="" roman="booth" star="1"/>
  <Word word="" roman="downward" star="1"/>
  <Word word="" roman="concise" star="1"/>
  <Word word="" roman="fright" star="1"/>
  <Word word="" roman="A.M." star="1"/>
  <Word word="" roman="annual" star="1"/>
  <Word word="" roman="arrival" star="1"/>
  <Word word="" roman="combine" star="1"/>
  <Word word="" roman="betray" star="1"/>
  <Word word="" roman="ability" star="1"/>
  <Word word="" roman="editor" star="1"/>
  <Word word="" roman="clay" star="1"/>
  <Word word="" roman="cherish" star="1"/>
  <Word word="" roman="acquaint" star="1"/>
  <Word word="" roman="foremost" star="1"/>
  <Word word="" roman="allege" star="1"/>
  <Word word="" roman="appearance" star="1"/>
  <Word word="" roman="amateur" star="1"/>
  <Word word="" roman="desert" star="1"/>
  <Word word="" roman="crumble" star="1"/>
  <Word word="" roman="borne" star="1"/>
  <Word word="" roman="display" star="1"/>
  <Word word="" roman="dislike" star="1"/>
  <Word word="" roman="boundary" star="1"/>
  <Word word="" roman="colt" star="1"/>
  <Word word="" roman="breathe" star="1"/>
  <Word word="" roman="creep" star="1"/>
  <Word word="" roman="fence" star="1"/>
  <Word word="" roman="cancer" star="1"/>
  <Word word="" roman="ashore" star="1"/>
  <Word word="" roman="distinguish" star="1"/>
  <Word word="" roman="chocolate" star="1"/>
  <Word word="" roman="decisive" star="1"/>
  <Word word="" roman="abuse" star="1"/>
  <Word word="" roman="agony" star="1"/>
  <Word word="" roman="collection" star="1"/>
  <Word word="" roman="expectation" star="1"/>
  <Word word="" roman="anonymous" star="1"/>
  <Word word="" roman="complex" star="1"/>
  <Word word="" roman="consonant" star="1"/>
  <Word word="" roman="devil" star="1"/>
  <Word word="" roman="fatal" star="1"/>
  <Word word="" roman="fowl" star="1"/>
  <Word word="" roman="fort" star="1"/>
  <Word word="" roman="comet" star="1"/>
  <Word word="" roman="airship" star="1"/>
  <Word word="" roman="extinguish" star="1"/>
  <Word word="" roman="buffalo" star="1"/>
  <Word word="" roman="ambitious" star="1"/>
  <Word word="" roman="esteem" star="1"/>
  <Word word="" roman="cellar" star="1"/>
  <Word word="" roman="chill" star="1"/>
  <Word word="" roman="confine" star="1"/>
  <Word word="" roman="determination" star="1"/>
  <Word word="" roman="constrain" star="1"/>
  <Word word="" roman="beer" star="1"/>
  <Word word="" roman="expand" star="1"/>
  <Word word="" roman="basement" star="1"/>
  <Word word="" roman="dishonor" star="1"/>
  <Word word="" roman="diagram" star="1"/>
  <Word word="" roman="essential" star="1"/>
  <Word word="" roman="apostrophe" star="1"/>
  <Word word="" roman="emphasize" star="1"/>
  <Word word="" roman="arrange" star="1"/>
  <Word word="" roman="accustom" star="1"/>
  <Word word="" roman="countenance" star="1"/>
  <Word word="" roman="discount" star="1"/>
  <Word word="" roman="fountain" star="1"/>
  <Word word="" roman="concerning" star="1"/>
  <Word word="" roman="chest" star="1"/>
  <Word word="" roman="advise" star="1"/>
  <Word word="" roman="automation" star="1"/>
  <Word word="" roman="capacity" star="1"/>
  <Word word="" roman="bribe" star="1"/>
  <Word word="" roman="earthquake" star="1"/>
  <Word word="" roman="drip" star="1"/>
  <Word word="" roman="decision" star="1"/>
  <Word word="" roman="considerable" star="1"/>
  <Word word="" roman="element" star="1"/>
  <Word word="" roman="dependent" star="1"/>
  <Word word="" roman="catalog" star="1"/>
  <Word word="" roman="dull" star="1"/>
  <Word word="" roman="commence" star="1"/>
  <Word word="" roman="flee" star="1"/>
  <Word word="" roman="epidemic" star="1"/>
  <Word word="" roman="agent" star="1"/>
  <Word word="" roman="brim" star="1"/>
  <Word word="" roman="aid" star="1"/>
  <Word word="" roman="derive" star="1"/>
  <Word word="" roman="buyer" star="1"/>
  <Word word="" roman="Chicago" star="1"/>
  <Word word="" roman="curious" star="1"/>
  <Word word="" roman="author" star="1"/>
  <Word word="" roman="afflict" star="1"/>
  <Word word="" roman="deceive" star="1"/>
  <Word word="" roman="collapse" star="1"/>
  <Word word="" roman="fatigue" star="1"/>
  <Word word="" roman="drain" star="1"/>
  <Word word="" roman="biology" star="1"/>
  <Word word="" roman="B.C." star="1"/>
  <Word word="" roman="chemical" star="1"/>
  <Word word="" roman="apparent" star="1"/>
  <Word word="" roman="fearless" star="1"/>
  <Word word="" roman="agreeable" star="1"/>
  <Word word="" roman="frozen" star="1"/>
  <Word word="" roman="capture" star="1"/>
  <Word word="" roman="expense" star="1"/>
  <Word word="" roman="anthem" star="1"/>
  <Word word="" roman="chime" star="1"/>
  <Word word="" roman="bundle" star="1"/>
  <Word word="" roman="censor" star="1"/>
  <Word word="" roman="congratulation" star="1"/>
  <Word word="" roman="float" star="1"/>
  <Word word="" roman="emperor" star="1"/>
  <Word word="" roman="counter" star="1"/>
  <Word word="" roman="defy" star="1"/>
  <Word word="" roman="cf." star="1"/>
  <Word word="" roman="accessory" star="1"/>
  <Word word="" roman="create" star="1"/>
  <Word word="" roman="contribute" star="1"/>
  <Word word="" roman="application" star="1"/>
  <Word word="" roman="comprehend" star="1"/>
  <Word word="" roman="calamity" star="1"/>
  <Word word="" roman="cease" star="1"/>
  <Word word="" roman="dealing" star="1"/>
  <Word word="" roman="endure" star="1"/>
  <Word word="" roman="bacteria" star="1"/>
  <Word word="" roman="driver" star="1"/>
  <Word word="" roman="characteristic" star="1"/>
  <Word word="" roman="decided" star="1"/>
  <Word word="" roman="fought" star="1"/>
  <Word word="" roman="aside" star="1"/>
  <Word word="" roman="anatomy" star="1"/>
  <Word word="" roman="chimpanzee" star="1"/>
  <Word word="" roman="background" star="1"/>
  <Word word="" roman="consent" star="1"/>
  <Word word="" roman="convince" star="1"/>
  <Word word="" roman="disclose" star="1"/>
  <Word word="" roman="chip" star="1"/>
  <Word word="" roman="convenience" star="1"/>
  <Word word="" roman="abbey" star="1"/>
  <Word word="" roman="bitter" star="1"/>
  <Word word="" roman="bless" star="1"/>
  <Word word="" roman="abnormal" star="1"/>
  <Word word="" roman="abbreviate" star="1"/>
  <Word word="" roman="crept" star="1"/>
  <Word word="" roman="bound" star="1"/>
  <Word word="" roman="explosive" star="1"/>
  <Word word="" roman="clap" star="1"/>
  <Word word="" roman="aspiration" star="1"/>
  <Word word="" roman="acquaintance" star="1"/>
  <Word word="" roman="comedy" star="1"/>
  <Word word="" roman="daytime" star="1"/>
  <Word word="" roman="cupboard" star="1"/>
  <Word word="" roman="barber" star="1"/>
  <Word word="" roman="compensate" star="1"/>
  <Word word="" roman="critic" star="1"/>
  <Word word="" roman="enhance" star="1"/>
  <Word word="" roman="depart" star="1"/>
  <Word word="" roman="farewell" star="1"/>
  <Word word="" roman="conflict" star="1"/>
  <Word word="" roman="foul" star="1"/>
  <Word word="" roman="delightful" star="1"/>
  <Word word="" roman="establish" star="1"/>
  <Word word="" roman="erase" star="1"/>
  <Word word="" roman="billion" star="1"/>
  <Word word="" roman="concentrate" star="1"/>
  <Word word="" roman="fertile" star="1"/>
  <Word word="" roman="destiny" star="1"/>
  <Word word="" roman="entreat" star="1"/>
  <Word word="" roman="culture" star="1"/>
  <Word word="" roman="arch" star="1"/>
  <Word word="" roman="alter" star="1"/>
  <Word word="" roman="excellent" star="1"/>
  <Word word="" roman="adopt" star="1"/>
  <Word word="" roman="explanation" star="1"/>
  <Word word="" roman="automobile" star="1"/>
  <Word word="" roman="enable" star="1"/>
  <Word word="" roman="formula" star="1"/>
  <Word word="" roman="cosmos" star="1"/>
  <Word word="" roman="architect" star="1"/>
  <Word word="" roman="benefit" star="1"/>
  <Word word="" roman="downstairs" star="1"/>
  <Word word="" roman="atomic" star="1"/>
  <Word word="" roman="extinct" star="1"/>
  <Word word="" roman="conscious" star="1"/>
  <Word word="" roman="cruel" star="1"/>
  <Word word="" roman="combat" star="1"/>
  <Word word="" roman="criticize" star="1"/>
  <Word word="" roman="discuss" star="1"/>
  <Word word="" roman="breeze" star="1"/>
  <Word word="" roman="explosion" star="1"/>
  <Word word="" roman="fare" star="1"/>
  <Word word="" roman="apron" star="1"/>
  <Word word="" roman="aerial" star="1"/>
  <Word word="" roman="copyright" star="1"/>
  <Word word="" roman="bomb" star="1"/>
  <Word word="" roman="flutter" star="1"/>
  <Word word="" roman="echo" star="1"/>
  <Word word="" roman="caravan" star="1"/>
  <Word word="" roman="devotion" star="1"/>
  <Word word="" roman="cheer" star="1"/>
  <Word word="" roman="embassy" star="1"/>
  <Word word="" roman="anger" star="1"/>
  <Word word="" roman="forbid" star="1"/>
  <Word word="" roman="formal" star="1"/>
  <Word word="" roman="endeavor" star="1"/>
  <Word word="" roman="elect" star="1"/>
  <Word word="" roman="dwarf" star="1"/>
  <Word word="" roman="chimney" star="1"/>
  <Word word="" roman="dirty" star="1"/>
  <Word word="" roman="arc" star="1"/>
  <Word word="" roman="delivery" star="1"/>
  <Word word="" roman="crawl" star="1"/>
  <Word word="" roman="excel" star="1"/>
  <Word word="" roman="communist" star="1"/>
  <Word word="" roman="dread" star="1"/>
  <Word word="" roman="fearful" star="1"/>
  <Word word="" roman="curry" star="1"/>
  <Word word="" roman="elementary" star="1"/>
  <Word word="" roman="froze" star="1"/>
  <Word word="" roman="exist" star="1"/>
  <Word word="" roman="discharge" star="1"/>
  <Word word="" roman="assault" star="1"/>
  <Word word="" roman="awoken" star="1"/>
  <Word word="" roman="exert" star="1"/>
  <Word word="" roman="envious" star="1"/>
  <Word word="" roman="enormous" star="1"/>
  <Word word="" roman="consumer" star="1"/>
  <Word word="" roman="awe" star="1"/>
  <Word word="" roman="clasp" star="1"/>
  <Word word="" roman="exterior" star="1"/>
  <Word word="" roman="bloody" star="1"/>
  <Word word="" roman="decade" star="1"/>
  <Word word="" roman="expose" star="1"/>
  <Word word="" roman="dust" star="1"/>
  <Word word="" roman="burglar" star="1"/>
  <Word word="" roman="distribute" star="1"/>
  <Word word="" roman="expire" star="1"/>
  <Word word="" roman="cart" star="1"/>
  <Word word="" roman="dialect" star="1"/>
  <Word word="" roman="blaze" star="1"/>
  <Word word="" roman="describe" star="1"/>
  <Word word="" roman="artist" star="1"/>
  <Word word="" roman="adapt" star="1"/>
  <Word word="" roman="everyday" star="1"/>
  <Word word="" roman="cubic" star="1"/>
  <Word word="" roman="delight" star="1"/>
  <Word word="" roman="circus" star="1"/>
  <Word word="" roman="demonstrate" star="1"/>
  <Word word="" roman="counsel" star="1"/>
  <Word word="" roman="eternal" star="1"/>
  <Word word="" roman="chairman" star="1"/>
  <Word word="" roman="allot" star="1"/>
  <Word word="" roman="encyclopedia" star="1"/>
  <Word word="" roman="babe" star="1"/>
  <Word word="" roman="convenient" star="1"/>
  <Word word="" roman="dim" star="1"/>
  <Word word="" roman="cash" star="1"/>
  <Word word="" roman="Egyptian" star="1"/>
  <Word word="" roman="frown" star="1"/>
  <Word word="" roman="dispatch" star="1"/>
  <Word word="" roman="associate" star="1"/>
  <Word word="" roman="craft" star="1"/>
  <Word word="" roman="erotic" star="1"/>
  <Word word="" roman="cable" star="1"/>
  <Word word="" roman="dive" star="1"/>
  <Word word="" roman="doctrine" star="1"/>
  <Word word="" roman="construct" star="1"/>
  <Word word="" roman="avenue" star="1"/>
  <Word word="" roman="abroad" star="1"/>
  <Word word="" roman="excitement" star="1"/>
  <Word word="" roman="editorial" star="1"/>
  <Word word="" roman="Eve" star="1"/>
  <Word word="" roman="admire" star="1"/>
  <Word word="" roman="anyway" star="1"/>
  <Word word="" roman="bulb" star="1"/>
  <Word word="" roman="citizen" star="1"/>
  <Word word="" roman="desirable" star="1"/>
  <Word word="" roman="emotion" star="1"/>
  <Word word="" roman="combination" star="1"/>
  <Word word="" roman="bubble" star="1"/>
  <Word word="" roman="drama" star="1"/>
  <Word word="" roman="coward" star="1"/>
  <Word word="" roman="domestic" star="1"/>
  <Word word="" roman="embarrass" star="1"/>
  <Word word="" roman="botany" star="1"/>
  <Word word="" roman="daffodil" star="1"/>
  <Word word="" roman="banquet" star="1"/>
  <Word word="" roman="cemetery" star="1"/>
  <Word word="" roman="faint" star="1"/>
  <Word word="" roman="basic" star="1"/>
  <Word word="" roman="external" star="1"/>
  <Word word="" roman="breed" star="1"/>
  <Word word="" roman="attach" star="1"/>
  <Word word="" roman="export" star="1"/>
  <Word word="" roman="conjunction" star="1"/>
  <Word word="" roman="brethren" star="1"/>
  <Word word="" roman="bushel" star="1"/>
  <Word word="" roman="dart" star="1"/>
  <Word word="" roman="flock" star="1"/>
  <Word word="" roman="actress" star="1"/>
  <Word word="" roman="convert" star="1"/>
  <Word word="" roman="backbone" star="1"/>
  <Word word="" roman="essence" star="1"/>
  <Word word="" roman="association" star="1"/>
  <Word word="" roman="coach" star="1"/>
  <Word word="" roman="ascend" star="1"/>
  <Word word="" roman="comply" star="1"/>
  <Word word="" roman="brutal" star="1"/>
  <Word word="" roman="commonplace" star="1"/>
  <Word word="" roman="colonial" star="1"/>
  <Word word="" roman="amazement" star="1"/>
  <Word word="" roman="bathroom" star="1"/>
  <Word word="" roman="freight" star="1"/>
  <Word word="" roman="beaten" star="1"/>
  <Word word="" roman="afford" star="1"/>
  <Word word="" roman="fan" star="1"/>
  <Word word="" roman="anecdote" star="1"/>
  <Word word="" roman="approach" star="1"/>
  <Word word="" roman="clause" star="1"/>
  <Word word="" roman="fairy" star="1"/>
  <Word word="" roman="drill" star="1"/>
  <Word word="" roman="device" star="1"/>
  <Word word="" roman="chose" star="1"/>
  <Word word="" roman="artificial" star="1"/>
  <Word word="" roman="extra" star="1"/>
  <Word word="" roman="criticism" star="1"/>
  <Word word="" roman="awaken" star="1"/>
  <Word word="" roman="chick" star="1"/>
  <Word word="" roman="fresh" star="1"/>
  <Word word="" roman="arouse" star="1"/>
  <Word word="" roman="flatter" star="1"/>
  <Word word="" roman="brief" star="1"/>
  <Word word="" roman="bachelor" star="1"/>
  <Word word="" roman="blunt" star="1"/>
  <Word word="" roman="compromise" star="1"/>
  <Word word="" roman="corrupt" star="1"/>
  <Word word="" roman="actual" star="1"/>
  <Word word="" roman="acknowledge" star="1"/>
  <Word word="" roman="canoe" star="1"/>
  <Word word="" roman="brighten" star="1"/>
  <Word word="" roman="current" star="1"/>
  <Word word="" roman="deepen" star="1"/>
  <Word word="" roman="detail" star="1"/>
  <Word word="" roman="buoy" star="1"/>
  <Word word="" roman="bridle" star="1"/>
  <Word word="" roman="facility" star="1"/>
  <Word word="" roman="commerce" star="1"/>
  <Word word="" roman="fulfill" star="1"/>
  <Word word="" roman="depression" star="1"/>
  <Word word="" roman="exciting" star="1"/>
  <Word word="" roman="chew" star="1"/>
  <Word word="" roman="consequence" star="1"/>
  <Word word="" roman="discriminate" star="1"/>
  <Word word="" roman="exhibit" star="1"/>
  <Word word="" roman="carriage" star="1"/>
  <Word word="" roman="chin" star="1"/>
  <Word word="" roman="bruise" star="1"/>
  <Word word="" roman="flood" star="1"/>
  <Word word="" roman="diameter" star="1"/>
  <Word word="" roman="cheerful" star="1"/>
  <Word word="" roman="executive" star="1"/>
  <Word word="" roman="deserve" star="1"/>
  <Word word="" roman="bishop" star="1"/>
  <Word word="" roman="auditorium" star="1"/>
  <Word word="" roman="bean" star="1"/>
  <Word word="" roman="fetch" star="1"/>
  <Word word="" roman="fighting" star="1"/>
  <Word word="" roman="almond" star="1"/>
  <Word word="" roman="argument" star="1"/>
  <Word word="" roman="accelerate" star="1"/>
  <Word word="" roman="closed" star="1"/>
  <Word word="" roman="daydream" star="1"/>
  <Word word="" roman="estimate" star="1"/>
  <Word word="" roman="enrich" star="1"/>
  <Word word="" roman="coffin" star="1"/>
  <Word word="" roman="delay" star="1"/>
  <Word word="" roman="despite" star="1"/>
  <Word word="" roman="chemistry" star="1"/>
  <Word word="" roman="earn" star="1"/>
  <Word word="" roman="crystal" star="1"/>
  <Word word="" roman="bull" star="1"/>
  <Word word="" roman="appreciate" star="1"/>
  <Word word="" roman="despair" star="1"/>
  <Word word="" roman="frequent" star="1"/>
  <Word word="" roman="compose" star="1"/>
  <Word word="" roman="aggressive" star="1"/>
  <Word word="" roman="delicate" star="1"/>
  <Word word="" roman="attempt" star="1"/>
  <Word word="" roman="dismay" star="1"/>
  <Word word="" roman="extraordinary" star="1"/>
  <Word word="" roman="European" star="1"/>
  <Word word="" roman="certificate" star="1"/>
  <Word word="" roman="cartoon" star="1"/>
  <Word word="" roman="amuse" star="1"/>
  <Word word="" roman="clung" star="1"/>
  <Word word="" roman="campaign" star="1"/>
  <Word word="" roman="careless" star="1"/>
  <Word word="" roman="bronze" star="1"/>
  <Word word="" roman="embrace" star="1"/>
  <Word word="" roman="aquarium" star="1"/>
  <Word word="" roman="award" star="1"/>
  <Word word="" roman="caramel" star="1"/>
  <Word word="" roman="analysis" star="1"/>
  <Word word="" roman="balloon" star="1"/>
  <Word word="" roman="angel" star="1"/>
  <Word word="" roman="doubtless" star="1"/>
  <Word word="" roman="charter" star="1"/>
  <Word word="" roman="fortress" star="1"/>
  <Word word="" roman="dessert" star="1"/>
  <Word word="" roman="fire engine" star="1"/>
  <Word word="" roman="blot" star="1"/>
  <Word word="" roman="diplomatic" star="1"/>
  <Word word="" roman="distress" star="1"/>
  <Word word="" roman="dying" star="1"/>
  <Word word="" roman="approval" star="1"/>
  <Word word="" roman="evident" star="1"/>
  <Word word="" roman="ax" star="1"/>
  <Word word="" roman="athletic" star="1"/>
  <Word word="" roman="exquisite" star="1"/>
  <Word word="" roman="famine" star="1"/>
  <Word word="" roman="bliss" star="1"/>
  <Word word="" roman="contemplate" star="1"/>
  <Word word="" roman="arrow" star="1"/>
  <Word word="" roman="fade" star="1"/>
  <Word word="" roman="experiment" star="1"/>
  <Word word="" roman="chop" star="1"/>
  <Word word="" roman="defensive" star="1"/>
  <Word word="" roman="cushion" star="1"/>
  <Word word="" roman="bush" star="1"/>
  <Word word="" roman="contrary" star="1"/>
  <Word word="" roman="aspect" star="1"/>
  <Word word="" roman="discern" star="1"/>
  <Word word="" roman="fist" star="1"/>
  <Word word="" roman="ancient" star="1"/>
  <Word word="" roman="distinct" star="1"/>
  <Word word="" roman="Antarctic" star="1"/>
  <Word word="" roman="energy" star="1"/>
  <Word word="" roman="bent" star="1"/>
  <Word word="" roman="administration" star="1"/>
  <Word word="" roman="exclamation" star="1"/>
  <Word word="" roman="descend" star="1"/>
  <Word word="" roman="employment" star="1"/>
  <Word word="" roman="fund" star="1"/>
  <Word word="" roman="accurate" star="1"/>
  <Word word="" roman="businessman" star="1"/>
  <Word word="" roman="fluent" star="1"/>
  <Word word="" roman="forum" star="1"/>
  <Word word="" roman="beginning" star="1"/>
  <Word word="" roman="disturb" star="1"/>
  <Word word="" roman="almighty" star="1"/>
  <Word word="" roman="due" star="1"/>
  <Word word="" roman="corps" star="1"/>
  <Word word="" roman="fairly" star="1"/>
  <Word word="" roman="adverb" star="1"/>
  <Word word="" roman="evil" star="1"/>
  <Word word="" roman="analyze" star="1"/>
  <Word word="" roman="colony" star="1"/>
  <Word word="" roman="den" star="1"/>
  <Word word="" roman="cock" star="1"/>
  <Word word="" roman="daisy" star="1"/>
  <Word word="" roman="Arabian" star="1"/>
  <Word word="" roman="comparison" star="1"/>
  <Word word="" roman="forbidden" star="1"/>
  <Word word="" roman="curl" star="1"/>
  <Word word="" roman="endow" star="1"/>
  <Word word="" roman="abstract" star="1"/>
  <Word word="" roman="brand" star="1"/>
  <Word word="" roman="cricket" star="1"/>
  <Word word="" roman="fierce" star="1"/>
  <Word word="" roman="cigarette" star="1"/>
  <Word word="" roman="ankle" star="1"/>
  <Word word="" roman="eloquent" star="1"/>
  <Word word="" roman="fake" star="1"/>
  <Word word="" roman="crash" star="1"/>
  <Word word="" roman="ancestor" star="1"/>
  <Word word="" roman="baggage" star="1"/>
  <Word word="" roman="aurora" star="1"/>
  <Word word="" roman="detective" star="1"/>
  <Word word="" roman="companion" star="1"/>
  <Word word="" roman="extract" star="1"/>
  <Word word="" roman="cucumber" star="1"/>
  <Word word="" roman="darken" star="1"/>
  <Word word="" roman="beggar" star="1"/>
  <Word word="" roman="anyhow" star="1"/>
  <Word word="" roman="choke" star="1"/>
  <Word word="" roman="cent" star="1"/>
  <Word word="" roman="captive" star="1"/>
  <Word word="" roman="bureau" star="1"/>
  <Word word="" roman="burial" star="1"/>
  <Word word="" roman="bud" star="1"/>
  <Word word="" roman="classical" star="1"/>
  <Word word="" roman="fireman" star="1"/>
  <Word word="" roman="cicada" star="1"/>
  <Word word="" roman="eliminate" star="1"/>
  <Word word="" roman="broker" star="1"/>
  <Word word="" roman="furthermore" star="1"/>
  <Word word="" roman="column" star="1"/>
  <Word word="" roman="factory" star="1"/>
  <Word word="" roman="endurance" star="1"/>
  <Word word="" roman="antique" star="1"/>
  <Word word="" roman="counselor" star="1"/>
  <Word word="" roman="false" star="1"/>
  <Word word="" roman="cement" star="1"/>
  <Word word="" roman="declaration" star="1"/>
  <Word word="" roman="epic" star="1"/>
  <Word word="" roman="accordion" star="1"/>
  <Word word="" roman="educate" star="1"/>
  <Word word="" roman="anniversary" star="1"/>
  <Word word="" roman="console" star="1"/>
  <Word word="" roman="courteous" star="1"/>
  <Word word="" roman="exceed" star="1"/>
  <Word word="" roman="conceal" star="1"/>
  <Word word="" roman="extension" star="1"/>
  <Word word="" roman="bustle" star="1"/>
  <Word word="" roman="ache" star="1"/>
  <Word word="" roman="demon" star="1"/>
  <Word word="" roman="focus" star="1"/>
  <Word word="" roman="attendant" star="1"/>
  <Word word="" roman="bonus" star="1"/>
  <Word word="" roman="corridor" star="1"/>
  <Word word="" roman="drug" star="1"/>
  <Word word="" roman="conductor" star="1"/>
  <Word word="" roman="bamboo" star="1"/>
  <Word word="" roman="equal" star="1"/>
  <Word word="" roman="dad" star="1"/>
  <Word word="" roman="enterprise" star="1"/>
  <Word word="" roman="ah" star="1"/>
  <Word word="" roman="antonym" star="1"/>
  <Word word="" roman="exhibition" star="1"/>
  <Word word="" roman="broadcast" star="1"/>
  <Word word="" roman="deceit" star="1"/>
  <Word word="" roman="eminent" star="1"/>
  <Word word="" roman="burden" star="1"/>
  <Word word="" roman="chaos" star="1"/>
  <Word word="" roman="abide" star="1"/>
  <Word word="" roman="actor" star="1"/>
  <Word word="" roman="coming" star="1"/>
  <Word word="" roman="digest" star="1"/>
  <Word word="" roman="batter" star="1"/>
  <Word word="" roman="elbow" star="1"/>
  <Word word="" roman="cabin" star="1"/>
  <Word word="" roman="ascent" star="1"/>
  <Word word="" roman="beheld" star="1"/>
  <Word word="" roman="common sense" star="1"/>
  <Word word="" roman="charming" star="1"/>
  <Word word="" roman="decorate" star="1"/>
  <Word word="" roman="divorce" star="1"/>
  <Word word="" roman="altogether" star="1"/>
  <Word word="" roman="freedom" star="1"/>
  <Word word="" roman="dawn" star="1"/>
  <Word word="" roman="bleed" star="1"/>
  <Word word="" roman="cattle" star="1"/>
  <Word word="" roman="clothe" star="1"/>
  <Word word="" roman="fix" star="1"/>
  <Word word="" roman="diving" star="1"/>
  <Word word="" roman="drawn" star="1"/>
  <Word word="" roman="adult" star="1"/>
  <Word word="" roman="elaborate" star="1"/>
  <Word word="" roman="bough" star="1"/>
  <Word word="" roman="elephant" star="1"/>
  <Word word="" roman="concept" star="1"/>
  <Word word="" roman="faithful" star="1"/>
  <Word word="" roman="click" star="1"/>
  <Word word="" roman="clamp" star="1"/>
  <Word word="" roman="err" star="1"/>
  <Word word="" roman="beaver" star="1"/>
  <Word word="" roman="alkali" star="1"/>
  <Word word="" roman="forbear" star="1"/>
</Words>