<?xml version="1.0"?>
<Words xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Word word="" roman="insufficient" star="1"/>
  <Word word="" roman="pressure" star="1"/>
  <Word word="" roman="plaster" star="1"/>
  <Word word="" roman="parallel" star="1"/>
  <Word word="" roman="prejudice" star="1"/>
  <Word word="" roman="management" star="1"/>
  <Word word="" roman="outstanding" star="1"/>
  <Word word="" roman="hollow" star="1"/>
  <Word word="" roman="muscular" star="1"/>
  <Word word="" roman="meanwhile" star="1"/>
  <Word word="" roman="orthodox" star="1"/>
  <Word word="" roman="mermaid" star="1"/>
  <Word word="" roman="influence" star="1"/>
  <Word word="" roman="portion" star="1"/>
  <Word word="" roman="moderate" star="1"/>
  <Word word="" roman="graze" star="1"/>
  <Word word="" roman="mill" star="1"/>
  <Word word="" roman="grocer" star="1"/>
  <Word word="" roman="lavatory" star="1"/>
  <Word word="" roman="omen" star="1"/>
  <Word word="" roman="huge" star="1"/>
  <Word word="" roman="phase" star="1"/>
  <Word word="" roman="plea" star="1"/>
  <Word word="" roman="leopard" star="1"/>
  <Word word="" roman="lobster" star="1"/>
  <Word word="" roman="instance" star="1"/>
  <Word word="" roman="kindness" star="1"/>
  <Word word="" roman="peculiar" star="1"/>
  <Word word="" roman="passionate" star="1"/>
  <Word word="" roman="mast" star="1"/>
  <Word word="" roman="prairie" star="1"/>
  <Word word="" roman="Olympic" star="1"/>
  <Word word="" roman="luminous" star="1"/>
  <Word word="" roman="medieval" star="1"/>
  <Word word="" roman="misfortune" star="1"/>
  <Word word="" roman="load" star="1"/>
  <Word word="" roman="household" star="1"/>
  <Word word="" roman="monitor" star="1"/>
  <Word word="" roman="marriage" star="1"/>
  <Word word="" roman="mistook" star="1"/>
  <Word word="" roman="lizard" star="1"/>
  <Word word="" roman="greater" star="1"/>
  <Word word="" roman="indifferent" star="1"/>
  <Word word="" roman="plum" star="1"/>
  <Word word="" roman="luxurious" star="1"/>
  <Word word="" roman="obstacle" star="1"/>
  <Word word="" roman="mental" star="1"/>
  <Word word="" roman="impress" star="1"/>
  <Word word="" roman="hostile" star="1"/>
  <Word word="" roman="graph" star="1"/>
  <Word word="" roman="odor" star="1"/>
  <Word word="" roman="New World" star="1"/>
  <Word word="" roman="orchard" star="1"/>
  <Word word="" roman="pavilion" star="1"/>
  <Word word="" roman="lance" star="1"/>
  <Word word="" roman="principal" star="1"/>
  <Word word="" roman="hysterical" star="1"/>
  <Word word="" roman="metaphor" star="1"/>
  <Word word="" roman="harden" star="1"/>
  <Word word="" roman="pride" star="1"/>
  <Word word="" roman="patience" star="1"/>
  <Word word="" roman="independence" star="1"/>
  <Word word="" roman="likely" star="1"/>
  <Word word="" roman="nevertheless" star="1"/>
  <Word word="" roman="implement" star="1"/>
  <Word word="" roman="producer" star="1"/>
  <Word word="" roman="gown" star="1"/>
  <Word word="" roman="maid" star="1"/>
  <Word word="" roman="ignore" star="1"/>
  <Word word="" roman="illustrate" star="1"/>
  <Word word="" roman="imperial" star="1"/>
  <Word word="" roman="pianist" star="1"/>
  <Word word="" roman="holy" star="1"/>
  <Word word="" roman="gale" star="1"/>
  <Word word="" roman="prediction" star="1"/>
  <Word word="" roman="impose" star="1"/>
  <Word word="" roman="peel" star="1"/>
  <Word word="" roman="omega" star="1"/>
  <Word word="" roman="limp" star="1"/>
  <Word word="" roman="hook" star="1"/>
  <Word word="" roman="guarantee" star="1"/>
  <Word word="" roman="haunt" star="1"/>
  <Word word="" roman="Latin" star="1"/>
  <Word word="" roman="impudent" star="1"/>
  <Word word="" roman="muscle" star="1"/>
  <Word word="" roman="pretend" star="1"/>
  <Word word="" roman="purity" star="1"/>
  <Word word="" roman="Hollywood" star="1"/>
  <Word word="" roman="melancholy" star="1"/>
  <Word word="" roman="pathetic" star="1"/>
  <Word word="" roman="memorize" star="1"/>
  <Word word="" roman="navigate" star="1"/>
  <Word word="" roman="goose" star="1"/>
  <Word word="" roman="Korea" star="1"/>
  <Word word="" roman="keyboard" star="1"/>
  <Word word="" roman="married" star="1"/>
  <Word word="" roman="pineapple" star="1"/>
  <Word word="" roman="pickle" star="1"/>
  <Word word="" roman="indirect" star="1"/>
  <Word word="" roman="possibility" star="1"/>
  <Word word="" roman="overnight" star="1"/>
  <Word word="" roman="panic" star="1"/>
  <Word word="" roman="prohibit" star="1"/>
  <Word word="" roman="luggage" star="1"/>
  <Word word="" roman="nylon" star="1"/>
  <Word word="" roman="pond" star="1"/>
  <Word word="" roman="New Zealand" star="1"/>
  <Word word="" roman="probable" star="1"/>
  <Word word="" roman="jellyfish" star="1"/>
  <Word word="" roman="jealous" star="1"/>
  <Word word="" roman="ministry" star="1"/>
  <Word word="" roman="medicine" star="1"/>
  <Word word="" roman="marble" star="1"/>
  <Word word="" roman="Jesus" star="1"/>
  <Word word="" roman="Portugal" star="1"/>
  <Word word="" roman="masterpiece" star="1"/>
  <Word word="" roman="inner" star="1"/>
  <Word word="" roman="luster" star="1"/>
  <Word word="" roman="option" star="1"/>
  <Word word="" roman="policy" star="1"/>
  <Word word="" roman="precious" star="1"/>
  <Word word="" roman="pence" star="1"/>
  <Word word="" roman="gasoline" star="1"/>
  <Word word="" roman="mixture" star="1"/>
  <Word word="" roman="misuse" star="1"/>
  <Word word="" roman="maiden" star="1"/>
  <Word word="" roman="humid" star="1"/>
  <Word word="" roman="microphone" star="1"/>
  <Word word="" roman="incorrect" star="1"/>
  <Word word="" roman="hopeless" star="1"/>
  <Word word="" roman="liver" star="1"/>
  <Word word="" roman="incapable" star="1"/>
  <Word word="" roman="panorama" star="1"/>
  <Word word="" roman="kindle" star="1"/>
  <Word word="" roman="growth" star="1"/>
  <Word word="" roman="paradise" star="1"/>
  <Word word="" roman="priest" star="1"/>
  <Word word="" roman="instruct" star="1"/>
  <Word word="" roman="initial" star="1"/>
  <Word word="" roman="outbreak" star="1"/>
  <Word word="" roman="northwest" star="1"/>
  <Word word="" roman="preparation" star="1"/>
  <Word word="" roman="instead" star="1"/>
  <Word word="" roman="jest" star="1"/>
  <Word word="" roman="propaganda" star="1"/>
  <Word word="" roman="intelligence" star="1"/>
  <Word word="" roman="majestic" star="1"/>
  <Word word="" roman="penetrate" star="1"/>
  <Word word="" roman="landscape" star="1"/>
  <Word word="" roman="plantation" star="1"/>
  <Word word="" roman="medley" star="1"/>
  <Word word="" roman="guilt" star="1"/>
  <Word word="" roman="grand" star="1"/>
  <Word word="" roman="mighty" star="1"/>
  <Word word="" roman="pastime" star="1"/>
  <Word word="" roman="pudding" star="1"/>
  <Word word="" roman="pigeon" star="1"/>
  <Word word="" roman="oriental" star="1"/>
  <Word word="" roman="heroine" star="1"/>
  <Word word="" roman="portrait" star="1"/>
  <Word word="" roman="property" star="1"/>
  <Word word="" roman="gradual" star="1"/>
  <Word word="" roman="inland" star="1"/>
  <Word word="" roman="Mediterranean" star="1"/>
  <Word word="" roman="jam" star="1"/>
  <Word word="" roman="orchestra" star="1"/>
  <Word word="" roman="highly" star="1"/>
  <Word word="" roman="pirate" star="1"/>
  <Word word="" roman="malaria" star="1"/>
  <Word word="" roman="mosquito" star="1"/>
  <Word word="" roman="mercy" star="1"/>
  <Word word="" roman="owing" star="1"/>
  <Word word="" roman="native" star="1"/>
  <Word word="" roman="momentary" star="1"/>
  <Word word="" roman="moonlight" star="1"/>
  <Word word="" roman="perception" star="1"/>
  <Word word="" roman="identify" star="1"/>
  <Word word="" roman="optimism" star="1"/>
  <Word word="" roman="gram" star="1"/>
  <Word word="" roman="lives" star="1"/>
  <Word word="" roman="impolite" star="1"/>
  <Word word="" roman="precision" star="1"/>
  <Word word="" roman="grammar" star="1"/>
  <Word word="" roman="objection" star="1"/>
  <Word word="" roman="plus" star="1"/>
  <Word word="" roman="inscription" star="1"/>
  <Word word="" roman="preservation" star="1"/>
  <Word word="" roman="mesh" star="1"/>
  <Word word="" roman="lunatic" star="1"/>
  <Word word="" roman="interior" star="1"/>
  <Word word="" roman="parade" star="1"/>
  <Word word="" roman="plastic" star="1"/>
  <Word word="" roman="journal" star="1"/>
  <Word word="" roman="passive" star="1"/>
  <Word word="" roman="liable" star="1"/>
  <Word word="" roman="peg" star="1"/>
  <Word word="" roman="miss" star="1"/>
  <Word word="" roman="observer" star="1"/>
  <Word word="" roman="proceed" star="1"/>
  <Word word="" roman="mankind" star="1"/>
  <Word word="" roman="practical" star="1"/>
  <Word word="" roman="negligence" star="1"/>
  <Word word="" roman="mixed" star="1"/>
  <Word word="" roman="loyal" star="1"/>
  <Word word="" roman="lament" star="1"/>
  <Word word="" roman="mansion" star="1"/>
  <Word word="" roman="middle-aged" star="1"/>
  <Word word="" roman="plentiful" star="1"/>
  <Word word="" roman="No." star="1"/>
  <Word word="" roman="infinitive" star="1"/>
  <Word word="" roman="indulge" star="1"/>
  <Word word="" roman="mechanical" star="1"/>
  <Word word="" roman="ha" star="1"/>
  <Word word="" roman="Greek" star="1"/>
  <Word word="" roman="indicate" star="1"/>
  <Word word="" roman="percent" star="1"/>
  <Word word="" roman="harmful" star="1"/>
  <Word word="" roman="naught" star="1"/>
  <Word word="" roman="mammoth" star="1"/>
  <Word word="" roman="plane" star="1"/>
  <Word word="" roman="locate" star="1"/>
  <Word word="" roman="personal" star="1"/>
  <Word word="" roman="hemisphere" star="1"/>
  <Word word="" roman="miracle" star="1"/>
  <Word word="" roman="highway" star="1"/>
  <Word word="" roman="moving" star="1"/>
  <Word word="" roman="interested" star="1"/>
  <Word word="" roman="nervous" star="1"/>
  <Word word="" roman="going" star="1"/>
  <Word word="" roman="garland" star="1"/>
  <Word word="" roman="instrument" star="1"/>
  <Word word="" roman="investigate" star="1"/>
  <Word word="" roman="hobby" star="1"/>
  <Word word="" roman="odd" star="1"/>
  <Word word="" roman="insurance" star="1"/>
  <Word word="" roman="obvious" star="1"/>
  <Word word="" roman="imperfect" star="1"/>
  <Word word="" roman="offense" star="1"/>
  <Word word="" roman="murderer" star="1"/>
  <Word word="" roman="prevent" star="1"/>
  <Word word="" roman="procedure" star="1"/>
  <Word word="" roman="imitate" star="1"/>
  <Word word="" roman="mob" star="1"/>
  <Word word="" roman="mat" star="1"/>
  <Word word="" roman="humility" star="1"/>
  <Word word="" roman="progress" star="1"/>
  <Word word="" roman="pyramid" star="1"/>
  <Word word="" roman="opportunity" star="1"/>
  <Word word="" roman="later" star="1"/>
  <Word word="" roman="pursuit" star="1"/>
  <Word word="" roman="moral" star="1"/>
  <Word word="" roman="mute" star="1"/>
  <Word word="" roman="presence" star="1"/>
  <Word word="" roman="obscure" star="1"/>
  <Word word="" roman="inflame" star="1"/>
  <Word word="" roman="genesis" star="1"/>
  <Word word="" roman="plural" star="1"/>
  <Word word="" roman="parrot" star="1"/>
  <Word word="" roman="photo" star="1"/>
  <Word word="" roman="meantime" star="1"/>
  <Word word="" roman="gymnastics" star="1"/>
  <Word word="" roman="pronunciation" star="1"/>
  <Word word="" roman="lawyer" star="1"/>
  <Word word="" roman="genius" star="1"/>
  <Word word="" roman="jail" star="1"/>
  <Word word="" roman="oxygen" star="1"/>
  <Word word="" roman="interval" star="1"/>
  <Word word="" roman="mummy" star="1"/>
  <Word word="" roman="led" star="1"/>
  <Word word="" roman="humor" star="1"/>
  <Word word="" roman="perplex" star="1"/>
  <Word word="" roman="mustard" star="1"/>
  <Word word="" roman="magic" star="1"/>
  <Word word="" roman="glow" star="1"/>
  <Word word="" roman="outrage" star="1"/>
  <Word word="" roman="mainly" star="1"/>
  <Word word="" roman="prophet" star="1"/>
  <Word word="" roman="lodging" star="1"/>
  <Word word="" roman="influenza" star="1"/>
  <Word word="" roman="happening" star="1"/>
  <Word word="" roman="network" star="1"/>
  <Word word="" roman="hasten" star="1"/>
  <Word word="" roman="project" star="1"/>
  <Word word="" roman="godfather" star="1"/>
  <Word word="" roman="historic" star="1"/>
  <Word word="" roman="northeast" star="1"/>
  <Word word="" roman="Mississippi" star="1"/>
  <Word word="" roman="mushroom" star="1"/>
  <Word word="" roman="peach" star="1"/>
  <Word word="" roman="medal" star="1"/>
  <Word word="" roman="magnitude" star="1"/>
  <Word word="" roman="paradox" star="1"/>
  <Word word="" roman="injure" star="1"/>
  <Word word="" roman="mug" star="1"/>
  <Word word="" roman="glue" star="1"/>
  <Word word="" roman="jaw" star="1"/>
  <Word word="" roman="notable" star="1"/>
  <Word word="" roman="noisy" star="1"/>
  <Word word="" roman="offend" star="1"/>
  <Word word="" roman="hostel" star="1"/>
  <Word word="" roman="grim" star="1"/>
  <Word word="" roman="hoof" star="1"/>
  <Word word="" roman="insist" star="1"/>
  <Word word="" roman="presume" star="1"/>
  <Word word="" roman="personality" star="1"/>
  <Word word="" roman="gem" star="1"/>
  <Word word="" roman="paste" star="1"/>
  <Word word="" roman="particle" star="1"/>
  <Word word="" roman="nail" star="1"/>
  <Word word="" roman="hover" star="1"/>
  <Word word="" roman="mineral" star="1"/>
  <Word word="" roman="kettle" star="1"/>
  <Word word="" roman="mature" star="1"/>
  <Word word="" roman="monument" star="1"/>
  <Word word="" roman="hereafter" star="1"/>
  <Word word="" roman="minimum" star="1"/>
  <Word word="" roman="paragraph" star="1"/>
  <Word word="" roman="jungle" star="1"/>
  <Word word="" roman="necessity" star="1"/>
  <Word word="" roman="interpreter" star="1"/>
  <Word word="" roman="ostrich" star="1"/>
  <Word word="" roman="gallery" star="1"/>
  <Word word="" roman="grip" star="1"/>
  <Word word="" roman="intend" star="1"/>
  <Word word="" roman="predecessor" star="1"/>
  <Word word="" roman="primitive" star="1"/>
  <Word word="" roman="promote" star="1"/>
  <Word word="" roman="goddess" star="1"/>
  <Word word="" roman="incident" star="1"/>
  <Word word="" roman="patent" star="1"/>
  <Word word="" roman="ivory" star="1"/>
  <Word word="" roman="half-way" star="1"/>
  <Word word="" roman="platform" star="1"/>
  <Word word="" roman="girlfriend" star="1"/>
  <Word word="" roman="joint" star="1"/>
  <Word word="" roman="hurrah" star="1"/>
  <Word word="" roman="pane" star="1"/>
  <Word word="" roman="procure" star="1"/>
  <Word word="" roman="lame" star="1"/>
  <Word word="" roman="lasting" star="1"/>
  <Word word="" roman="pharmacy" star="1"/>
  <Word word="" roman="grew" star="1"/>
  <Word word="" roman="gratify" star="1"/>
  <Word word="" roman="lengthen" star="1"/>
  <Word word="" roman="magician" star="1"/>
  <Word word="" roman="glory" star="1"/>
  <Word word="" roman="porch" star="1"/>
  <Word word="" roman="occupy" star="1"/>
  <Word word="" roman="purge" star="1"/>
  <Word word="" roman="gorgeous" star="1"/>
  <Word word="" roman="harbor" star="1"/>
  <Word word="" roman="lavender" star="1"/>
  <Word word="" roman="old-fashioned" star="1"/>
  <Word word="" roman="majesty" star="1"/>
  <Word word="" roman="predict" star="1"/>
  <Word word="" roman="impact" star="1"/>
  <Word word="" roman="hive" star="1"/>
  <Word word="" roman="glare" star="1"/>
  <Word word="" roman="layer" star="1"/>
  <Word word="" roman="mingle" star="1"/>
  <Word word="" roman="owner" star="1"/>
  <Word word="" roman="groan" star="1"/>
  <Word word="" roman="jacket" star="1"/>
  <Word word="" roman="publication" star="1"/>
  <Word word="" roman="proof" star="1"/>
  <Word word="" roman="mutter" star="1"/>
  <Word word="" roman="junk" star="1"/>
  <Word word="" roman="politician" star="1"/>
  <Word word="" roman="ingratitude" star="1"/>
  <Word word="" roman="nowadays" star="1"/>
  <Word word="" roman="nap" star="1"/>
  <Word word="" roman="Moscow" star="1"/>
  <Word word="" roman="hare" star="1"/>
  <Word word="" roman="marvel" star="1"/>
  <Word word="" roman="informal" star="1"/>
  <Word word="" roman="obligation" star="1"/>
  <Word word="" roman="meddle" star="1"/>
  <Word word="" roman="lass" star="1"/>
  <Word word="" roman="geese" star="1"/>
  <Word word="" roman="grease" star="1"/>
  <Word word="" roman="incense" star="1"/>
  <Word word="" roman="mysterious" star="1"/>
  <Word word="" roman="local" star="1"/>
  <Word word="" roman="jar" star="1"/>
  <Word word="" roman="offensive" star="1"/>
  <Word word="" roman="monk" star="1"/>
  <Word word="" roman="niece" star="1"/>
  <Word word="" roman="Poland" star="1"/>
  <Word word="" roman="implore" star="1"/>
  <Word word="" roman="motif" star="1"/>
  <Word word="" roman="hypocrisy" star="1"/>
  <Word word="" roman="longing" star="1"/>
  <Word word="" roman="paddle" star="1"/>
  <Word word="" roman="hum" star="1"/>
  <Word word="" roman="minor" star="1"/>
  <Word word="" roman="proportion" star="1"/>
  <Word word="" roman="papa" star="1"/>
  <Word word="" roman="golf" star="1"/>
  <Word word="" roman="protection" star="1"/>
  <Word word="" roman="learned" star="1"/>
  <Word word="" roman="purple" star="1"/>
  <Word word="" roman="inherent" star="1"/>
  <Word word="" roman="oppose" star="1"/>
  <Word word="" roman="purse" star="1"/>
  <Word word="" roman="import" star="1"/>
  <Word word="" roman="meant" star="1"/>
  <Word word="" roman="massive" star="1"/>
  <Word word="" roman="normal" star="1"/>
  <Word word="" roman="legend" star="1"/>
  <Word word="" roman="proportional" star="1"/>
  <Word word="" roman="icy" star="1"/>
  <Word word="" roman="privacy" star="1"/>
  <Word word="" roman="plan" star="1"/>
  <Word word="" roman="hotel" star="1"/>
  <Word word="" roman="nationality" star="1"/>
  <Word word="" roman="kindly" star="1"/>
  <Word word="" roman="insure" star="1"/>
  <Word word="" roman="outfit" star="1"/>
  <Word word="" roman="host" star="1"/>
  <Word word="" roman="navy" star="1"/>
  <Word word="" roman="overflow" star="1"/>
  <Word word="" roman="knives" star="1"/>
  <Word word="" roman="pious" star="1"/>
  <Word word="" roman="pressing" star="1"/>
  <Word word="" roman="hymn" star="1"/>
  <Word word="" roman="hind" star="1"/>
  <Word word="" roman="Pacific Ocean" star="1"/>
  <Word word="" roman="prosperity" star="1"/>
  <Word word="" roman="inferior" star="1"/>
  <Word word="" roman="philosophy" star="1"/>
  <Word word="" roman="hyphen" star="1"/>
  <Word word="" roman="illegal" star="1"/>
  <Word word="" roman="professional" star="1"/>
  <Word word="" roman="hurl" star="1"/>
  <Word word="" roman="minus" star="1"/>
  <Word word="" roman="nominate" star="1"/>
  <Word word="" roman="generation" star="1"/>
  <Word word="" roman="manipulate" star="1"/>
  <Word word="" roman="leak" star="1"/>
  <Word word="" roman="overwork" star="1"/>
  <Word word="" roman="linger" star="1"/>
  <Word word="" roman="pepper" star="1"/>
  <Word word="" roman="outward" star="1"/>
  <Word word="" roman="prominent" star="1"/>
  <Word word="" roman="organization" star="1"/>
  <Word word="" roman="introduction" star="1"/>
  <Word word="" roman="naked" star="1"/>
  <Word word="" roman="portable" star="1"/>
  <Word word="" roman="process" star="1"/>
  <Word word="" roman="impossible" star="1"/>
  <Word word="" roman="population" star="1"/>
  <Word word="" roman="malice" star="1"/>
  <Word word="" roman="provision" star="1"/>
  <Word word="" roman="persist" star="1"/>
  <Word word="" roman="homeroom" star="1"/>
  <Word word="" roman="individual" star="1"/>
  <Word word="" roman="pier" star="1"/>
  <Word word="" roman="princess" star="1"/>
  <Word word="" roman="honey" star="1"/>
  <Word word="" roman="prime minister" star="1"/>
  <Word word="" roman="lad" star="1"/>
  <Word word="" roman="institute" star="1"/>
  <Word word="" roman="peaceful" star="1"/>
  <Word word="" roman="peril" star="1"/>
  <Word word="" roman="kid" star="1"/>
  <Word word="" roman="prohibition" star="1"/>
  <Word word="" roman="horizontal" star="1"/>
  <Word word="" roman="profound" star="1"/>
  <Word word="" roman="plate" star="1"/>
  <Word word="" roman="kindergarten" star="1"/>
  <Word word="" roman="prompt" star="1"/>
  <Word word="" roman="olive" star="1"/>
  <Word word="" roman="horror" star="1"/>
  <Word word="" roman="parcel" star="1"/>
  <Word word="" roman="massacre" star="1"/>
  <Word word="" roman="occasion" star="1"/>
  <Word word="" roman="obedient" star="1"/>
  <Word word="" roman="passion" star="1"/>
  <Word word="" roman="hush" star="1"/>
  <Word word="" roman="latest" star="1"/>
  <Word word="" roman="openly" star="1"/>
  <Word word="" roman="Pacific" star="1"/>
  <Word word="" roman="opposite" star="1"/>
  <Word word="" roman="lawn" star="1"/>
  <Word word="" roman="greet" star="1"/>
  <Word word="" roman="hay" star="1"/>
  <Word word="" roman="pose" star="1"/>
  <Word word="" roman="provoke" star="1"/>
  <Word word="" roman="Great Britain" star="1"/>
  <Word word="" roman="gulf" star="1"/>
  <Word word="" roman="precede" star="1"/>
  <Word word="" roman="perfection" star="1"/>
  <Word word="" roman="instructive" star="1"/>
  <Word word="" roman="moreover" star="1"/>
  <Word word="" roman="menace" star="1"/>
  <Word word="" roman="lobby" star="1"/>
  <Word word="" roman="lark" star="1"/>
  <Word word="" roman="grin" star="1"/>
  <Word word="" roman="overseas" star="1"/>
  <Word word="" roman="plague" star="1"/>
  <Word word="" roman="protect" star="1"/>
  <Word word="" roman="inclination" star="1"/>
  <Word word="" roman="perpetual" star="1"/>
  <Word word="" roman="lying" star="1"/>
  <Word word="" roman="melody" star="1"/>
  <Word word="" roman="OK" star="1"/>
  <Word word="" roman="hunger" star="1"/>
  <Word word="" roman="mailman" star="1"/>
  <Word word="" roman="input" star="1"/>
  <Word word="" roman="needle" star="1"/>
  <Word word="" roman="grocery" star="1"/>
  <Word word="" roman="goldfish" star="1"/>
  <Word word="" roman="mortal" star="1"/>
  <Word word="" roman="orient" star="1"/>
  <Word word="" roman="preach" star="1"/>
  <Word word="" roman="herb" star="1"/>
  <Word word="" roman="mold" star="1"/>
  <Word word="" roman="loose" star="1"/>
  <Word word="" roman="onion" star="1"/>
  <Word word="" roman="postage" star="1"/>
  <Word word="" roman="noun" star="1"/>
  <Word word="" roman="prior" star="1"/>
  <Word word="" roman="inactive" star="1"/>
  <Word word="" roman="omit" star="1"/>
  <Word word="" roman="physics" star="1"/>
  <Word word="" roman="handsome" star="1"/>
  <Word word="" roman="Holland" star="1"/>
  <Word word="" roman="gleam" star="1"/>
  <Word word="" roman="potential" star="1"/>
  <Word word="" roman="hatred" star="1"/>
  <Word word="" roman="premier" star="1"/>
  <Word word="" roman="proficient" star="1"/>
  <Word word="" roman="junction" star="1"/>
  <Word word="" roman="knelt" star="1"/>
  <Word word="" roman="overcoat" star="1"/>
  <Word word="" roman="heritage" star="1"/>
  <Word word="" roman="maximum" star="1"/>
  <Word word="" roman="moist" star="1"/>
  <Word word="" roman="Islam" star="1"/>
  <Word word="" roman="philosopher" star="1"/>
  <Word word="" roman="mourn" star="1"/>
  <Word word="" roman="margin" star="1"/>
  <Word word="" roman="ghost" star="1"/>
  <Word word="" roman="merchandise" star="1"/>
  <Word word="" roman="phone" star="1"/>
  <Word word="" roman="landing" star="1"/>
  <Word word="" roman="handful" star="1"/>
  <Word word="" roman="psychology" star="1"/>
  <Word word="" roman="independent" star="1"/>
  <Word word="" roman="honeymoon" star="1"/>
  <Word word="" roman="generalize" star="1"/>
  <Word word="" roman="lottery" star="1"/>
  <Word word="" roman="housewife" star="1"/>
  <Word word="" roman="helm" star="1"/>
  <Word word="" roman="interrupt" star="1"/>
  <Word word="" roman="meadow" star="1"/>
  <Word word="" roman="intensity" star="1"/>
  <Word word="" roman="Jerusalem" star="1"/>
  <Word word="" roman="item" star="1"/>
  <Word word="" roman="location" star="1"/>
  <Word word="" roman="idle" star="1"/>
  <Word word="" roman="grasp" star="1"/>
  <Word word="" roman="Iraq" star="1"/>
  <Word word="" roman="objective" star="1"/>
  <Word word="" roman="optics" star="1"/>
  <Word word="" roman="nursery" star="1"/>
  <Word word="" roman="neighboring" star="1"/>
  <Word word="" roman="publish" star="1"/>
  <Word word="" roman="powerful" star="1"/>
  <Word word="" roman="lightly" star="1"/>
  <Word word="" roman="luncheon" star="1"/>
  <Word word="" roman="ledge" star="1"/>
  <Word word="" roman="hatch" star="1"/>
  <Word word="" roman="popularity" star="1"/>
  <Word word="" roman="plot" star="1"/>
  <Word word="" roman="pension" star="1"/>
  <Word word="" roman="overtime" star="1"/>
  <Word word="" roman="gratitude" star="1"/>
  <Word word="" roman="poetry" star="1"/>
  <Word word="" roman="North America" star="1"/>
  <Word word="" roman="harness" star="1"/>
  <Word word="" roman="plead" star="1"/>
  <Word word="" roman="gesture" star="1"/>
  <Word word="" roman="pigment" star="1"/>
  <Word word="" roman="musical" star="1"/>
  <Word word="" roman="lung" star="1"/>
  <Word word="" roman="outlook" star="1"/>
  <Word word="" roman="per" star="1"/>
  <Word word="" roman="illusion" star="1"/>
  <Word word="" roman="lonely" star="1"/>
  <Word word="" roman="penguin" star="1"/>
  <Word word="" roman="locomotive" star="1"/>
  <Word word="" roman="pebble" star="1"/>
  <Word word="" roman="otherwise" star="1"/>
  <Word word="" roman="gossip" star="1"/>
  <Word word="" roman="indoors" star="1"/>
  <Word word="" roman="lap" star="1"/>
  <Word word="" roman="Halloween" star="1"/>
  <Word word="" roman="preposition" star="1"/>
  <Word word="" roman="prestige" star="1"/>
  <Word word="" roman="gamble" star="1"/>
  <Word word="" roman="impressive" star="1"/>
  <Word word="" roman="grape" star="1"/>
  <Word word="" roman="New Year" star="1"/>
  <Word word="" roman="processor" star="1"/>
  <Word word="" roman="means" star="1"/>
  <Word word="" roman="inquire" star="1"/>
  <Word word="" roman="homeless" star="1"/>
  <Word word="" roman="observe" star="1"/>
  <Word word="" roman="octopus" star="1"/>
  <Word word="" roman="helpless" star="1"/>
  <Word word="" roman="metal" star="1"/>
  <Word word="" roman="minority" star="1"/>
  <Word word="" roman="lantern" star="1"/>
  <Word word="" roman="insert" star="1"/>
  <Word word="" roman="protective" star="1"/>
  <Word word="" roman="hostility" star="1"/>
  <Word word="" roman="heel" star="1"/>
  <Word word="" roman="likewise" star="1"/>
  <Word word="" roman="negative" star="1"/>
  <Word word="" roman="hung" star="1"/>
  <Word word="" roman="P.M." star="1"/>
  <Word word="" roman="hearing" star="1"/>
  <Word word="" roman="mirror" star="1"/>
  <Word word="" roman="historian" star="1"/>
  <Word word="" roman="healthy" star="1"/>
  <Word word="" roman="inspiration" star="1"/>
  <Word word="" roman="microscope" star="1"/>
  <Word word="" roman="keen" star="1"/>
  <Word word="" roman="oak" star="1"/>
  <Word word="" roman="lash" star="1"/>
  <Word word="" roman="peanut" star="1"/>
  <Word word="" roman="haul" star="1"/>
  <Word word="" roman="lapse" star="1"/>
  <Word word="" roman="injury" star="1"/>
  <Word word="" roman="globe" star="1"/>
  <Word word="" roman="plough" star="1"/>
  <Word word="" roman="marshal" star="1"/>
  <Word word="" roman="pregnant" star="1"/>
  <Word word="" roman="myth" star="1"/>
  <Word word="" roman="pamphlet" star="1"/>
  <Word word="" roman="periodical" star="1"/>
  <Word word="" roman="hurried" star="1"/>
  <Word word="" roman="lone" star="1"/>
  <Word word="" roman="institution" star="1"/>
  <Word word="" roman="monopolize" star="1"/>
  <Word word="" roman="missing" star="1"/>
  <Word word="" roman="good afternoon" star="1"/>
  <Word word="" roman="passage" star="1"/>
  <Word word="" roman="itch" star="1"/>
  <Word word="" roman="mamma" star="1"/>
  <Word word="" roman="gay" star="1"/>
  <Word word="" roman="limit" star="1"/>
  <Word word="" roman="novel" star="1"/>
  <Word word="" roman="marsh" star="1"/>
  <Word word="" roman="gear" star="1"/>
  <Word word="" roman="pink" star="1"/>
  <Word word="" roman="internal" star="1"/>
  <Word word="" roman="pitcher" star="1"/>
  <Word word="" roman="helpful" star="1"/>
  <Word word="" roman="politics" star="1"/>
  <Word word="" roman="humane" star="1"/>
  <Word word="" roman="nuclear" star="1"/>
  <Word word="" roman="madam" star="1"/>
  <Word word="" roman="prescribe" star="1"/>
  <Word word="" roman="naturally" star="1"/>
  <Word word="" roman="napkin" star="1"/>
  <Word word="" roman="mantle" star="1"/>
  <Word word="" roman="lust" star="1"/>
  <Word word="" roman="heal" star="1"/>
  <Word word="" roman="graphic" star="1"/>
  <Word word="" roman="musician" star="1"/>
  <Word word="" roman="necessarily" star="1"/>
  <Word word="" roman="idiom" star="1"/>
  <Word word="" roman="orbit" star="1"/>
  <Word word="" roman="harmless" star="1"/>
  <Word word="" roman="orphan" star="1"/>
  <Word word="" roman="invalid" star="1"/>
  <Word word="" roman="largely" star="1"/>
  <Word word="" roman="pluck" star="1"/>
  <Word word="" roman="grind" star="1"/>
  <Word word="" roman="nobility" star="1"/>
  <Word word="" roman="pedestal" star="1"/>
  <Word word="" roman="merely" star="1"/>
  <Word word="" roman="mourning" star="1"/>
  <Word word="" roman="inaugurate" star="1"/>
  <Word word="" roman="numerous" star="1"/>
  <Word word="" roman="hunt" star="1"/>
  <Word word="" roman="moss" star="1"/>
  <Word word="" roman="installment" star="1"/>
  <Word word="" roman="guidebook" star="1"/>
  <Word word="" roman="glitter" star="1"/>
  <Word word="" roman="postcard" star="1"/>
  <Word word="" roman="guilty" star="1"/>
  <Word word="" roman="numeral" star="1"/>
  <Word word="" roman="lace" star="1"/>
  <Word word="" roman="imprison" star="1"/>
  <Word word="" roman="pad" star="1"/>
  <Word word="" roman="layout" star="1"/>
  <Word word="" roman="pilgrim" star="1"/>
  <Word word="" roman="needless" star="1"/>
  <Word word="" roman="pile" star="1"/>
  <Word word="" roman="grain" star="1"/>
  <Word word="" roman="obey" star="1"/>
  <Word word="" roman="genuine" star="1"/>
  <Word word="" roman="helmet" star="1"/>
  <Word word="" roman="penny" star="1"/>
  <Word word="" roman="leadership" star="1"/>
  <Word word="" roman="geology" star="1"/>
  <Word word="" roman="mammal" star="1"/>
  <Word word="" roman="oral" star="1"/>
  <Word word="" roman="loop" star="1"/>
  <Word word="" roman="guardian" star="1"/>
  <Word word="" roman="income" star="1"/>
  <Word word="" roman="Irish" star="1"/>
  <Word word="" roman="poorly" star="1"/>
  <Word word="" roman="opposition" star="1"/>
  <Word word="" roman="peer" star="1"/>
  <Word word="" roman="innumerable" star="1"/>
  <Word word="" roman="province" star="1"/>
  <Word word="" roman="grotesque" star="1"/>
  <Word word="" roman="Peru" star="1"/>
  <Word word="" roman="pack" star="1"/>
  <Word word="" roman="infinite" star="1"/>
  <Word word="" roman="geographic" star="1"/>
  <Word word="" roman="pail" star="1"/>
  <Word word="" roman="herd" star="1"/>
  <Word word="" roman="pollution" star="1"/>
  <Word word="" roman="Nile" star="1"/>
  <Word word="" roman="physical" star="1"/>
  <Word word="" roman="instruction" star="1"/>
  <Word word="" roman="moisture" star="1"/>
  <Word word="" roman="multiply" star="1"/>
  <Word word="" roman="magnet" star="1"/>
  <Word word="" roman="insect" star="1"/>
  <Word word="" roman="oat" star="1"/>
  <Word word="" roman="gracious" star="1"/>
  <Word word="" roman="modify" star="1"/>
  <Word word="" roman="ox" star="1"/>
  <Word word="" roman="motto" star="1"/>
  <Word word="" roman="monotonous" star="1"/>
  <Word word="" roman="hurdle" star="1"/>
  <Word word="" roman="ounce" star="1"/>
  <Word word="" roman="immense" star="1"/>
  <Word word="" roman="mass" star="1"/>
  <Word word="" roman="gum" star="1"/>
  <Word word="" roman="pale" star="1"/>
  <Word word="" roman="intent" star="1"/>
  <Word word="" roman="ideal" star="1"/>
  <Word word="" roman="praise" star="1"/>
  <Word word="" roman="mild" star="1"/>
  <Word word="" roman="imply" star="1"/>
  <Word word="" roman="monster" star="1"/>
  <Word word="" roman="heavenly" star="1"/>
  <Word word="" roman="honorable" star="1"/>
  <Word word="" roman="planet" star="1"/>
  <Word word="" roman="Italian" star="1"/>
  <Word word="" roman="mode" star="1"/>
  <Word word="" roman="origin" star="1"/>
  <Word word="" roman="induce" star="1"/>
  <Word word="" roman="prelude" star="1"/>
  <Word word="" roman="pardon" star="1"/>
  <Word word="" roman="nourish" star="1"/>
  <Word word="" roman="Hawaii" star="1"/>
  <Word word="" roman="liar" star="1"/>
  <Word word="" roman="possess" star="1"/>
  <Word word="" roman="polite" star="1"/>
  <Word word="" roman="interrogation" star="1"/>
  <Word word="" roman="overcome" star="1"/>
  <Word word="" roman="humanist" star="1"/>
  <Word word="" roman="pillar" star="1"/>
  <Word word="" roman="kick" star="1"/>
  <Word word="" roman="locust" star="1"/>
  <Word word="" roman="maintain" star="1"/>
  <Word word="" roman="petal" star="1"/>
  <Word word="" roman="inevitable" star="1"/>
  <Word word="" roman="printing" star="1"/>
  <Word word="" roman="lest" star="1"/>
  <Word word="" roman="nickel" star="1"/>
  <Word word="" roman="patrol" star="1"/>
  <Word word="" roman="invade" star="1"/>
  <Word word="" roman="pursue" star="1"/>
  <Word word="" roman="goat" star="1"/>
  <Word word="" roman="match" star="1"/>
  <Word word="" roman="obstinate" star="1"/>
  <Word word="" roman="patient" star="1"/>
  <Word word="" roman="nod" star="1"/>
  <Word word="" roman="laughter" star="1"/>
  <Word word="" roman="harmonious" star="1"/>
  <Word word="" roman="legal" star="1"/>
  <Word word="" roman="organize" star="1"/>
  <Word word="" roman="governor" star="1"/>
  <Word word="" roman="nickname" star="1"/>
  <Word word="" roman="ladder" star="1"/>
  <Word word="" roman="liberty" star="1"/>
  <Word word="" roman="heed" star="1"/>
  <Word word="" roman="irritate" star="1"/>
  <Word word="" roman="oven" star="1"/>
  <Word word="" roman="painful" star="1"/>
  <Word word="" roman="opening" star="1"/>
  <Word word="" roman="harp" star="1"/>
  <Word word="" roman="persistent" star="1"/>
  <Word word="" roman="pork" star="1"/>
  <Word word="" roman="neat" star="1"/>
  <Word word="" roman="maintenance" star="1"/>
  <Word word="" roman="midday" star="1"/>
  <Word word="" roman="peep" star="1"/>
  <Word word="" roman="lime" star="1"/>
  <Word word="" roman="intellectual" star="1"/>
  <Word word="" roman="lifetime" star="1"/>
  <Word word="" roman="inquiry" star="1"/>
  <Word word="" roman="outcome" star="1"/>
  <Word word="" roman="herald" star="1"/>
  <Word word="" roman="haughty" star="1"/>
  <Word word="" roman="key" star="1"/>
  <Word word="" roman="placard" star="1"/>
  <Word word="" roman="journey" star="1"/>
  <Word word="" roman="muddy" star="1"/>
  <Word word="" roman="posterity" star="1"/>
  <Word word="" roman="prosperous" star="1"/>
  <Word word="" roman="ham" star="1"/>
  <Word word="" roman="Jew" star="1"/>
  <Word word="" roman="messenger" star="1"/>
  <Word word="" roman="Mars" star="1"/>
  <Word word="" roman="instinct" star="1"/>
  <Word word="" roman="overlook" star="1"/>
  <Word word="" roman="laundry" star="1"/>
  <Word word="" roman="mathematical" star="1"/>
  <Word word="" roman="govern" star="1"/>
  <Word word="" roman="overwhelm" star="1"/>
  <Word word="" roman="moor" star="1"/>
  <Word word="" roman="miniature" star="1"/>
  <Word word="" roman="painter" star="1"/>
  <Word word="" roman="mad" star="1"/>
  <Word word="" roman="lumber" star="1"/>
  <Word word="" roman="jolly" star="1"/>
  <Word word="" roman="prolong" star="1"/>
  <Word word="" roman="Israel" star="1"/>
  <Word word="" roman="interpretation" star="1"/>
  <Word word="" roman="propose" star="1"/>
  <Word word="" roman="persuade" star="1"/>
  <Word word="" roman="logic" star="1"/>
  <Word word="" roman="nitrogen" star="1"/>
  <Word word="" roman="ore" star="1"/>
  <Word word="" roman="powder" star="1"/>
  <Word word="" roman="headlong" star="1"/>
  <Word word="" roman="onward" star="1"/>
  <Word word="" roman="nasty" star="1"/>
  <Word word="" roman="mere" star="1"/>
  <Word word="" roman="mattress" star="1"/>
  <Word word="" roman="precaution" star="1"/>
  <Word word="" roman="murmur" star="1"/>
  <Word word="" roman="incline" star="1"/>
  <Word word="" roman="mantelpiece" star="1"/>
  <Word word="" roman="hesitate" star="1"/>
  <Word word="" roman="identical" star="1"/>
  <Word word="" roman="permission" star="1"/>
  <Word word="" roman="landlord" star="1"/>
  <Word word="" roman="naval" star="1"/>
  <Word word="" roman="justice" star="1"/>
  <Word word="" roman="lyric" star="1"/>
  <Word word="" roman="gigantic" star="1"/>
  <Word word="" roman="phenomenon" star="1"/>
  <Word word="" roman="inform" star="1"/>
  <Word word="" roman="one's" star="1"/>
  <Word word="" roman="medical" star="1"/>
  <Word word="" roman="hate" star="1"/>
  <Word word="" roman="possessive" star="1"/>
  <Word word="" roman="military" star="1"/>
  <Word word="" roman="nationalism" star="1"/>
  <Word word="" roman="glance" star="1"/>
  <Word word="" roman="major" star="1"/>
  <Word word="" roman="occupation" star="1"/>
  <Word word="" roman="port" star="1"/>
  <Word word="" roman="naughty" star="1"/>
  <Word word="" roman="Geneva" star="1"/>
  <Word word="" roman="knight" star="1"/>
  <Word word="" roman="hence" star="1"/>
  <Word word="" roman="permit" star="1"/>
  <Word word="" roman="outdoor" star="1"/>
  <Word word="" roman="horseman" star="1"/>
  <Word word="" roman="involve" star="1"/>
  <Word word="" roman="obstruct" star="1"/>
  <Word word="" roman="pea" star="1"/>
  <Word word="" roman="poverty" star="1"/>
  <Word word="" roman="lick" star="1"/>
  <Word word="" roman="municipal" star="1"/>
  <Word word="" roman="parliament" star="1"/>
  <Word word="" roman="practically" star="1"/>
  <Word word="" roman="good-looking" star="1"/>
  <Word word="" roman="lord" star="1"/>
  <Word word="" roman="juice" star="1"/>
  <Word word="" roman="playground" star="1"/>
  <Word word="" roman="geometry" star="1"/>
  <Word word="" roman="kindred" star="1"/>
  <Word word="" roman="punch" star="1"/>
  <Word word="" roman="jazz" star="1"/>
  <Word word="" roman="pillow" star="1"/>
  <Word word="" roman="global" star="1"/>
  <Word word="" roman="interview" star="1"/>
  <Word word="" roman="hint" star="1"/>
  <Word word="" roman="paw" star="1"/>
  <Word word="" roman="kidnap" star="1"/>
  <Word word="" roman="handwriting" star="1"/>
  <Word word="" roman="pendant" star="1"/>
  <Word word="" roman="gauge" star="1"/>
  <Word word="" roman="howl" star="1"/>
  <Word word="" roman="gallant" star="1"/>
  <Word word="" roman="moan" star="1"/>
  <Word word="" roman="isolate" star="1"/>
  <Word word="" roman="mercury" star="1"/>
  <Word word="" roman="illness" star="1"/>
  <Word word="" roman="murder" star="1"/>
  <Word word="" roman="liberal" star="1"/>
  <Word word="" roman="inject" star="1"/>
  <Word word="" roman="hostess" star="1"/>
  <Word word="" roman="majority" star="1"/>
  <Word word="" roman="pending" star="1"/>
  <Word word="" roman="heap" star="1"/>
  <Word word="" roman="insane" star="1"/>
  <Word word="" roman="original" star="1"/>
  <Word word="" roman="muse" star="1"/>
  <Word word="" roman="prisoner" star="1"/>
  <Word word="" roman="organic" star="1"/>
  <Word word="" roman="permanent" star="1"/>
  <Word word="" roman="incredible" star="1"/>
  <Word word="" roman="mountainous" star="1"/>
  <Word word="" roman="oar" star="1"/>
  <Word word="" roman="official" star="1"/>
  <Word word="" roman="petition" star="1"/>
  <Word word="" roman="insult" star="1"/>
  <Word word="" roman="impatient" star="1"/>
  <Word word="" roman="profession" star="1"/>
  <Word word="" roman="partner" star="1"/>
  <Word word="" roman="marvelous" star="1"/>
  <Word word="" roman="intransitive" star="1"/>
  <Word word="" roman="jelly" star="1"/>
  <Word word="" roman="gap" star="1"/>
  <Word word="" roman="nuisance" star="1"/>
  <Word word="" roman="manifest" star="1"/>
  <Word word="" roman="masculine" star="1"/>
  <Word word="" roman="product" star="1"/>
  <Word word="" roman="pedal" star="1"/>
  <Word word="" roman="nightmare" star="1"/>
  <Word word="" roman="knave" star="1"/>
  <Word word="" roman="penalty" star="1"/>
  <Word word="" roman="misery" star="1"/>
  <Word word="" roman="infamous" star="1"/>
  <Word word="" roman="include" star="1"/>
  <Word word="" roman="predicate" star="1"/>
  <Word word="" roman="lower" star="1"/>
  <Word word="" roman="priority" star="1"/>
  <Word word="" roman="outlet" star="1"/>
  <Word word="" roman="progressive" star="1"/>
  <Word word="" roman="invisible" star="1"/>
  <Word word="" roman="jet" star="1"/>
  <Word word="" roman="motorcar" star="1"/>
  <Word word="" roman="league" star="1"/>
  <Word word="" roman="halt" star="1"/>
  <Word word="" roman="humorous" star="1"/>
  <Word word="" roman="Ireland" star="1"/>
  <Word word="" roman="mate" star="1"/>
  <Word word="" roman="Norway" star="1"/>
  <Word word="" roman="peacock" star="1"/>
  <Word word="" roman="intense" star="1"/>
  <Word word="" roman="inhabit" star="1"/>
  <Word word="" roman="growing" star="1"/>
  <Word word="" roman="opponent" star="1"/>
  <Word word="" roman="profit" star="1"/>
  <Word word="" roman="graduate" star="1"/>
  <Word word="" roman="guy" star="1"/>
  <Word word="" roman="pan" star="1"/>
  <Word word="" roman="prescription" star="1"/>
  <Word word="" roman="leisure" star="1"/>
  <Word word="" roman="protest" star="1"/>
  <Word word="" roman="miser" star="1"/>
  <Word word="" roman="pinch" star="1"/>
  <Word word="" roman="pitch" star="1"/>
  <Word word="" roman="inspire" star="1"/>
  <Word word="" roman="Philippines" star="1"/>
  <Word word="" roman="horrible" star="1"/>
  <Word word="" roman="lecture" star="1"/>
  <Word word="" roman="historical" star="1"/>
  <Word word="" roman="horn" star="1"/>
  <Word word="" roman="perform" star="1"/>
  <Word word="" roman="prevention" star="1"/>
  <Word word="" roman="pledge" star="1"/>
  <Word word="" roman="ornament" star="1"/>
  <Word word="" roman="offspring" star="1"/>
  <Word word="" roman="previous" star="1"/>
  <Word word="" roman="mellow" star="1"/>
  <Word word="" roman="paralyze" star="1"/>
  <Word word="" roman="preliminary" star="1"/>
  <Word word="" roman="lock" star="1"/>
  <Word word="" roman="hermit" star="1"/>
  <Word word="" roman="midnight" star="1"/>
  <Word word="" roman="intention" star="1"/>
  <Word word="" roman="manage" star="1"/>
  <Word word="" roman="inward" star="1"/>
  <Word word="" roman="hail" star="1"/>
  <Word word="" roman="miner" star="1"/>
  <Word word="" roman="panel" star="1"/>
  <Word word="" roman="merit" star="1"/>
  <Word word="" roman="Greece" star="1"/>
  <Word word="" roman="loan" star="1"/>
  <Word word="" roman="interjection" star="1"/>
  <Word word="" roman="hire" star="1"/>
  <Word word="" roman="melt" star="1"/>
  <Word word="" roman="prudent" star="1"/>
  <Word word="" roman="mice" star="1"/>
  <Word word="" roman="pen pal" star="1"/>
  <Word word="" roman="idol" star="1"/>
  <Word word="" roman="horizon" star="1"/>
  <Word word="" roman="hound" star="1"/>
  <Word word="" roman="polar" star="1"/>
  <Word word="" roman="hue" star="1"/>
  <Word word="" roman="grace" star="1"/>
  <Word word="" roman="horseback" star="1"/>
  <Word word="" roman="operation" star="1"/>
  <Word word="" roman="punish" star="1"/>
  <Word word="" roman="mist" star="1"/>
  <Word word="" roman="initiative" star="1"/>
  <Word word="" roman="mournful" star="1"/>
  <Word word="" roman="neglect" star="1"/>
  <Word word="" roman="productive" star="1"/>
  <Word word="" roman="hazard" star="1"/>
  <Word word="" roman="insignificant" star="1"/>
  <Word word="" roman="open air" star="1"/>
  <Word word="" roman="latitude" star="1"/>
  <Word word="" roman="incorporate" star="1"/>
  <Word word="" roman="landlady" star="1"/>
  <Word word="" roman="glide" star="1"/>
  <Word word="" roman="harmony" star="1"/>
  <Word word="" roman="invest" star="1"/>
  <Word word="" roman="gorilla" star="1"/>
  <Word word="" roman="mock" star="1"/>
  <Word word="" roman="hug" star="1"/>
  <Word word="" roman="good luck" star="1"/>
  <Word word="" roman="migrate" star="1"/>
  <Word word="" roman="lure" star="1"/>
  <Word word="" roman="overturn" star="1"/>
  <Word word="" roman="paraphrase" star="1"/>
  <Word word="" roman="giant" star="1"/>
  <Word word="" roman="pear" star="1"/>
  <Word word="" roman="inadequate" star="1"/>
  <Word word="" roman="neighbor" star="1"/>
  <Word word="" roman="glimpse" star="1"/>
  <Word word="" roman="motion" star="1"/>
  <Word word="" roman="pour" star="1"/>
  <Word word="" roman="main" star="1"/>
  <Word word="" roman="pave" star="1"/>
  <Word word="" roman="melon" star="1"/>
  <Word word="" roman="kitten" star="1"/>
  <Word word="" roman="goodwill" star="1"/>
  <Word word="" roman="mutton" star="1"/>
  <Word word="" roman="nephew" star="1"/>
  <Word word="" roman="headquarters" star="1"/>
  <Word word="" roman="pronoun" star="1"/>
  <Word word="" roman="isle" star="1"/>
  <Word word="" roman="narrative" star="1"/>
  <Word word="" roman="heroic" star="1"/>
  <Word word="" roman="pony" star="1"/>
  <Word word="" roman="hinder" star="1"/>
  <Word word="" roman="justify" star="1"/>
  <Word word="" roman="holder" star="1"/>
  <Word word="" roman="procession" star="1"/>
  <Word word="" roman="garage" star="1"/>
  <Word word="" roman="homesick" star="1"/>
  <Word word="" roman="palm" star="1"/>
  <Word word="" roman="perilous" star="1"/>
  <Word word="" roman="liquor" star="1"/>
  <Word word="" roman="ice cream" star="1"/>
  <Word word="" roman="needn't" star="1"/>
  <Word word="" roman="particular" star="1"/>
  <Word word="" roman="pant" star="1"/>
  <Word word="" roman="galaxy" star="1"/>
  <Word word="" roman="immediate" star="1"/>
  <Word word="" roman="grown-up" star="1"/>
  <Word word="" roman="gun" star="1"/>
  <Word word="" roman="puzzle" star="1"/>
  <Word word="" roman="handy" star="1"/>
  <Word word="" roman="political" star="1"/>
  <Word word="" roman="jolt" star="1"/>
  <Word word="" roman="leap" star="1"/>
  <Word word="" roman="overthrow" star="1"/>
  <Word word="" roman="graceful" star="1"/>
  <Word word="" roman="leather" star="1"/>
  <Word word="" roman="machinery" star="1"/>
  <Word word="" roman="menu" star="1"/>
  <Word word="" roman="puff" star="1"/>
  <Word word="" roman="hostage" star="1"/>
  <Word word="" roman="plume" star="1"/>
  <Word word="" roman="hydrogen" star="1"/>
  <Word word="" roman="ironic" star="1"/>
  <Word word="" roman="knot" star="1"/>
  <Word word="" roman="heave" star="1"/>
  <Word word="" roman="lull" star="1"/>
  <Word word="" roman="missile" star="1"/>
  <Word word="" roman="intonation" star="1"/>
  <Word word="" roman="lightning" star="1"/>
  <Word word="" roman="perfume" star="1"/>
  <Word word="" roman="petroleum" star="1"/>
  <Word word="" roman="promotion" star="1"/>
  <Word word="" roman="list" star="1"/>
  <Word word="" roman="phoenix" star="1"/>
  <Word word="" roman="lazy" star="1"/>
  <Word word="" roman="peak" star="1"/>
  <Word word="" roman="ordinary" star="1"/>
  <Word word="" roman="hike" star="1"/>
  <Word word="" roman="metropolis" star="1"/>
  <Word word="" roman="hood" star="1"/>
  <Word word="" roman="partial" star="1"/>
  <Word word="" roman="judgment" star="1"/>
  <Word word="" roman="install" star="1"/>
  <Word word="" roman="Honolulu" star="1"/>
  <Word word="" roman="oblige" star="1"/>
  <Word word="" roman="oppress" star="1"/>
  <Word word="" roman="image" star="1"/>
  <Word word="" roman="multiple" star="1"/>
  <Word word="" roman="germ" star="1"/>
  <Word word="" roman="mud" star="1"/>
  <Word word="" roman="latter" star="1"/>
  <Word word="" roman="gymnastic" star="1"/>
  <Word word="" roman="generous" star="1"/>
  <Word word="" roman="plank" star="1"/>
  <Word word="" roman="metropolitan" star="1"/>
  <Word word="" roman="literal" star="1"/>
  <Word word="" roman="mystery" star="1"/>
  <Word word="" roman="magnify" star="1"/>
  <Word word="" roman="print" star="1"/>
  <Word word="" roman="industrial" star="1"/>
  <Word word="" roman="performance" star="1"/>
  <Word word="" roman="intelligent" star="1"/>
  <Word word="" roman="platinum" star="1"/>
  <Word word="" roman="hasty" star="1"/>
  <Word word="" roman="parasite" star="1"/>
  <Word word="" roman="inspect" star="1"/>
  <Word word="" roman="publicity" star="1"/>
  <Word word="" roman="impulse" star="1"/>
  <Word word="" roman="greed" star="1"/>
  <Word word="" roman="pointed" star="1"/>
  <Word word="" roman="pat" star="1"/>
  <Word word="" roman="proverb" star="1"/>
  <Word word="" roman="maze" star="1"/>
  <Word word="" roman="loosen" star="1"/>
  <Word word="" roman="goodness" star="1"/>
  <Word word="" roman="pot" star="1"/>
  <Word word="" roman="injustice" star="1"/>
  <Word word="" roman="lain" star="1"/>
  <Word word="" roman="intimate" star="1"/>
  <Word word="" roman="private" star="1"/>
  <Word word="" roman="loaf" star="1"/>
  <Word word="" roman="impression" star="1"/>
  <Word word="" roman="laurel" star="1"/>
  <Word word="" roman="gaze" star="1"/>
  <Word word="" roman="linguistic" star="1"/>
  <Word word="" roman="postal" star="1"/>
  <Word word="" roman="pine" star="1"/>
  <Word word="" roman="nude" star="1"/>
  <Word word="" roman="ingenious" star="1"/>
  <Word word="" roman="possibly" star="1"/>
  <Word word="" roman="notion" star="1"/>
  <Word word="" roman="prefix" star="1"/>
  <Word word="" roman="housekeeper" star="1"/>
  <Word word="" roman="intervene" star="1"/>
  <Word word="" roman="interpret" star="1"/>
  <Word word="" roman="plump" star="1"/>
  <Word word="" roman="opinion" star="1"/>
  <Word word="" roman="overtake" star="1"/>
  <Word word="" roman="index" star="1"/>
  <Word word="" roman="instant" star="1"/>
  <Word word="" roman="immortal" star="1"/>
  <Word word="" roman="laborer" star="1"/>
  <Word word="" roman="pump" star="1"/>
  <Word word="" roman="gang" star="1"/>
  <Word word="" roman="gasp" star="1"/>
  <Word word="" roman="hearty" star="1"/>
  <Word word="" roman="pill" star="1"/>
  <Word word="" roman="haste" star="1"/>
  <Word word="" roman="hip" star="1"/>
  <Word word="" roman="marine" star="1"/>
  <Word word="" roman="patriot" star="1"/>
  <Word word="" roman="lighten" star="1"/>
  <Word word="" roman="nowhere" star="1"/>
  <Word word="" roman="plow" star="1"/>
  <Word word="" roman="necklace" star="1"/>
  <Word word="" roman="lover" star="1"/>
  <Word word="" roman="parlor" star="1"/>
  <Word word="" roman="prayer" star="1"/>
  <Word word="" roman="hop" star="1"/>
  <Word word="" roman="irony" star="1"/>
  <Word word="" roman="owe" star="1"/>
  <Word word="" roman="meditate" star="1"/>
  <Word word="" roman="manhood" star="1"/>
  <Word word="" roman="gym" star="1"/>
  <Word word="" roman="medium" star="1"/>
  <Word word="" roman="lofty" star="1"/>
  <Word word="" roman="maxim" star="1"/>
  <Word word="" roman="notify" star="1"/>
  <Word word="" roman="possession" star="1"/>
  <Word word="" roman="inn" star="1"/>
  <Word word="" roman="gravel" star="1"/>
  <Word word="" roman="homely" star="1"/>
  <Word word="" roman="hardy" star="1"/>
  <Word word="" roman="meter" star="1"/>
  <Word word="" roman="incessant" star="1"/>
  <Word word="" roman="hunter" star="1"/>
  <Word word="" roman="mistaken" star="1"/>
  <Word word="" roman="nearby" star="1"/>
  <Word word="" roman="misty" star="1"/>
  <Word word="" roman="indent" star="1"/>
  <Word word="" roman="lemon" star="1"/>
  <Word word="" roman="good-natured" star="1"/>
  <Word word="" roman="merciful" star="1"/>
  <Word word="" roman="phrase" star="1"/>
  <Word word="" roman="graduation" star="1"/>
  <Word word="" roman="lively" star="1"/>
  <Word word="" roman="pattern" star="1"/>
  <Word word="" roman="infancy" star="1"/>
  <Word word="" roman="gross" star="1"/>
  <Word word="" roman="gateway" star="1"/>
  <Word word="" roman="meaning" star="1"/>
  <Word word="" roman="manual" star="1"/>
  <Word word="" roman="panther" star="1"/>
  <Word word="" roman="privilege" star="1"/>
  <Word word="" roman="illuminate" star="1"/>
  <Word word="" roman="growl" star="1"/>
  <Word word="" roman="occur" star="1"/>
  <Word word="" roman="gallop" star="1"/>
  <Word word="" roman="heartily" star="1"/>
  <Word word="" roman="investment" star="1"/>
  <Word word="" roman="invitation" star="1"/>
  <Word word="" roman="pasture" star="1"/>
  <Word word="" roman="perceive" star="1"/>
  <Word word="" roman="grumble" star="1"/>
  <Word word="" roman="proclaim" star="1"/>
  <Word word="" roman="New England" star="1"/>
  <Word word="" roman="humanism" star="1"/>
  <Word word="" roman="mislead" star="1"/>
  <Word word="" roman="manufacture" star="1"/>
  <Word word="" roman="pioneer" star="1"/>
  <Word word="" roman="mayor" star="1"/>
  <Word word="" roman="hidden" star="1"/>
  <Word word="" roman="opera" star="1"/>
  <Word word="" roman="prime" star="1"/>
  <Word word="" roman="literature" star="1"/>
  <Word word="" roman="invention" star="1"/>
  <Word word="" roman="handle" star="1"/>
  <Word word="" roman="manly" star="1"/>
  <Word word="" roman="lawful" star="1"/>
  <Word word="" roman="postpone" star="1"/>
  <Word word="" roman="gift" star="1"/>
  <Word word="" roman="jewel" star="1"/>
  <Word word="" roman="monopoly" star="1"/>
  <Word word="" roman="ideology" star="1"/>
  <Word word="" roman="innocent" star="1"/>
  <Word word="" roman="mason" star="1"/>
  <Word word="" roman="issue" star="1"/>
  <Word word="" roman="nymph" star="1"/>
  <Word word="" roman="northern" star="1"/>
  <Word word="" roman="nomad" star="1"/>
  <Word word="" roman="millionaire" star="1"/>
  <Word word="" roman="lamb" star="1"/>
  <Word word="" roman="precise" star="1"/>
  <Word word="" roman="peasant" star="1"/>
  <Word word="" roman="mortar" star="1"/>
  <Word word="" roman="magnificent" star="1"/>
  <Word word="" roman="Iran" star="1"/>
  <Word word="" roman="pie" star="1"/>
  <Word word="" roman="heir" star="1"/>
  <Word word="" roman="loving" star="1"/>
  <Word word="" roman="high school" star="1"/>
  <Word word="" roman="grasshopper" star="1"/>
  <Word word="" roman="Mexico" star="1"/>
  <Word word="" roman="mistress" star="1"/>
  <Word word="" roman="indefinite" star="1"/>
  <Word word="" roman="janitor" star="1"/>
  <Word word="" roman="hunting" star="1"/>
  <Word word="" roman="poison" star="1"/>
  <Word word="" roman="prey" star="1"/>
  <Word word="" roman="inherit" star="1"/>
  <Word word="" roman="painting" star="1"/>
  <Word word="" roman="parachute" star="1"/>
  <Word word="" roman="printer" star="1"/>
  <Word word="" roman="oasis" star="1"/>
  <Word word="" roman="manuscript" star="1"/>
  <Word word="" roman="owl" star="1"/>
  <Word word="" roman="mirth" star="1"/>
  <Word word="" roman="inability" star="1"/>
  <Word word="" roman="kite" star="1"/>
  <Word word="" roman="inflation" star="1"/>
  <Word word="" roman="intercept" star="1"/>
  <Word word="" roman="gerund" star="1"/>
  <Word word="" roman="ingredient" star="1"/>
  <Word word="" roman="mess" star="1"/>
  <Word word="" roman="pray" star="1"/>
  <Word word="" roman="narcotic" star="1"/>
  <Word word="" roman="playmate" star="1"/>
  <Word word="" roman="pure" star="1"/>
  <Word word="" roman="irregular" star="1"/>
  <Word word="" roman="mischief" star="1"/>
  <Word word="" roman="output" star="1"/>
  <Word word="" roman="prevail" star="1"/>
  <Word word="" roman="outer" star="1"/>
  <Word word="" roman="humanity" star="1"/>
  <Word word="" roman="nerve" star="1"/>
  <Word word="" roman="hearth" star="1"/>
  <Word word="" roman="nonsense" star="1"/>
  <Word word="" roman="gloom" star="1"/>
  <Word word="" roman="launch" star="1"/>
  <Word word="" roman="mission" star="1"/>
  <Word word="" roman="monarch" star="1"/>
  <Word word="" roman="poll" star="1"/>
  <Word word="" roman="hopeful" star="1"/>
  <Word word="" roman="nebula" star="1"/>
  <Word word="" roman="improve" star="1"/>
  <Word word="" roman="Netherlands" star="1"/>
  <Word word="" roman="innovation" star="1"/>
  <Word word="" roman="ignorant" star="1"/>
  <Word word="" roman="positive" star="1"/>
  <Word word="" roman="limb" star="1"/>
  <Word word="" roman="license" star="1"/>
  <Word word="" roman="pool" star="1"/>
  <Word word="" roman="grateful" star="1"/>
  <Word word="" roman="humble" star="1"/>
  <Word word="" roman="pace" star="1"/>
  <Word word="" roman="picturesque" star="1"/>
  <Word word="" roman="lighthouse" star="1"/>
  <Word word="" roman="magistrate" star="1"/>
  <Word word="" roman="mutual" star="1"/>
  <Word word="" roman="preside" star="1"/>
  <Word word="" roman="lately" star="1"/>
  <Word word="" roman="Gothic" star="1"/>
  <Word word="" roman="neighborhood" star="1"/>
  <Word word="" roman="multitude" star="1"/>
  <Word word="" roman="passport" star="1"/>
  <Word word="" roman="miserable" star="1"/>
  <Word word="" roman="manager" star="1"/>
  <Word word="" roman="hardware" star="1"/>
  <Word word="" roman="preface" star="1"/>
  <Word word="" roman="observation" star="1"/>
  <Word word="" roman="link" star="1"/>
  <Word word="" roman="harsh" star="1"/>
  <Word word="" roman="nostalgia" star="1"/>
  <Word word="" roman="misunderstand" star="1"/>
  <Word word="" roman="guidance" star="1"/>
  <Word word="" roman="implicit" star="1"/>
  <Word word="" roman="plasma" star="1"/>
  <Word word="" roman="porter" star="1"/>
  <Word word="" roman="mint" star="1"/>
  <Word word="" roman="namely" star="1"/>
  <Word word="" roman="peck" star="1"/>
  <Word word="" roman="goal" star="1"/>
  <Word word="" roman="noble" star="1"/>
  <Word word="" roman="prose" star="1"/>
  <Word word="" roman="lid" star="1"/>
  <Word word="" roman="mink" star="1"/>
  <Word word="" roman="isolation" star="1"/>
  <Word word="" roman="livelihood" star="1"/>
  <Word word="" roman="lessen" star="1"/>
  <Word word="" roman="moth" star="1"/>
  <Word word="" roman="homemade" star="1"/>
  <Word word="" roman="outlaw" star="1"/>
  <Word word="" roman="perseverance" star="1"/>
  <Word word="" roman="hippopotamus" star="1"/>
  <Word word="" roman="hero" star="1"/>
  <Word word="" roman="originate" star="1"/>
  <Word word="" roman="patch" star="1"/>
  <Word word="" roman="insight" star="1"/>
  <Word word="" roman="ply" star="1"/>
  <Word word="" roman="mentality" star="1"/>
  <Word word="" roman="motive" star="1"/>
  <Word word="" roman="grief" star="1"/>
  <Word word="" roman="handicap" star="1"/>
  <Word word="" roman="loiter" star="1"/>
  <Word word="" roman="occasional" star="1"/>
  <Word word="" roman="harvest" star="1"/>
  <Word word="" roman="pulse" star="1"/>
  <Word word="" roman="living" star="1"/>
  <Word word="" roman="good day" star="1"/>
  <Word word="" roman="malt" star="1"/>
  <Word word="" roman="indispensable" star="1"/>
  <Word word="" roman="grown" star="1"/>
  <Word word="" roman="pal" star="1"/>
  <Word word="" roman="hillside" star="1"/>
  <Word word="" roman="pleasing" star="1"/>
  <Word word="" roman="mouthpiece" star="1"/>
  <Word word="" roman="kneel" star="1"/>
  <Word word="" roman="kilometer" star="1"/>
  <Word word="" roman="negotiate" star="1"/>
  <Word word="" roman="mound" star="1"/>
  <Word word="" roman="mend" star="1"/>
  <Word word="" roman="industrious" star="1"/>
  <Word word="" roman="psalm" star="1"/>
  <Word word="" roman="pause" star="1"/>
  <Word word="" roman="jet plane" star="1"/>
  <Word word="" roman="geography" star="1"/>
  <Word word="" roman="novelty" star="1"/>
  <Word word="" roman="Indonesia" star="1"/>
  <Word word="" roman="lack" star="1"/>
  <Word word="" roman="pajamas" star="1"/>
  <Word word="" roman="laboratory" star="1"/>
  <Word word="" roman="luxury" star="1"/>
  <Word word="" roman="oval" star="1"/>
  <Word word="" roman="participate" star="1"/>
  <Word word="" roman="outline" star="1"/>
  <Word word="" roman="patron" star="1"/>
  <Word word="" roman="linen" star="1"/>
  <Word word="" roman="mosaic" star="1"/>
  <Word word="" roman="lane" star="1"/>
  <Word word="" roman="mood" star="1"/>
  <Word word="" roman="pedestrian" star="1"/>
  <Word word="" roman="optical" star="1"/>
  <Word word="" roman="grill" star="1"/>
  <Word word="" roman="principle" star="1"/>
  <Word word="" roman="plunge" star="1"/>
  <Word word="" roman="likeness" star="1"/>
  <Word word="" roman="primary" star="1"/>
  <Word word="" roman="interfere" star="1"/>
  <Word word="" roman="jug" star="1"/>
  <Word word="" roman="liquid" star="1"/>
  <Word word="" roman="infect" star="1"/>
  <Word word="" roman="prison" star="1"/>
  <Word word="" roman="hell" star="1"/>
  <Word word="" roman="poster" star="1"/>
  <Word word="" roman="lens" star="1"/>
  <Word word="" roman="immigrate" star="1"/>
  <Word word="" roman="meek" star="1"/>
  <Word word="" roman="petty" star="1"/>
  <Word word="" roman="knit" star="1"/>
  <Word word="" roman="hammer" star="1"/>
  <Word word="" roman="method" star="1"/>
  <Word word="" roman="pickup" star="1"/>
  <Word word="" roman="hateful" star="1"/>
  <Word word="" roman="prefer" star="1"/>
  <Word word="" roman="literary" star="1"/>
  <Word word="" roman="overhead" star="1"/>
  <Word word="" roman="gravity" star="1"/>
  <Word word="" roman="logical" star="1"/>
  <Word word="" roman="male" star="1"/>
  <Word word="" roman="Mary" star="1"/>
  <Word word="" roman="garment" star="1"/>
  <Word word="" roman="glorious" star="1"/>
  <Word word="" roman="pansy" star="1"/>
  <Word word="" roman="prefecture" star="1"/>
  <Word word="" roman="parasol" star="1"/>
  <Word word="" roman="physician" star="1"/>
  <Word word="" roman="preserve" star="1"/>
  <Word word="" roman="pole" star="1"/>
  <Word word="" roman="label" star="1"/>
  <Word word="" roman="intellect" star="1"/>
  <Word word="" roman="production" star="1"/>
  <Word word="" roman="intercourse" star="1"/>
  <Word word="" roman="jean" star="1"/>
  <Word word="" roman="pronounce" star="1"/>
  <Word word="" roman="prospect" star="1"/>
  <Word word="" roman="prolog" star="1"/>
  <Word word="" roman="preference" star="1"/>
  <Word word="" roman="plug" star="1"/>
  <Word word="" roman="joyful" star="1"/>
  <Word word="" roman="motor" star="1"/>
  <Word word="" roman="participle" star="1"/>
  <Word word="" roman="intrude" star="1"/>
  <Word word="" roman="polish" star="1"/>
  <Word word="" roman="handkerchief" star="1"/>
  <Word word="" roman="partly" star="1"/>
  <Word word="" roman="lodge" star="1"/>
  <Word word="" roman="punctual" star="1"/>
  <Word word="" roman="level" star="1"/>
  <Word word="" roman="lurk" star="1"/>
  <Word word="" roman="hardship" star="1"/>
  <Word word="" roman="perch" star="1"/>
  <Word word="" roman="modest" star="1"/>
  <Word word="" roman="lettuce" star="1"/>
  <Word word="" roman="landmark" star="1"/>
  <Word word="" roman="jerk" star="1"/>
  <Word word="" roman="maple" star="1"/>
  <Word word="" roman="hawk" star="1"/>
  <Word word="" roman="lean" star="1"/>
  <Word word="" roman="protein" star="1"/>
  <Word word="" roman="pollen" star="1"/>
  <Word word="" roman="proposition" star="1"/>
  <Word word="" roman="kingdom" star="1"/>
  <Word word="" roman="pavement" star="1"/>
  <Word word="" roman="pants" star="1"/>
  <Word word="" roman="peninsula" star="1"/>
  <Word word="" roman="neutral" star="1"/>
  <Word word="" roman="hitchhike" star="1"/>
  <Word word="" roman="professor" star="1"/>
  <Word word="" roman="hospitality" star="1"/>
  <Word word="" roman="purchase" star="1"/>
  <Word word="" roman="hut" star="1"/>
  <Word word="" roman="harm" star="1"/>
  <Word word="" roman="home run" star="1"/>
  <Word word="" roman="inflict" star="1"/>
  <Word word="" roman="luck" star="1"/>
  <Word word="" roman="memorial" star="1"/>
  <Word word="" roman="oyster" star="1"/>
  <Word word="" roman="giraffe" star="1"/>
  <Word word="" roman="pipe" star="1"/>
</Words>