<?xml version="1.0"?>
<Words xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Word word="" roman="walking" star="1"/>
  <Word word="" roman="summon" star="1"/>
  <Word word="" roman="slide" star="1"/>
  <Word word="" roman="resume" star="1"/>
  <Word word="" roman="recommendation" star="1"/>
  <Word word="" roman="territory" star="1"/>
  <Word word="" roman="usage" star="1"/>
  <Word word="" roman="workman" star="1"/>
  <Word word="" roman="wagon" star="1"/>
  <Word word="" roman="quiz" star="1"/>
  <Word word="" roman="sober" star="1"/>
  <Word word="" roman="trailer" star="1"/>
  <Word word="" roman="yearn" star="1"/>
  <Word word="" roman="suppress" star="1"/>
  <Word word="" roman="resign" star="1"/>
  <Word word="" roman="smuggle" star="1"/>
  <Word word="" roman="sum" star="1"/>
  <Word word="" roman="stimulate" star="1"/>
  <Word word="" roman="recycle" star="1"/>
  <Word word="" roman="successful" star="1"/>
  <Word word="" roman="robe" star="1"/>
  <Word word="" roman="worthless" star="1"/>
  <Word word="" roman="shrine" star="1"/>
  <Word word="" roman="reckon" star="1"/>
  <Word word="" roman="surgeon" star="1"/>
  <Word word="" roman="schoolmate" star="1"/>
  <Word word="" roman="sleigh" star="1"/>
  <Word word="" roman="stuck" star="1"/>
  <Word word="" roman="thanksgiving" star="1"/>
  <Word word="" roman="venture" star="1"/>
  <Word word="" roman="radiator" star="1"/>
  <Word word="" roman="reliable" star="1"/>
  <Word word="" roman="scratch" star="1"/>
  <Word word="" roman="treasury" star="1"/>
  <Word word="" roman="spider" star="1"/>
  <Word word="" roman="software" star="1"/>
  <Word word="" roman="worker" star="1"/>
  <Word word="" roman="scare" star="1"/>
  <Word word="" roman="synthetic" star="1"/>
  <Word word="" roman="reduce" star="1"/>
  <Word word="" roman="sickness" star="1"/>
  <Word word="" roman="shiver" star="1"/>
  <Word word="" roman="survival" star="1"/>
  <Word word="" roman="volleyball" star="1"/>
  <Word word="" roman="uphold" star="1"/>
  <Word word="" roman="sometime" star="1"/>
  <Word word="" roman="shortcoming" star="1"/>
  <Word word="" roman="subjection" star="1"/>
  <Word word="" roman="Venice" star="1"/>
  <Word word="" roman="rein" star="1"/>
  <Word word="" roman="rob" star="1"/>
  <Word word="" roman="rugged" star="1"/>
  <Word word="" roman="spaceman" star="1"/>
  <Word word="" roman="Red Cross" star="1"/>
  <Word word="" roman="ridden" star="1"/>
  <Word word="" roman="spit" star="1"/>
  <Word word="" roman="splendid" star="1"/>
  <Word word="" roman="vanity" star="1"/>
  <Word word="" roman="slogan" star="1"/>
  <Word word="" roman="triumph" star="1"/>
  <Word word="" roman="seal" star="1"/>
  <Word word="" roman="victor" star="1"/>
  <Word word="" roman="treat" star="1"/>
  <Word word="" roman="sergeant" star="1"/>
  <Word word="" roman="subsequent" star="1"/>
  <Word word="" roman="vapor" star="1"/>
  <Word word="" roman="springtime" star="1"/>
  <Word word="" roman="victory" star="1"/>
  <Word word="" roman="trump" star="1"/>
  <Word word="" roman="toast" star="1"/>
  <Word word="" roman="shriek" star="1"/>
  <Word word="" roman="steadily" star="1"/>
  <Word word="" roman="steam" star="1"/>
  <Word word="" roman="temporary" star="1"/>
  <Word word="" roman="reflect" star="1"/>
  <Word word="" roman="wrap" star="1"/>
  <Word word="" roman="tube" star="1"/>
  <Word word="" roman="waist" star="1"/>
  <Word word="" roman="whisper" star="1"/>
  <Word word="" roman="rustic" star="1"/>
  <Word word="" roman="tackle" star="1"/>
  <Word word="" roman="spruce" star="1"/>
  <Word word="" roman="spring" star="1"/>
  <Word word="" roman="Socrates" star="1"/>
  <Word word="" roman="typhoon" star="1"/>
  <Word word="" roman="queue" star="1"/>
  <Word word="" roman="simultaneous" star="1"/>
  <Word word="" roman="temperature" star="1"/>
  <Word word="" roman="weave" star="1"/>
  <Word word="" roman="unwilling" star="1"/>
  <Word word="" roman="softly" star="1"/>
  <Word word="" roman="slumber" star="1"/>
  <Word word="" roman="rally" star="1"/>
  <Word word="" roman="whale" star="1"/>
  <Word word="" roman="random" star="1"/>
  <Word word="" roman="trial" star="1"/>
  <Word word="" roman="thoughtful" star="1"/>
  <Word word="" roman="tried" star="1"/>
  <Word word="" roman="request" star="1"/>
  <Word word="" roman="stead" star="1"/>
  <Word word="" roman="revival" star="1"/>
  <Word word="" roman="vague" star="1"/>
  <Word word="" roman="sew" star="1"/>
  <Word word="" roman="revenue" star="1"/>
  <Word word="" roman="yearly" star="1"/>
  <Word word="" roman="tip" star="1"/>
  <Word word="" roman="submarine" star="1"/>
  <Word word="" roman="whistle" star="1"/>
  <Word word="" roman="remote" star="1"/>
  <Word word="" roman="scarlet" star="1"/>
  <Word word="" roman="sheriff" star="1"/>
  <Word word="" roman="screen" star="1"/>
  <Word word="" roman="typist" star="1"/>
  <Word word="" roman="sneeze" star="1"/>
  <Word word="" roman="soap" star="1"/>
  <Word word="" roman="recruit" star="1"/>
  <Word word="" roman="understanding" star="1"/>
  <Word word="" roman="requirement" star="1"/>
  <Word word="" roman="spire" star="1"/>
  <Word word="" roman="shrink" star="1"/>
  <Word word="" roman="strongly" star="1"/>
  <Word word="" roman="secretary" star="1"/>
  <Word word="" roman="wilderness" star="1"/>
  <Word word="" roman="spherical" star="1"/>
  <Word word="" roman="steep" star="1"/>
  <Word word="" roman="rotate" star="1"/>
  <Word word="" roman="San Francisco" star="1"/>
  <Word word="" roman="static" star="1"/>
  <Word word="" roman="species" star="1"/>
  <Word word="" roman="thereafter" star="1"/>
  <Word word="" roman="repay" star="1"/>
  <Word word="" roman="sought" star="1"/>
  <Word word="" roman="triple" star="1"/>
  <Word word="" roman="summarize" star="1"/>
  <Word word="" roman="scrape" star="1"/>
  <Word word="" roman="tattoo" star="1"/>
  <Word word="" roman="wounded" star="1"/>
  <Word word="" roman="recline" star="1"/>
  <Word word="" roman="trench" star="1"/>
  <Word word="" roman="spotlight" star="1"/>
  <Word word="" roman="seldom" star="1"/>
  <Word word="" roman="scream" star="1"/>
  <Word word="" roman="vulgar" star="1"/>
  <Word word="" roman="underneath" star="1"/>
  <Word word="" roman="thrust" star="1"/>
  <Word word="" roman="sailing" star="1"/>
  <Word word="" roman="sigh" star="1"/>
  <Word word="" roman="silently" star="1"/>
  <Word word="" roman="title" star="1"/>
  <Word word="" roman="violent" star="1"/>
  <Word word="" roman="subscribe" star="1"/>
  <Word word="" roman="rogue" star="1"/>
  <Word word="" roman="steel" star="1"/>
  <Word word="" roman="touching" star="1"/>
  <Word word="" roman="regarding" star="1"/>
  <Word word="" roman="squad" star="1"/>
  <Word word="" roman="silicon" star="1"/>
  <Word word="" roman="soar" star="1"/>
  <Word word="" roman="sulfur" star="1"/>
  <Word word="" roman="terrify" star="1"/>
  <Word word="" roman="suspicion" star="1"/>
  <Word word="" roman="rescue" star="1"/>
  <Word word="" roman="shutter" star="1"/>
  <Word word="" roman="syrup" star="1"/>
  <Word word="" roman="slang" star="1"/>
  <Word word="" roman="veranda" star="1"/>
  <Word word="" roman="tolerate" star="1"/>
  <Word word="" roman="singer" star="1"/>
  <Word word="" roman="universe" star="1"/>
  <Word word="" roman="stud" star="1"/>
  <Word word="" roman="U.S.A." star="1"/>
  <Word word="" roman="wore" star="1"/>
  <Word word="" roman="underwear" star="1"/>
  <Word word="" roman="quicken" star="1"/>
  <Word word="" roman="urgent" star="1"/>
  <Word word="" roman="sorrowful" star="1"/>
  <Word word="" roman="succession" star="1"/>
  <Word word="" roman="stalk" star="1"/>
  <Word word="" roman="tutor" star="1"/>
  <Word word="" roman="western" star="1"/>
  <Word word="" roman="transition" star="1"/>
  <Word word="" roman="swimming" star="1"/>
  <Word word="" roman="seventh" star="1"/>
  <Word word="" roman="stole" star="1"/>
  <Word word="" roman="sleeve" star="1"/>
  <Word word="" roman="variation" star="1"/>
  <Word word="" roman="respectable" star="1"/>
  <Word word="" roman="yard" star="1"/>
  <Word word="" roman="spinach" star="1"/>
  <Word word="" roman="sash" star="1"/>
  <Word word="" roman="radial" star="1"/>
  <Word word="" roman="weakness" star="1"/>
  <Word word="" roman="spike" star="1"/>
  <Word word="" roman="witch" star="1"/>
  <Word word="" roman="waste" star="1"/>
  <Word word="" roman="upper" star="1"/>
  <Word word="" roman="repel" star="1"/>
  <Word word="" roman="sweetheart" star="1"/>
  <Word word="" roman="topic" star="1"/>
  <Word word="" roman="sect" star="1"/>
  <Word word="" roman="retail" star="1"/>
  <Word word="" roman="tar" star="1"/>
  <Word word="" roman="salad" star="1"/>
  <Word word="" roman="tremble" star="1"/>
  <Word word="" roman="tongue" star="1"/>
  <Word word="" roman="wrist" star="1"/>
  <Word word="" roman="technology" star="1"/>
  <Word word="" roman="text" star="1"/>
  <Word word="" roman="query" star="1"/>
  <Word word="" roman="taint" star="1"/>
  <Word word="" roman="tune" star="1"/>
  <Word word="" roman="thrill" star="1"/>
  <Word word="" roman="rarely" star="1"/>
  <Word word="" roman="suggestion" star="1"/>
  <Word word="" roman="wharf" star="1"/>
  <Word word="" roman="wisdom" star="1"/>
  <Word word="" roman="reunion" star="1"/>
  <Word word="" roman="wept" star="1"/>
  <Word word="" roman="trance" star="1"/>
  <Word word="" roman="quench" star="1"/>
  <Word word="" roman="tramp" star="1"/>
  <Word word="" roman="replace" star="1"/>
  <Word word="" roman="shake" star="1"/>
  <Word word="" roman="shatter" star="1"/>
  <Word word="" roman="tropic" star="1"/>
  <Word word="" roman="wireless" star="1"/>
  <Word word="" roman="strenuous" star="1"/>
  <Word word="" roman="realism" star="1"/>
  <Word word="" roman="rear" star="1"/>
  <Word word="" roman="structural" star="1"/>
  <Word word="" roman="sharply" star="1"/>
  <Word word="" roman="trash" star="1"/>
  <Word word="" roman="respond" star="1"/>
  <Word word="" roman="westward" star="1"/>
  <Word word="" roman="quit" star="1"/>
  <Word word="" roman="snake" star="1"/>
  <Word word="" roman="wolves" star="1"/>
  <Word word="" roman="rebellion" star="1"/>
  <Word word="" roman="wither" star="1"/>
  <Word word="" roman="stiff" star="1"/>
  <Word word="" roman="relation" star="1"/>
  <Word word="" roman="seriously" star="1"/>
  <Word word="" roman="transparent" star="1"/>
  <Word word="" roman="ugly" star="1"/>
  <Word word="" roman="shortage" star="1"/>
  <Word word="" roman="social" star="1"/>
  <Word word="" roman="sole" star="1"/>
  <Word word="" roman="sword" star="1"/>
  <Word word="" roman="slain" star="1"/>
  <Word word="" roman="raccoon" star="1"/>
  <Word word="" roman="specialize" star="1"/>
  <Word word="" roman="toll" star="1"/>
  <Word word="" roman="rib" star="1"/>
  <Word word="" roman="wildly" star="1"/>
  <Word word="" roman="strap" star="1"/>
  <Word word="" roman="zigzag" star="1"/>
  <Word word="" roman="scroll" star="1"/>
  <Word word="" roman="shudder" star="1"/>
  <Word word="" roman="renown" star="1"/>
  <Word word="" roman="stable" star="1"/>
  <Word word="" roman="reign" star="1"/>
  <Word word="" roman="zero" star="1"/>
  <Word word="" roman="space travel" star="1"/>
  <Word word="" roman="tragic" star="1"/>
  <Word word="" roman="snatch" star="1"/>
  <Word word="" roman="torrent" star="1"/>
  <Word word="" roman="rode" star="1"/>
  <Word word="" roman="statue" star="1"/>
  <Word word="" roman="shelves" star="1"/>
  <Word word="" roman="stall" star="1"/>
  <Word word="" roman="ultimate" star="1"/>
  <Word word="" roman="snowball" star="1"/>
  <Word word="" roman="unhappy" star="1"/>
  <Word word="" roman="seminar" star="1"/>
  <Word word="" roman="span" star="1"/>
  <Word word="" roman="sandwich" star="1"/>
  <Word word="" roman="recommend" star="1"/>
  <Word word="" roman="similar" star="1"/>
  <Word word="" roman="simplicity" star="1"/>
  <Word word="" roman="subjective" star="1"/>
  <Word word="" roman="scarecrow" star="1"/>
  <Word word="" roman="slice" star="1"/>
  <Word word="" roman="swam" star="1"/>
  <Word word="" roman="reinforce" star="1"/>
  <Word word="" roman="rare" star="1"/>
  <Word word="" roman="rash" star="1"/>
  <Word word="" roman="upstairs" star="1"/>
  <Word word="" roman="steady" star="1"/>
  <Word word="" roman="reactor" star="1"/>
  <Word word="" roman="surface" star="1"/>
  <Word word="" roman="starvation" star="1"/>
  <Word word="" roman="sap" star="1"/>
  <Word word="" roman="widow" star="1"/>
  <Word word="" roman="throve" star="1"/>
  <Word word="" roman="seasonal" star="1"/>
  <Word word="" roman="sunlight" star="1"/>
  <Word word="" roman="youthful" star="1"/>
  <Word word="" roman="tram" star="1"/>
  <Word word="" roman="saddle" star="1"/>
  <Word word="" roman="simplify" star="1"/>
  <Word word="" roman="woke" star="1"/>
  <Word word="" roman="spectator" star="1"/>
  <Word word="" roman="spear" star="1"/>
  <Word word="" roman="throng" star="1"/>
  <Word word="" roman="waiting" star="1"/>
  <Word word="" roman="undergo" star="1"/>
  <Word word="" roman="react" star="1"/>
  <Word word="" roman="screw" star="1"/>
  <Word word="" roman="surpass" star="1"/>
  <Word word="" roman="strawberry" star="1"/>
  <Word word="" roman="sesame" star="1"/>
  <Word word="" roman="woe" star="1"/>
  <Word word="" roman="rayon" star="1"/>
  <Word word="" roman="sterling" star="1"/>
  <Word word="" roman="sprinkle" star="1"/>
  <Word word="" roman="synchronize" star="1"/>
  <Word word="" roman="tighten" star="1"/>
  <Word word="" roman="scale" star="1"/>
  <Word word="" roman="texture" star="1"/>
  <Word word="" roman="scan" star="1"/>
  <Word word="" roman="radiate" star="1"/>
  <Word word="" roman="shield" star="1"/>
  <Word word="" roman="revise" star="1"/>
  <Word word="" roman="rot" star="1"/>
  <Word word="" roman="unpleasant" star="1"/>
  <Word word="" roman="refer" star="1"/>
  <Word word="" roman="steer" star="1"/>
  <Word word="" roman="terrace" star="1"/>
  <Word word="" roman="user" star="1"/>
  <Word word="" roman="recorder" star="1"/>
  <Word word="" roman="situated" star="1"/>
  <Word word="" roman="slope" star="1"/>
  <Word word="" roman="slavery" star="1"/>
  <Word word="" roman="sperm" star="1"/>
  <Word word="" roman="sexual" star="1"/>
  <Word word="" roman="saint" star="1"/>
  <Word word="" roman="suffering" star="1"/>
  <Word word="" roman="whenever" star="1"/>
  <Word word="" roman="willing" star="1"/>
  <Word word="" roman="spite" star="1"/>
  <Word word="" roman="raid" star="1"/>
  <Word word="" roman="theory" star="1"/>
  <Word word="" roman="vast" star="1"/>
  <Word word="" roman="weapon" star="1"/>
  <Word word="" roman="wove" star="1"/>
  <Word word="" roman="tribute" star="1"/>
  <Word word="" roman="stake" star="1"/>
  <Word word="" roman="zoological" star="1"/>
  <Word word="" roman="reap" star="1"/>
  <Word word="" roman="respective" star="1"/>
  <Word word="" roman="trim" star="1"/>
  <Word word="" roman="thorn" star="1"/>
  <Word word="" roman="Thames" star="1"/>
  <Word word="" roman="shallow" star="1"/>
  <Word word="" roman="trample" star="1"/>
  <Word word="" roman="summit" star="1"/>
  <Word word="" roman="schedule" star="1"/>
  <Word word="" roman="saying" star="1"/>
  <Word word="" roman="superstition" star="1"/>
  <Word word="" roman="solve" star="1"/>
  <Word word="" roman="spine" star="1"/>
  <Word word="" roman="translation" star="1"/>
  <Word word="" roman="willow" star="1"/>
  <Word word="" roman="standing" star="1"/>
  <Word word="" roman="wardrobe" star="1"/>
  <Word word="" roman="sufferer" star="1"/>
  <Word word="" roman="slash" star="1"/>
  <Word word="" roman="tragedy" star="1"/>
  <Word word="" roman="simply" star="1"/>
  <Word word="" roman="rectangle" star="1"/>
  <Word word="" roman="reel" star="1"/>
  <Word word="" roman="tire" star="1"/>
  <Word word="" roman="seaman" star="1"/>
  <Word word="" roman="rhinoceros" star="1"/>
  <Word word="" roman="tax" star="1"/>
  <Word word="" roman="veil" star="1"/>
  <Word word="" roman="warn" star="1"/>
  <Word word="" roman="sore" star="1"/>
  <Word word="" roman="stoop" star="1"/>
  <Word word="" roman="scholar" star="1"/>
  <Word word="" roman="sally" star="1"/>
  <Word word="" roman="southeast" star="1"/>
  <Word word="" roman="ridge" star="1"/>
  <Word word="" roman="vertical" star="1"/>
  <Word word="" roman="status" star="1"/>
  <Word word="" roman="staff" star="1"/>
  <Word word="" roman="sped" star="1"/>
  <Word word="" roman="trousers" star="1"/>
  <Word word="" roman="terrific" star="1"/>
  <Word word="" roman="reside" star="1"/>
  <Word word="" roman="tour" star="1"/>
  <Word word="" roman="traveler" star="1"/>
  <Word word="" roman="wont" star="1"/>
  <Word word="" roman="recession" star="1"/>
  <Word word="" roman="sample" star="1"/>
  <Word word="" roman="shadow" star="1"/>
  <Word word="" roman="weaken" star="1"/>
  <Word word="" roman="sift" star="1"/>
  <Word word="" roman="wretched" star="1"/>
  <Word word="" roman="sandal" star="1"/>
  <Word word="" roman="rouse" star="1"/>
  <Word word="" roman="rifle" star="1"/>
  <Word word="" roman="suffice" star="1"/>
  <Word word="" roman="vacant" star="1"/>
  <Word word="" roman="worthy" star="1"/>
  <Word word="" roman="vicinity" star="1"/>
  <Word word="" roman="sculptor" star="1"/>
  <Word word="" roman="slipper" star="1"/>
  <Word word="" roman="zinc" star="1"/>
  <Word word="" roman="spaceship" star="1"/>
  <Word word="" roman="rust" star="1"/>
  <Word word="" roman="realm" star="1"/>
  <Word word="" roman="registration" star="1"/>
  <Word word="" roman="raw" star="1"/>
  <Word word="" roman="youngster" star="1"/>
  <Word word="" roman="sleepy" star="1"/>
  <Word word="" roman="stray" star="1"/>
  <Word word="" roman="raft" star="1"/>
  <Word word="" roman="racial" star="1"/>
  <Word word="" roman="wholly" star="1"/>
  <Word word="" roman="salary" star="1"/>
  <Word word="" roman="South America" star="1"/>
  <Word word="" roman="seize" star="1"/>
  <Word word="" roman="vote" star="1"/>
  <Word word="" roman="sculpture" star="1"/>
  <Word word="" roman="stereo" star="1"/>
  <Word word="" roman="wink" star="1"/>
  <Word word="" roman="statement" star="1"/>
  <Word word="" roman="restaurant" star="1"/>
  <Word word="" roman="witness" star="1"/>
  <Word word="" roman="tough" star="1"/>
  <Word word="" roman="threshold" star="1"/>
  <Word word="" roman="stance" star="1"/>
  <Word word="" roman="theme" star="1"/>
  <Word word="" roman="specific" star="1"/>
  <Word word="" roman="search" star="1"/>
  <Word word="" roman="tap" star="1"/>
  <Word word="" roman="wander" star="1"/>
  <Word word="" roman="shark" star="1"/>
  <Word word="" roman="upward" star="1"/>
  <Word word="" roman="we'd" star="1"/>
  <Word word="" roman="restrain" star="1"/>
  <Word word="" roman="tense" star="1"/>
  <Word word="" roman="thereupon" star="1"/>
  <Word word="" roman="startle" star="1"/>
  <Word word="" roman="unemployment" star="1"/>
  <Word word="" roman="stolen" star="1"/>
  <Word word="" roman="whoever" star="1"/>
  <Word word="" roman="rage" star="1"/>
  <Word word="" roman="spout" star="1"/>
  <Word word="" roman="stately" star="1"/>
  <Word word="" roman="trap" star="1"/>
  <Word word="" roman="truck" star="1"/>
  <Word word="" roman="row" star="1"/>
  <Word word="" roman="underline" star="1"/>
  <Word word="" roman="resolution" star="1"/>
  <Word word="" roman="stewardess" star="1"/>
  <Word word="" roman="recording" star="1"/>
  <Word word="" roman="wound" star="1"/>
  <Word word="" roman="repair" star="1"/>
  <Word word="" roman="Scotland" star="1"/>
  <Word word="" roman="talent" star="1"/>
  <Word word="" roman="rebel" star="1"/>
  <Word word="" roman="socialize" star="1"/>
  <Word word="" roman="tobacco" star="1"/>
  <Word word="" roman="trick" star="1"/>
  <Word word="" roman="secondary" star="1"/>
  <Word word="" roman="vary" star="1"/>
  <Word word="" roman="taboo" star="1"/>
  <Word word="" roman="towel" star="1"/>
  <Word word="" roman="spice" star="1"/>
  <Word word="" roman="weekday" star="1"/>
  <Word word="" roman="romance" star="1"/>
  <Word word="" roman="refreshment" star="1"/>
  <Word word="" roman="stuff" star="1"/>
  <Word word="" roman="suite" star="1"/>
  <Word word="" roman="syndicate" star="1"/>
  <Word word="" roman="spin" star="1"/>
  <Word word="" roman="snowy" star="1"/>
  <Word word="" roman="wedding" star="1"/>
  <Word word="" roman="seventeenth" star="1"/>
  <Word word="" roman="weekly" star="1"/>
  <Word word="" roman="tropical" star="1"/>
  <Word word="" roman="reserved" star="1"/>
  <Word word="" roman="wanting" star="1"/>
  <Word word="" roman="score" star="1"/>
  <Word word="" roman="subway" star="1"/>
  <Word word="" roman="reader" star="1"/>
  <Word word="" roman="war" star="1"/>
  <Word word="" roman="reject" star="1"/>
  <Word word="" roman="sequence" star="1"/>
  <Word word="" roman="uniform" star="1"/>
  <Word word="" roman="spiral" star="1"/>
  <Word word="" roman="scent" star="1"/>
  <Word word="" roman="terror" star="1"/>
  <Word word="" roman="tile" star="1"/>
  <Word word="" roman="rubbish" star="1"/>
  <Word word="" roman="restrict" star="1"/>
  <Word word="" roman="worn" star="1"/>
  <Word word="" roman="tremendous" star="1"/>
  <Word word="" roman="solitude" star="1"/>
  <Word word="" roman="space station" star="1"/>
  <Word word="" roman="tide" star="1"/>
  <Word word="" roman="renew" star="1"/>
  <Word word="" roman="wrinkle" star="1"/>
  <Word word="" roman="regardless" star="1"/>
  <Word word="" roman="reliance" star="1"/>
  <Word word="" roman="tub" star="1"/>
  <Word word="" roman="zealous" star="1"/>
  <Word word="" roman="stormy" star="1"/>
  <Word word="" roman="serpent" star="1"/>
  <Word word="" roman="strip" star="1"/>
  <Word word="" roman="waiter" star="1"/>
  <Word word="" roman="recognize" star="1"/>
  <Word word="" roman="shabby" star="1"/>
  <Word word="" roman="vault" star="1"/>
  <Word word="" roman="slaughter" star="1"/>
  <Word word="" roman="resource" star="1"/>
  <Word word="" roman="rejoice" star="1"/>
  <Word word="" roman="utter" star="1"/>
  <Word word="" roman="she'd" star="1"/>
  <Word word="" roman="vowel" star="1"/>
  <Word word="" roman="spray" star="1"/>
  <Word word="" roman="squire" star="1"/>
  <Word word="" roman="quake" star="1"/>
  <Word word="" roman="shelf" star="1"/>
  <Word word="" roman="ruler" star="1"/>
  <Word word="" roman="rent" star="1"/>
  <Word word="" roman="trustworthy" star="1"/>
  <Word word="" roman="spectacle" star="1"/>
  <Word word="" roman="telegraph" star="1"/>
  <Word word="" roman="strict" star="1"/>
  <Word word="" roman="suitcase" star="1"/>
  <Word word="" roman="regular" star="1"/>
  <Word word="" roman="specimen" star="1"/>
  <Word word="" roman="separation" star="1"/>
  <Word word="" roman="tribe" star="1"/>
  <Word word="" roman="twice" star="1"/>
  <Word word="" roman="unable" star="1"/>
  <Word word="" roman="spark" star="1"/>
  <Word word="" roman="vein" star="1"/>
  <Word word="" roman="skim" star="1"/>
  <Word word="" roman="ruin" star="1"/>
  <Word word="" roman="resin" star="1"/>
  <Word word="" roman="toil" star="1"/>
  <Word word="" roman="wizard" star="1"/>
  <Word word="" roman="sketch" star="1"/>
  <Word word="" roman="smoothly" star="1"/>
  <Word word="" roman="tick" star="1"/>
  <Word word="" roman="rocky" star="1"/>
  <Word word="" roman="southwest" star="1"/>
  <Word word="" roman="quest" star="1"/>
  <Word word="" roman="range" star="1"/>
  <Word word="" roman="tame" star="1"/>
  <Word word="" roman="responsible" star="1"/>
  <Word word="" roman="strand" star="1"/>
  <Word word="" roman="vine" star="1"/>
  <Word word="" roman="repeat" star="1"/>
  <Word word="" roman="sufficiently" star="1"/>
  <Word word="" roman="vile" star="1"/>
  <Word word="" roman="rumor" star="1"/>
  <Word word="" roman="reverse" star="1"/>
  <Word word="" roman="sincerely" star="1"/>
  <Word word="" roman="suspenders" star="1"/>
  <Word word="" roman="rhythm" star="1"/>
  <Word word="" roman="unseen" star="1"/>
  <Word word="" roman="timetable" star="1"/>
  <Word word="" roman="temperate" star="1"/>
  <Word word="" roman="tan" star="1"/>
  <Word word="" roman="wealthy" star="1"/>
  <Word word="" roman="stability" star="1"/>
  <Word word="" roman="rolling" star="1"/>
  <Word word="" roman="torn" star="1"/>
  <Word word="" roman="trumpet" star="1"/>
  <Word word="" roman="timely" star="1"/>
  <Word word="" roman="reward" star="1"/>
  <Word word="" roman="scout" star="1"/>
  <Word word="" roman="wicked" star="1"/>
  <Word word="" roman="tyrant" star="1"/>
  <Word word="" roman="religious" star="1"/>
  <Word word="" roman="skip" star="1"/>
  <Word word="" roman="splash" star="1"/>
  <Word word="" roman="realize" star="1"/>
  <Word word="" roman="sweater" star="1"/>
  <Word word="" roman="sheet" star="1"/>
  <Word word="" roman="traverse" star="1"/>
  <Word word="" roman="torch" star="1"/>
  <Word word="" roman="veteran" star="1"/>
  <Word word="" roman="tract" star="1"/>
  <Word word="" roman="stony" star="1"/>
  <Word word="" roman="woolen" star="1"/>
  <Word word="" roman="repent" star="1"/>
  <Word word="" roman="royalty" star="1"/>
  <Word word="" roman="temple" star="1"/>
  <Word word="" roman="slay" star="1"/>
  <Word word="" roman="rap" star="1"/>
  <Word word="" roman="tone" star="1"/>
  <Word word="" roman="steak" star="1"/>
  <Word word="" roman="turning" star="1"/>
  <Word word="" roman="vanish" star="1"/>
  <Word word="" roman="trust" star="1"/>
  <Word word="" roman="razor" star="1"/>
  <Word word="" roman="unlucky" star="1"/>
  <Word word="" roman="surrender" star="1"/>
  <Word word="" roman="vision" star="1"/>
  <Word word="" roman="regain" star="1"/>
  <Word word="" roman="safety" star="1"/>
  <Word word="" roman="Shakespeare" star="1"/>
  <Word word="" roman="smoking" star="1"/>
  <Word word="" roman="spokesman" star="1"/>
  <Word word="" roman="senator" star="1"/>
  <Word word="" roman="sensible" star="1"/>
  <Word word="" roman="recover" star="1"/>
  <Word word="" roman="scarcely" star="1"/>
  <Word word="" roman="silly" star="1"/>
  <Word word="" roman="straighten" star="1"/>
  <Word word="" roman="rag" star="1"/>
  <Word word="" roman="salmon" star="1"/>
  <Word word="" roman="salesman" star="1"/>
  <Word word="" roman="rental" star="1"/>
  <Word word="" roman="selfish" star="1"/>
  <Word word="" roman="troop" star="1"/>
  <Word word="" roman="spur" star="1"/>
  <Word word="" roman="talking" star="1"/>
  <Word word="" roman="superficial" star="1"/>
  <Word word="" roman="thread" star="1"/>
  <Word word="" roman="spade" star="1"/>
  <Word word="" roman="won" star="1"/>
  <Word word="" roman="recipe" star="1"/>
  <Word word="" roman="security" star="1"/>
  <Word word="" roman="steamship" star="1"/>
  <Word word="" roman="tore" star="1"/>
  <Word word="" roman="stumble" star="1"/>
  <Word word="" roman="sour" star="1"/>
  <Word word="" roman="suitable" star="1"/>
  <Word word="" roman="tease" star="1"/>
  <Word word="" roman="Switzerland" star="1"/>
  <Word word="" roman="rural" star="1"/>
  <Word word="" roman="sidewalk" star="1"/>
  <Word word="" roman="ratio" star="1"/>
  <Word word="" roman="successor" star="1"/>
  <Word word="" roman="tempest" star="1"/>
  <Word word="" roman="torture" star="1"/>
  <Word word="" roman="St." star="1"/>
  <Word word="" roman="specialist" star="1"/>
  <Word word="" roman="successfully" star="1"/>
  <Word word="" roman="revolution" star="1"/>
  <Word word="" roman="slate" star="1"/>
  <Word word="" roman="reality" star="1"/>
  <Word word="" roman="sip" star="1"/>
  <Word word="" roman="tariff" star="1"/>
  <Word word="" roman="struck" star="1"/>
  <Word word="" roman="surprising" star="1"/>
  <Word word="" roman="saving" star="1"/>
  <Word word="" roman="sightseeing" star="1"/>
  <Word word="" roman="responsibility" star="1"/>
  <Word word="" roman="suspense" star="1"/>
  <Word word="" roman="sparrow" star="1"/>
  <Word word="" roman="subdue" star="1"/>
  <Word word="" roman="zone" star="1"/>
  <Word word="" roman="seaport" star="1"/>
  <Word word="" roman="sway" star="1"/>
  <Word word="" roman="solitary" star="1"/>
  <Word word="" roman="roughly" star="1"/>
  <Word word="" roman="void" star="1"/>
  <Word word="" roman="quality" star="1"/>
  <Word word="" roman="quote" star="1"/>
  <Word word="" roman="whichever" star="1"/>
  <Word word="" roman="thirsty" star="1"/>
  <Word word="" roman="siege" star="1"/>
  <Word word="" roman="recess" star="1"/>
  <Word word="" roman="remarkable" star="1"/>
  <Word word="" roman="shampoo" star="1"/>
  <Word word="" roman="violet" star="1"/>
  <Word word="" roman="sparkle" star="1"/>
  <Word word="" roman="shrub" star="1"/>
  <Word word="" roman="response" star="1"/>
  <Word word="" roman="Satan" star="1"/>
  <Word word="" roman="rustle" star="1"/>
  <Word word="" roman="swift" star="1"/>
  <Word word="" roman="washing" star="1"/>
  <Word word="" roman="sensational" star="1"/>
  <Word word="" roman="shiny" star="1"/>
  <Word word="" roman="sink" star="1"/>
  <Word word="" roman="thirteenth" star="1"/>
  <Word word="" roman="straw" star="1"/>
  <Word word="" roman="specially" star="1"/>
  <Word word="" roman="significance" star="1"/>
  <Word word="" roman="schoolmaster" star="1"/>
  <Word word="" roman="shot" star="1"/>
  <Word word="" roman="symptom" star="1"/>
  <Word word="" roman="reduction" star="1"/>
  <Word word="" roman="switch" star="1"/>
  <Word word="" roman="survey" star="1"/>
  <Word word="" roman="saloon" star="1"/>
  <Word word="" roman="slender" star="1"/>
  <Word word="" roman="sown" star="1"/>
  <Word word="" roman="tradition" star="1"/>
  <Word word="" roman="strategy" star="1"/>
  <Word word="" roman="region" star="1"/>
  <Word word="" roman="relative" star="1"/>
  <Word word="" roman="repetition" star="1"/>
  <Word word="" roman="selective" star="1"/>
  <Word word="" roman="swung" star="1"/>
  <Word word="" roman="subsidiary" star="1"/>
  <Word word="" roman="recent" star="1"/>
  <Word word="" roman="recite" star="1"/>
  <Word word="" roman="sensitive" star="1"/>
  <Word word="" roman="unknown" star="1"/>
  <Word word="" roman="riot" star="1"/>
  <Word word="" roman="sack" star="1"/>
  <Word word="" roman="vicious" star="1"/>
  <Word word="" roman="smelt" star="1"/>
  <Word word="" roman="strait" star="1"/>
  <Word word="" roman="seaweed" star="1"/>
  <Word word="" roman="trot" star="1"/>
  <Word word="" roman="tight" star="1"/>
  <Word word="" roman="zoology" star="1"/>
  <Word word="" roman="rug" star="1"/>
  <Word word="" roman="windy" star="1"/>
  <Word word="" roman="staircase" star="1"/>
  <Word word="" roman="technique" star="1"/>
  <Word word="" roman="vitamin" star="1"/>
  <Word word="" roman="substitute" star="1"/>
  <Word word="" roman="virtue" star="1"/>
  <Word word="" roman="slim" star="1"/>
  <Word word="" roman="signify" star="1"/>
  <Word word="" roman="thumb" star="1"/>
  <Word word="" roman="reception" star="1"/>
  <Word word="" roman="retain" star="1"/>
  <Word word="" roman="they'll" star="1"/>
  <Word word="" roman="squat" star="1"/>
  <Word word="" roman="Sweden" star="1"/>
  <Word word="" roman="uncover" star="1"/>
  <Word word="" roman="vigorous" star="1"/>
  <Word word="" roman="whip" star="1"/>
  <Word word="" roman="scramble" star="1"/>
  <Word word="" roman="tale" star="1"/>
  <Word word="" roman="subtle" star="1"/>
  <Word word="" roman="underground" star="1"/>
  <Word word="" roman="slit" star="1"/>
  <Word word="" roman="slap" star="1"/>
  <Word word="" roman="Russian" star="1"/>
  <Word word="" roman="socialist" star="1"/>
  <Word word="" roman="tournament" star="1"/>
  <Word word="" roman="refusal" star="1"/>
  <Word word="" roman="resist" star="1"/>
  <Word word="" roman="suck" star="1"/>
  <Word word="" roman="substitution" star="1"/>
  <Word word="" roman="teller" star="1"/>
  <Word word="" roman="stool" star="1"/>
  <Word word="" roman="steamer" star="1"/>
  <Word word="" roman="revolt" star="1"/>
  <Word word="" roman="United Nations" star="1"/>
  <Word word="" roman="striking" star="1"/>
  <Word word="" roman="route" star="1"/>
  <Word word="" roman="reproach" star="1"/>
  <Word word="" roman="syntax" star="1"/>
  <Word word="" roman="qualify" star="1"/>
  <Word word="" roman="wine" star="1"/>
  <Word word="" roman="trunk" star="1"/>
  <Word word="" roman="sweeping" star="1"/>
  <Word word="" roman="via" star="1"/>
  <Word word="" roman="stew" star="1"/>
  <Word word="" roman="warmth" star="1"/>
  <Word word="" roman="spontaneous" star="1"/>
  <Word word="" roman="rub" star="1"/>
  <Word word="" roman="sauce" star="1"/>
  <Word word="" roman="transport" star="1"/>
  <Word word="" roman="soothe" star="1"/>
  <Word word="" roman="spoon" star="1"/>
  <Word word="" roman="spaghetti" star="1"/>
  <Word word="" roman="release" star="1"/>
  <Word word="" roman="sweetly" star="1"/>
  <Word word="" roman="violate" star="1"/>
  <Word word="" roman="timing" star="1"/>
  <Word word="" roman="temptation" star="1"/>
  <Word word="" roman="roan" star="1"/>
  <Word word="" roman="stomach" star="1"/>
  <Word word="" roman="shortly" star="1"/>
  <Word word="" roman="stretch" star="1"/>
  <Word word="" roman="unique" star="1"/>
  <Word word="" roman="session" star="1"/>
  <Word word="" roman="whereas" star="1"/>
  <Word word="" roman="scanty" star="1"/>
  <Word word="" roman="symbolic" star="1"/>
  <Word word="" roman="sunrise" star="1"/>
  <Word word="" roman="reserve" star="1"/>
  <Word word="" roman="sovereign" star="1"/>
  <Word word="" roman="utilize" star="1"/>
  <Word word="" roman="supervise" star="1"/>
  <Word word="" roman="Swiss" star="1"/>
  <Word word="" roman="sensation" star="1"/>
  <Word word="" roman="stagger" star="1"/>
  <Word word="" roman="robber" star="1"/>
  <Word word="" roman="spare" star="1"/>
  <Word word="" roman="stripe" star="1"/>
  <Word word="" roman="tactics" star="1"/>
  <Word word="" roman="yonder" star="1"/>
  <Word word="" roman="whatever" star="1"/>
  <Word word="" roman="supplicate" star="1"/>
  <Word word="" roman="residence" star="1"/>
  <Word word="" roman="streamer" star="1"/>
  <Word word="" roman="weed" star="1"/>
  <Word word="" roman="rid" star="1"/>
  <Word word="" roman="ward" star="1"/>
  <Word word="" roman="scorch" star="1"/>
  <Word word="" roman="rum" star="1"/>
  <Word word="" roman="savage" star="1"/>
  <Word word="" roman="reef" star="1"/>
  <Word word="" roman="severe" star="1"/>
  <Word word="" roman="risk" star="1"/>
  <Word word="" roman="thigh" star="1"/>
  <Word word="" roman="worm" star="1"/>
  <Word word="" roman="vocabulary" star="1"/>
  <Word word="" roman="sucker" star="1"/>
  <Word word="" roman="rod" star="1"/>
  <Word word="" roman="unity" star="1"/>
  <Word word="" roman="scrap" star="1"/>
  <Word word="" roman="siphon" star="1"/>
  <Word word="" roman="sod" star="1"/>
  <Word word="" roman="stain" star="1"/>
  <Word word="" roman="speaker" star="1"/>
  <Word word="" roman="sieve" star="1"/>
  <Word word="" roman="rail" star="1"/>
  <Word word="" roman="spell" star="1"/>
  <Word word="" roman="TV" star="1"/>
  <Word word="" roman="shorten" star="1"/>
  <Word word="" roman="seaside" star="1"/>
  <Word word="" roman="singing" star="1"/>
  <Word word="" roman="sixtieth" star="1"/>
  <Word word="" roman="wax" star="1"/>
  <Word word="" roman="tuck" star="1"/>
  <Word word="" roman="swallow" star="1"/>
  <Word word="" roman="volcano" star="1"/>
  <Word word="" roman="shell" star="1"/>
  <Word word="" roman="secure" star="1"/>
  <Word word="" roman="swum" star="1"/>
  <Word word="" roman="stubborn" star="1"/>
  <Word word="" roman="shave" star="1"/>
  <Word word="" roman="unfortunately" star="1"/>
  <Word word="" roman="wheel" star="1"/>
  <Word word="" roman="sweat" star="1"/>
  <Word word="" roman="shy" star="1"/>
  <Word word="" roman="token" star="1"/>
  <Word word="" roman="slave" star="1"/>
  <Word word="" roman="rational" star="1"/>
  <Word word="" roman="tug" star="1"/>
  <Word word="" roman="superior" star="1"/>
  <Word word="" roman="tray" star="1"/>
  <Word word="" roman="violin" star="1"/>
  <Word word="" roman="stroke" star="1"/>
  <Word word="" roman="speculation" star="1"/>
  <Word word="" roman="suspend" star="1"/>
  <Word word="" roman="rascal" star="1"/>
  <Word word="" roman="revive" star="1"/>
  <Word word="" roman="sacrifice" star="1"/>
  <Word word="" roman="suffix" star="1"/>
  <Word word="" roman="Singapore" star="1"/>
  <Word word="" roman="ritual" star="1"/>
  <Word word="" roman="Scotch" star="1"/>
  <Word word="" roman="tyranny" star="1"/>
  <Word word="" roman="sponge" star="1"/>
  <Word word="" roman="resort" star="1"/>
  <Word word="" roman="remind" star="1"/>
  <Word word="" roman="ware" star="1"/>
  <Word word="" roman="shaken" star="1"/>
  <Word word="" roman="warrior" star="1"/>
  <Word word="" roman="yield" star="1"/>
  <Word word="" roman="sow" star="1"/>
  <Word word="" roman="vest" star="1"/>
  <Word word="" roman="storage" star="1"/>
  <Word word="" roman="wives" star="1"/>
  <Word word="" roman="tedious" star="1"/>
  <Word word="" roman="soil" star="1"/>
  <Word word="" roman="suburb" star="1"/>
  <Word word="" roman="sensibility" star="1"/>
  <Word word="" roman="sanitary" star="1"/>
  <Word word="" roman="review" star="1"/>
  <Word word="" roman="resident" star="1"/>
  <Word word="" roman="repose" star="1"/>
  <Word word="" roman="sympathetic" star="1"/>
  <Word word="" roman="warship" star="1"/>
  <Word word="" roman="stranger" star="1"/>
  <Word word="" roman="umpire" star="1"/>
  <Word word="" roman="reckless" star="1"/>
  <Word word="" roman="surround" star="1"/>
  <Word word="" roman="rat" star="1"/>
  <Word word="" roman="satellite" star="1"/>
  <Word word="" roman="weary" star="1"/>
  <Word word="" roman="smog" star="1"/>
  <Word word="" roman="unaccountable" star="1"/>
  <Word word="" roman="secretly" star="1"/>
  <Word word="" roman="tendency" star="1"/>
  <Word word="" roman="souvenir" star="1"/>
  <Word word="" roman="select" star="1"/>
  <Word word="" roman="ridiculous" star="1"/>
  <Word word="" roman="synonym" star="1"/>
  <Word word="" roman="stationery" star="1"/>
  <Word word="" roman="symphony" star="1"/>
  <Word word="" roman="script" star="1"/>
  <Word word="" roman="vex" star="1"/>
  <Word word="" roman="streetcar" star="1"/>
  <Word word="" roman="tail" star="1"/>
  <Word word="" roman="secondhand" star="1"/>
  <Word word="" roman="soup" star="1"/>
  <Word word="" roman="trophy" star="1"/>
  <Word word="" roman="slight" star="1"/>
  <Word word="" roman="surgery" star="1"/>
  <Word word="" roman="radius" star="1"/>
  <Word word="" roman="smart" star="1"/>
  <Word word="" roman="ruby" star="1"/>
  <Word word="" roman="self" star="1"/>
  <Word word="" roman="reconcile" star="1"/>
  <Word word="" roman="revolutionary" star="1"/>
  <Word word="" roman="shooting" star="1"/>
  <Word word="" roman="trifling" star="1"/>
  <Word word="" roman="shorthand" star="1"/>
  <Word word="" roman="stack" star="1"/>
  <Word word="" roman="singular" star="1"/>
  <Word word="" roman="reconstruct" star="1"/>
  <Word word="" roman="separate" star="1"/>
  <Word word="" roman="worldly" star="1"/>
  <Word word="" roman="shower" star="1"/>
  <Word word="" roman="swirl" star="1"/>
  <Word word="" roman="semicolon" star="1"/>
  <Word word="" roman="varied" star="1"/>
  <Word word="" roman="verb" star="1"/>
  <Word word="" roman="whisky" star="1"/>
  <Word word="" roman="severely" star="1"/>
  <Word word="" roman="victim" star="1"/>
  <Word word="" roman="sock" star="1"/>
  <Word word="" roman="tunnel" star="1"/>
  <Word word="" roman="rip" star="1"/>
  <Word word="" roman="tidy" star="1"/>
  <Word word="" roman="stammer" star="1"/>
  <Word word="" roman="they'd" star="1"/>
  <Word word="" roman="signature" star="1"/>
  <Word word="" roman="swoon" star="1"/>
  <Word word="" roman="sympathize" star="1"/>
  <Word word="" roman="thoroughly" star="1"/>
  <Word word="" roman="socket" star="1"/>
  <Word word="" roman="sentiment" star="1"/>
  <Word word="" roman="subsistence" star="1"/>
  <Word word="" roman="shortsighted" star="1"/>
  <Word word="" roman="suspicious" star="1"/>
  <Word word="" roman="quilt" star="1"/>
  <Word word="" roman="skill" star="1"/>
  <Word word="" roman="undertake" star="1"/>
  <Word word="" roman="raindrop" star="1"/>
  <Word word="" roman="vessel" star="1"/>
  <Word word="" roman="swear" star="1"/>
  <Word word="" roman="scope" star="1"/>
  <Word word="" roman="rapture" star="1"/>
  <Word word="" roman="refugee" star="1"/>
  <Word word="" roman="unnatural" star="1"/>
  <Word word="" roman="symbol" star="1"/>
  <Word word="" roman="site" star="1"/>
  <Word word="" roman="stump" star="1"/>
  <Word word="" roman="thereby" star="1"/>
  <Word word="" roman="thirst" star="1"/>
  <Word word="" roman="unfortunate" star="1"/>
  <Word word="" roman="readily" star="1"/>
  <Word word="" roman="shocking" star="1"/>
  <Word word="" roman="tablecloth" star="1"/>
  <Word word="" roman="riches" star="1"/>
  <Word word="" roman="upright" star="1"/>
  <Word word="" roman="shipping" star="1"/>
  <Word word="" roman="tortoise" star="1"/>
  <Word word="" roman="referee" star="1"/>
  <Word word="" roman="urban" star="1"/>
  <Word word="" roman="suspect" star="1"/>
  <Word word="" roman="solo" star="1"/>
  <Word word="" roman="rude" star="1"/>
  <Word word="" roman="rubber" star="1"/>
  <Word word="" roman="sob" star="1"/>
  <Word word="" roman="solemn" star="1"/>
  <Word word="" roman="undertaking" star="1"/>
  <Word word="" roman="skirt" star="1"/>
  <Word word="" roman="working" star="1"/>
  <Word word="" roman="slam" star="1"/>
  <Word word="" roman="theft" star="1"/>
  <Word word="" roman="tread" star="1"/>
  <Word word="" roman="soda" star="1"/>
  <Word word="" roman="teaspoon" star="1"/>
  <Word word="" roman="shuffle" star="1"/>
  <Word word="" roman="vacuum" star="1"/>
  <Word word="" roman="target" star="1"/>
  <Word word="" roman="scorn" star="1"/>
  <Word word="" roman="upset" star="1"/>
  <Word word="" roman="studio" star="1"/>
  <Word word="" roman="typical" star="1"/>
  <Word word="" roman="shilling" star="1"/>
  <Word word="" roman="shift" star="1"/>
  <Word word="" roman="religion" star="1"/>
  <Word word="" roman="superstitious" star="1"/>
  <Word word="" roman="serious" star="1"/>
  <Word word="" roman="stroll" star="1"/>
  <Word word="" roman="soften" star="1"/>
  <Word word="" roman="stricken" star="1"/>
  <Word word="" roman="settlement" star="1"/>
  <Word word="" roman="royal" star="1"/>
  <Word word="" roman="tranquil" star="1"/>
  <Word word="" roman="vain" star="1"/>
  <Word word="" roman="snail" star="1"/>
  <Word word="" roman="translate" star="1"/>
  <Word word="" roman="schoolhouse" star="1"/>
  <Word word="" roman="wig" star="1"/>
  <Word word="" roman="reputation" star="1"/>
  <Word word="" roman="refined" star="1"/>
  <Word word="" roman="shaggy" star="1"/>
  <Word word="" roman="rattle" star="1"/>
  <Word word="" roman="root" star="1"/>
  <Word word="" roman="serene" star="1"/>
  <Word word="" roman="swarm" star="1"/>
  <Word word="" roman="resemble" star="1"/>
  <Word word="" roman="treaty" star="1"/>
  <Word word="" roman="sportsman" star="1"/>
  <Word word="" roman="Spain" star="1"/>
  <Word word="" roman="southern" star="1"/>
  <Word word="" roman="undoubtedly" star="1"/>
  <Word word="" roman="spoil" star="1"/>
  <Word word="" roman="weekend" star="1"/>
  <Word word="" roman="radish" star="1"/>
  <Word word="" roman="smash" star="1"/>
  <Word word="" roman="windmill" star="1"/>
  <Word word="" roman="ventilation" star="1"/>
  <Word word="" roman="succeed" star="1"/>
  <Word word="" roman="vocal" star="1"/>
  <Word word="" roman="ready-made" star="1"/>
  <Word word="" roman="term" star="1"/>
  <Word word="" roman="sphere" star="1"/>
  <Word word="" roman="render" star="1"/>
  <Word word="" roman="radar" star="1"/>
  <Word word="" roman="throne" star="1"/>
  <Word word="" roman="radical" star="1"/>
  <Word word="" roman="survive" star="1"/>
  <Word word="" roman="voyage" star="1"/>
  <Word word="" roman="unnecessary" star="1"/>
  <Word word="" roman="warrant" star="1"/>
  <Word word="" roman="tomato" star="1"/>
  <Word word="" roman="Saturn" star="1"/>
  <Word word="" roman="smack" star="1"/>
  <Word word="" roman="vengeance" star="1"/>
  <Word word="" roman="snap" star="1"/>
  <Word word="" roman="vow" star="1"/>
  <Word word="" roman="reluctant" star="1"/>
  <Word word="" roman="swamp" star="1"/>
  <Word word="" roman="zeal" star="1"/>
  <Word word="" roman="soprano" star="1"/>
  <Word word="" roman="snuff" star="1"/>
  <Word word="" roman="supreme" star="1"/>
  <Word word="" roman="sadness" star="1"/>
  <Word word="" roman="reform" star="1"/>
  <Word word="" roman="representation" star="1"/>
  <Word word="" roman="thief" star="1"/>
  <Word word="" roman="ragged" star="1"/>
  <Word word="" roman="rheumatism" star="1"/>
  <Word word="" roman="rang" star="1"/>
  <Word word="" roman="research" star="1"/>
  <Word word="" roman="slip" star="1"/>
  <Word word="" roman="unexpected" star="1"/>
  <Word word="" roman="uneasy" star="1"/>
  <Word word="" roman="thicket" star="1"/>
  <Word word="" roman="seller" star="1"/>
  <Word word="" roman="reflection" star="1"/>
  <Word word="" roman="refuge" star="1"/>
  <Word word="" roman="toss" star="1"/>
  <Word word="" roman="swept" star="1"/>
  <Word word="" roman="throughout" star="1"/>
  <Word word="" roman="stock" star="1"/>
  <Word word="" roman="split" star="1"/>
  <Word word="" roman="themselves" star="1"/>
  <Word word="" roman="removal" star="1"/>
  <Word word="" roman="trifle" star="1"/>
  <Word word="" roman="recognition" star="1"/>
  <Word word="" roman="sin" star="1"/>
  <Word word="" roman="slowdown" star="1"/>
  <Word word="" roman="stomachache" star="1"/>
  <Word word="" roman="raincoat" star="1"/>
  <Word word="" roman="who's" star="1"/>
  <Word word="" roman="trigger" star="1"/>
  <Word word="" roman="sustain" star="1"/>
  <Word word="" roman="standard" star="1"/>
  <Word word="" roman="section" star="1"/>
  <Word word="" roman="splendor" star="1"/>
  <Word word="" roman="strengthen" star="1"/>
  <Word word="" roman="silhouette" star="1"/>
  <Word word="" roman="sofa" star="1"/>
  <Word word="" roman="tiptoe" star="1"/>
  <Word word="" roman="sniff" star="1"/>
  <Word word="" roman="refrain" star="1"/>
  <Word word="" roman="United Kingdom" star="1"/>
  <Word word="" roman="somber" star="1"/>
  <Word word="" roman="rapid" star="1"/>
  <Word word="" roman="summary" star="1"/>
  <Word word="" roman="traveling" star="1"/>
  <Word word="" roman="so-called" star="1"/>
  <Word word="" roman="ribbon" star="1"/>
  <Word word="" roman="transfer" star="1"/>
  <Word word="" roman="writer" star="1"/>
  <Word word="" roman="voluntary" star="1"/>
  <Word word="" roman="rosy" star="1"/>
  <Word word="" roman="restless" star="1"/>
  <Word word="" roman="sadly" star="1"/>
  <Word word="" roman="sunbeam" star="1"/>
  <Word word="" roman="useless" star="1"/>
  <Word word="" roman="trimming" star="1"/>
  <Word word="" roman="tomb" star="1"/>
  <Word word="" roman="sled" star="1"/>
  <Word word="" roman="they've" star="1"/>
  <Word word="" roman="submission" star="1"/>
  <Word word="" roman="youth" star="1"/>
  <Word word="" roman="turtle" star="1"/>
  <Word word="" roman="yell" star="1"/>
  <Word word="" roman="worship" star="1"/>
  <Word word="" roman="quantity" star="1"/>
  <Word word="" roman="salvage" star="1"/>
  <Word word="" roman="solution" star="1"/>
  <Word word="" roman="strangely" star="1"/>
  <Word word="" roman="style" star="1"/>
  <Word word="" roman="tin" star="1"/>
  <Word word="" roman="wheat" star="1"/>
  <Word word="" roman="relic" star="1"/>
  <Word word="" roman="selection" star="1"/>
  <Word word="" roman="rival" star="1"/>
  <Word word="" roman="scheme" star="1"/>
  <Word word="" roman="well-known" star="1"/>
  <Word word="" roman="rely" star="1"/>
  <Word word="" roman="restore" star="1"/>
  <Word word="" roman="umbrella" star="1"/>
  <Word word="" roman="tag" star="1"/>
  <Word word="" roman="ruling" star="1"/>
  <Word word="" roman="withdraw" star="1"/>
  <Word word="" roman="quaint" star="1"/>
  <Word word="" roman="trend" star="1"/>
  <Word word="" roman="spawn" star="1"/>
  <Word word="" roman="yacht" star="1"/>
  <Word word="" roman="rapidly" star="1"/>
  <Word word="" roman="thrice" star="1"/>
  <Word word="" roman="vibrate" star="1"/>
  <Word word="" roman="Wales" star="1"/>
  <Word word="" roman="realistic" star="1"/>
  <Word word="" roman="zip code" star="1"/>
  <Word word="" roman="swollen" star="1"/>
  <Word word="" roman="rake" star="1"/>
  <Word word="" roman="truly" star="1"/>
  <Word word="" roman="ratify" star="1"/>
  <Word word="" roman="total" star="1"/>
  <Word word="" roman="scarce" star="1"/>
  <Word word="" roman="unkind" star="1"/>
  <Word word="" roman="setup" star="1"/>
  <Word word="" roman="swiftly" star="1"/>
  <Word word="" roman="variety" star="1"/>
  <Word word="" roman="technical" star="1"/>
  <Word word="" roman="tint" star="1"/>
  <Word word="" roman="unworthy" star="1"/>
  <Word word="" roman="secrecy" star="1"/>
  <Word word="" roman="Russia" star="1"/>
  <Word word="" roman="stout" star="1"/>
  <Word word="" roman="relax" star="1"/>
  <Word word="" roman="statesman" star="1"/>
  <Word word="" roman="toe" star="1"/>
  <Word word="" roman="sympathy" star="1"/>
  <Word word="" roman="strife" star="1"/>
  <Word word="" roman="waterfall" star="1"/>
  <Word word="" roman="seam" star="1"/>
  <Word word="" roman="testify" star="1"/>
  <Word word="" roman="thrive" star="1"/>
  <Word word="" roman="yawn" star="1"/>
  <Word word="" roman="rainfall" star="1"/>
  <Word word="" roman="setting" star="1"/>
  <Word word="" roman="valve" star="1"/>
  <Word word="" roman="stern" star="1"/>
  <Word word="" roman="threat" star="1"/>
  <Word word="" roman="stare" star="1"/>
  <Word word="" roman="symbolize" star="1"/>
  <Word word="" roman="twig" star="1"/>
  <Word word="" roman="simmer" star="1"/>
  <Word word="" roman="sapphire" star="1"/>
  <Word word="" roman="threaten" star="1"/>
  <Word word="" roman="revolve" star="1"/>
  <Word word="" roman="unlike" star="1"/>
  <Word word="" roman="starch" star="1"/>
  <Word word="" roman="republic" star="1"/>
  <Word word="" roman="roam" star="1"/>
  <Word word="" roman="stem" star="1"/>
  <Word word="" roman="tissue" star="1"/>
  <Word word="" roman="queer" star="1"/>
  <Word word="" roman="raisin" star="1"/>
  <Word word="" roman="tumble" star="1"/>
  <Word word="" roman="sufficient" star="1"/>
  <Word word="" roman="society" star="1"/>
  <Word word="" roman="reaction" star="1"/>
  <Word word="" roman="shovel" star="1"/>
  <Word word="" roman="quotation" star="1"/>
  <Word word="" roman="ton" star="1"/>
  <Word word="" roman="recollect" star="1"/>
  <Word word="" roman="resolve" star="1"/>
  <Word word="" roman="velvet" star="1"/>
  <Word word="" roman="recently" star="1"/>
  <Word word="" roman="segment" star="1"/>
  <Word word="" roman="update" star="1"/>
  <Word word="" roman="robin" star="1"/>
  <Word word="" roman="senior" star="1"/>
  <Word word="" roman="treatment" star="1"/>
  <Word word="" roman="supermarket" star="1"/>
  <Word word="" roman="strategic" star="1"/>
  <Word word="" roman="wade" star="1"/>
  <Word word="" roman="stigma" star="1"/>
  <Word word="" roman="telescope" star="1"/>
  <Word word="" roman="training" star="1"/>
  <Word word="" roman="woodland" star="1"/>
  <Word word="" roman="skylark" star="1"/>
  <Word word="" roman="sunburn" star="1"/>
  <Word word="" roman="twist" star="1"/>
  <Word word="" roman="spy" star="1"/>
  <Word word="" roman="torment" star="1"/>
  <Word word="" roman="subside" star="1"/>
  <Word word="" roman="refine" star="1"/>
  <Word word="" roman="swell" star="1"/>
  <Word word="" roman="temper" star="1"/>
  <Word word="" roman="weigh" star="1"/>
  <Word word="" roman="scoop" star="1"/>
  <Word word="" roman="sex" star="1"/>
  <Word word="" roman="volunteer" star="1"/>
  <Word word="" roman="sly" star="1"/>
  <Word word="" roman="tend" star="1"/>
  <Word word="" roman="stocking" star="1"/>
  <Word word="" roman="settler" star="1"/>
  <Word word="" roman="server" star="1"/>
  <Word word="" roman="streak" star="1"/>
  <Word word="" roman="running" star="1"/>
  <Word word="" roman="scissors" star="1"/>
  <Word word="" roman="sermon" star="1"/>
  <Word word="" roman="smooth" star="1"/>
  <Word word="" roman="secular" star="1"/>
  <Word word="" roman="urge" star="1"/>
  <Word word="" roman="sweep" star="1"/>
  <Word word="" roman="scatter" star="1"/>
  <Word word="" roman="web" star="1"/>
  <Word word="" roman="uncomfortable" star="1"/>
  <Word word="" roman="suspension" star="1"/>
  <Word word="" roman="schoolroom" star="1"/>
  <Word word="" roman="uncertain" star="1"/>
  <Word word="" roman="surrounding" star="1"/>
  <Word word="" roman="remembrance" star="1"/>
  <Word word="" roman="sheer" star="1"/>
  <Word word="" roman="width" star="1"/>
  <Word word="" roman="sportsmanship" star="1"/>
  <Word word="" roman="revenge" star="1"/>
  <Word word="" roman="sardine" star="1"/>
  <Word word="" roman="relay" star="1"/>
  <Word word="" roman="stair" star="1"/>
  <Word word="" roman="union" star="1"/>
  <Word word="" roman="sweetness" star="1"/>
  <Word word="" roman="universal" star="1"/>
  <Word word="" roman="twin" star="1"/>
  <Word word="" roman="sake" star="1"/>
  <Word word="" roman="teaching" star="1"/>
  <Word word="" roman="waken" star="1"/>
  <Word word="" roman="shred" star="1"/>
  <Word word="" roman="skyline" star="1"/>
  <Word word="" roman="sunk" star="1"/>
  <Word word="" roman="suicide" star="1"/>
  <Word word="" roman="sentimental" star="1"/>
  <Word word="" roman="reflex" star="1"/>
  <Word word="" roman="tadpole" star="1"/>
  <Word word="" roman="timid" star="1"/>
  <Word word="" roman="vivid" star="1"/>
  <Word word="" roman="violence" star="1"/>
  <Word word="" roman="rape" star="1"/>
  <Word word="" roman="rider" star="1"/>
  <Word word="" roman="satisfy" star="1"/>
  <Word word="" roman="relieve" star="1"/>
  <Word word="" roman="utmost" star="1"/>
  <Word word="" roman="semester" star="1"/>
  <Word word="" roman="shear" star="1"/>
  <Word word="" roman="villager" star="1"/>
  <Word word="" roman="vigor" star="1"/>
  <Word word="" roman="shelter" star="1"/>
  <Word word="" roman="speaking" star="1"/>
  <Word word="" roman="surplus" star="1"/>
  <Word word="" roman="standpoint" star="1"/>
  <Word word="" roman="whirl" star="1"/>
  <Word word="" roman="sanction" star="1"/>
  <Word word="" roman="scenery" star="1"/>
  <Word word="" roman="wipe" star="1"/>
  <Word word="" roman="retire" star="1"/>
  <Word word="" roman="reconstruction" star="1"/>
  <Word word="" roman="SOS" star="1"/>
  <Word word="" roman="stress" star="1"/>
  <Word word="" roman="source" star="1"/>
  <Word word="" roman="staple" star="1"/>
  <Word word="" roman="systematic" star="1"/>
  <Word word="" roman="spectrum" star="1"/>
  <Word word="" roman="university" star="1"/>
  <Word word="" roman="scientist" star="1"/>
  <Word word="" roman="stifle" star="1"/>
  <Word word="" roman="substance" star="1"/>
  <Word word="" roman="twentieth" star="1"/>
  <Word word="" roman="shrill" star="1"/>
  <Word word="" roman="somehow" star="1"/>
  <Word word="" roman="series" star="1"/>
  <Word word="" roman="wherever" star="1"/>
  <Word word="" roman="temporal" star="1"/>
  <Word word="" roman="spank" star="1"/>
  <Word word="" roman="sledge" star="1"/>
  <Word word="" roman="warning" star="1"/>
  <Word word="" roman="shuttle" star="1"/>
  <Word word="" roman="regret" star="1"/>
  <Word word="" roman="utensil" star="1"/>
  <Word word="" roman="successive" star="1"/>
  <Word word="" roman="ripple" star="1"/>
  <Word word="" roman="tenant" star="1"/>
  <Word word="" roman="suggestive" star="1"/>
  <Word word="" roman="slant" star="1"/>
  <Word word="" roman="testimony" star="1"/>
  <Word word="" roman="speculate" star="1"/>
  <Word word="" roman="tractor" star="1"/>
  <Word word="" roman="theology" star="1"/>
  <Word word="" roman="represent" star="1"/>
  <Word word="" roman="thistle" star="1"/>
  <Word word="" roman="sanatorium" star="1"/>
  <Word word="" roman="unusual" star="1"/>
  <Word word="" roman="spun" star="1"/>
  <Word word="" roman="supplement" star="1"/>
  <Word word="" roman="role" star="1"/>
  <Word word="" roman="retreat" star="1"/>
  <Word word="" roman="Xmas" star="1"/>
  <Word word="" roman="rebuke" star="1"/>
  <Word word="" roman="unjust" star="1"/>
  <Word word="" roman="regularly" star="1"/>
  <Word word="" roman="senate" star="1"/>
  <Word word="" roman="vital" star="1"/>
  <Word word="" roman="united" star="1"/>
  <Word word="" roman="utility" star="1"/>
  <Word word="" roman="unreasonable" star="1"/>
  <Word word="" roman="syllable" star="1"/>
  <Word word="" roman="shame" star="1"/>
  <Word word="" roman="wire" star="1"/>
  <Word word="" roman="sincere" star="1"/>
  <Word word="" roman="salute" star="1"/>
  <Word word="" roman="rusty" star="1"/>
  <Word word="" roman="shaft" star="1"/>
  <Word word="" roman="sprout" star="1"/>
  <Word word="" roman="scarf" star="1"/>
  <Word word="" roman="remark" star="1"/>
  <Word word="" roman="recall" star="1"/>
  <Word word="" roman="recollection" star="1"/>
  <Word word="" roman="shoemaker" star="1"/>
  <Word word="" roman="sphinx" star="1"/>
  <Word word="" roman="representative" star="1"/>
  <Word word="" roman="sunset" star="1"/>
  <Word word="" roman="stride" star="1"/>
  <Word word="" roman="somewhat" star="1"/>
  <Word word="" roman="squirrel" star="1"/>
  <Word word="" roman="socialism" star="1"/>
  <Word word="" roman="shed" star="1"/>
  <Word word="" roman="shown" star="1"/>
  <Word word="" roman="sodium" star="1"/>
  <Word word="" roman="swan" star="1"/>
  <Word word="" roman="strain" star="1"/>
  <Word word="" roman="traditional" star="1"/>
  <Word word="" roman="trail" star="1"/>
  <Word word="" roman="woven" star="1"/>
  <Word word="" roman="routine" star="1"/>
  <Word word="" roman="ripe" star="1"/>
  <Word word="" roman="turkey" star="1"/>
  <Word word="" roman="quiver" star="1"/>
  <Word word="" roman="quarrel" star="1"/>
  <Word word="" roman="scripture" star="1"/>
  <Word word="" roman="string" star="1"/>
  <Word word="" roman="spinning" star="1"/>
  <Word word="" roman="reference" star="1"/>
  <Word word="" roman="tiny" star="1"/>
  <Word word="" roman="reveal" star="1"/>
  <Word word="" roman="textile" star="1"/>
  <Word word="" roman="specter" star="1"/>
  <Word word="" roman="subjunctive" star="1"/>
  <Word word="" roman="ray" star="1"/>
  <Word word="" roman="sublime" star="1"/>
  <Word word="" roman="toothbrush" star="1"/>
  <Word word="" roman="spill" star="1"/>
  <Word word="" roman="scandal" star="1"/>
  <Word word="" roman="unite" star="1"/>
  <Word word="" roman="track" star="1"/>
  <Word word="" roman="visible" star="1"/>
  <Word word="" roman="sixteenth" star="1"/>
  <Word word="" roman="radioactive" star="1"/>
  <Word word="" roman="volume" star="1"/>
  <Word word="" roman="wet" star="1"/>
  <Word word="" roman="related" star="1"/>
  <Word word="" roman="seesaw" star="1"/>
  <Word word="" roman="significant" star="1"/>
  <Word word="" roman="tourist" star="1"/>
  <Word word="" roman="sorrow" star="1"/>
  <Word word="" roman="receiver" star="1"/>
  <Word word="" roman="revision" star="1"/>
  <Word word="" roman="structure" star="1"/>
  <Word word="" roman="scrub" star="1"/>
  <Word word="" roman="seashore" star="1"/>
  <Word word="" roman="squeeze" star="1"/>
  <Word word="" roman="stir" star="1"/>
  <Word word="" roman="skillful" star="1"/>
  <Word word="" roman="task" star="1"/>
  <Word word="" roman="strive" star="1"/>
  <Word word="" roman="roller" star="1"/>
  <Word word="" roman="teen-ager" star="1"/>
  <Word word="" roman="sprang" star="1"/>
  <Word word="" roman="reed" star="1"/>
  <Word word="" roman="twilight" star="1"/>
  <Word word="" roman="telegram" star="1"/>
  <Word word="" roman="tension" star="1"/>
  <Word word="" roman="radiant" star="1"/>
  <Word word="" roman="runner" star="1"/>
  <Word word="" roman="substantial" star="1"/>
  <Word word="" roman="relief" star="1"/>
  <Word word="" roman="submit" star="1"/>
  <Word word="" roman="throat" star="1"/>
  <Word word="" roman="thunder" star="1"/>
  <Word word="" roman="yarn" star="1"/>
  <Word word="" roman="trivial" star="1"/>
  <Word word="" roman="skyscraper" star="1"/>
  <Word word="" roman="sanctuary" star="1"/>
  <Word word="" roman="satin" star="1"/>
  <Word word="" roman="riddle" star="1"/>
  <Word word="" roman="triangle" star="1"/>
  <Word word="" roman="recompense" star="1"/>
  <Word word="" roman="shone" star="1"/>
  <Word word="" roman="stitch" star="1"/>
  <Word word="" roman="refresh" star="1"/>
  <Word word="" roman="reindeer" star="1"/>
  <Word word="" roman="sacred" star="1"/>
  <Word word="" roman="transform" star="1"/>
  <Word word="" roman="sunshine" star="1"/>
  <Word word="" roman="remedy" star="1"/>
  <Word word="" roman="spelling" star="1"/>
  <Word word="" roman="resistance" star="1"/>
  <Word word="" roman="transitive" star="1"/>
  <Word word="" roman="tailor" star="1"/>
  <Word word="" roman="strictly" star="1"/>
  <Word word="" roman="shellfish" star="1"/>
  <Word word="" roman="swimmer" star="1"/>
  <Word word="" roman="sue" star="1"/>
  <Word word="" roman="vehicle" star="1"/>
  <Word word="" roman="stab" star="1"/>
  <Word word="" roman="ransom" star="1"/>
  <Word word="" roman="sting" star="1"/>
  <Word word="" roman="typewriter" star="1"/>
  <Word word="" roman="verse" star="1"/>
  <Word word="" roman="surf" star="1"/>
  <Word word="" roman="rotten" star="1"/>
  <Word word="" roman="tempt" star="1"/>
  <Word word="" roman="shrewd" star="1"/>
  <Word word="" roman="tender" star="1"/>
  <Word word="" roman="serial" star="1"/>
  <Word word="" roman="sane" star="1"/>
  <Word word="" roman="sideboard" star="1"/>
  <Word word="" roman="self-defense" star="1"/>
  <Word word="" roman="romantic" star="1"/>
  <Word word="" roman="terminate" star="1"/>
  <Word word="" roman="reasonable" star="1"/>
  <Word word="" roman="relate" star="1"/>
  <Word word="" roman="wit" star="1"/>
  <Word word="" roman="scientific" star="1"/>
  <Word word="" roman="transit" star="1"/>
  <Word word="" roman="receipt" star="1"/>
  <Word word="" roman="shepherd" star="1"/>
  <Word word="" roman="timber" star="1"/>
  <Word word="" roman="recital" star="1"/>
  <Word word="" roman="sank" star="1"/>
  <Word word="" roman="spectacular" star="1"/>
  <Word word="" roman="rewrite" star="1"/>
  <Word word="" roman="starve" star="1"/>
  <Word word="" roman="stove" star="1"/>
  <Word word="" roman="speedy" star="1"/>
  <Word word="" roman="tablet" star="1"/>
  <Word word="" roman="scar" star="1"/>
  <Word word="" roman="yoke" star="1"/>
  <Word word="" roman="terminal" star="1"/>
  <Word word="" roman="virgin" star="1"/>
  <Word word="" roman="shook" star="1"/>
  <Word word="" roman="spiritual" star="1"/>
  <Word word="" roman="register" star="1"/>
  <Word word="" roman="roast" star="1"/>
  <Word word="" roman="steamboat" star="1"/>
  <Word word="" roman="thorough" star="1"/>
  <Word word="" roman="solid" star="1"/>
  <Word word="" roman="solar" star="1"/>
  <Word word="" roman="situation" star="1"/>
  <Word word="" roman="wholesome" star="1"/>
  <Word word="" roman="wail" star="1"/>
  <Word word="" roman="toothache" star="1"/>
  <Word word="" roman="seeming" star="1"/>
  <Word word="" roman="transmission" star="1"/>
  <Word word="" roman="unconscious" star="1"/>
  <Word word="" roman="statistics" star="1"/>
  <Word word="" roman="sponsor" star="1"/>
  <Word word="" roman="struggle" star="1"/>
</Words>